### ISSUE TITLE
Cumulative Rewards Incorrectly Trigger

### ISSUE THREAD

**Issue by delbertina** [BenCodez/VotingPlugin#1006]
**Versions**
Paper 1.16.3
VP - Latest beta build # 34

**Describe the bug**
I have cumulative rewards set for 100, 500 etc. Whenever someone triggers the 100 cumulative reward it gives them every cumulative reward beyond. It also tries to give them the first 2 cumulative rewards twice but I havent been able to find a reason why exactly those specific two twice. I'm 99% sure this wasn't a bug in 5.24.1 so sometime between then and the current dev build this bug may have been introduced.

**To Reproduce**
- Use the cumulative rewards linked below
- /av user [name] SetTotal AllTime 99 (or any number ending in 99)
- /av User [name ForceVote [any site name]
- Watch as it tries (and fails) to give the advancements multiple times. Can also just replace the advancement grant commands with broadcast commands to visualize the error better.

**Screenshots/Configs**
Cumulative Rewards - [https://pastebin.com/eGMiZ18J](https://pastebin.com/eGMiZ18J)
Console Debug Output - [https://pastebin.com/AAjxWVcR](https://pastebin.com/AAjxWVcR)

**Comment by BenCodez** [comment]
Cumulative gives every x number of votes, so every 100, 500, and etc in your case.

**Comment by delbertina** [comment]
I'm saying the bug is that when a player gets 100 total votes it triggers for 100 and 500 and 1,000 and 5,000 etc.

**Comment by BenCodez** [comment]
If the total votes divided by the cumulative amount equals 0 the reward is given.

My guess is that you want to use milestones.

**Comment by delbertina** [comment]
I feel like there's a misunderstanding happening here so I'll explain a little big more. 

I get that if there's cumulative rewards for 10, 50, and 100 that going from 99 to 100 votes will trigger all 3 of those. What is happening is that with cumulative rewards set at 100, 500, 1,000, 5,000 etc going from 99 total votes to 100 triggers for 100, 500, 1,000, 5,000 etc. To me this is not the expected behavior because the user has less than that number. 100 is less than 500, 100 is less than 1,000, 100 is less than 5,000 etc.

I tested this functionality in 5.24.1 with the steps I provided to reproduce and it works as expected.
Tested in the 6.0 build # 13 (the earliest listed build) and the bug is present in that build too.
Also tested in the latest master branch dev build # 448 

This tells me that the bug was introduced in one of the first 12 commits of the 6.0 branch. Hopefully that helps in finding the root cause of this.

**Comment by BenCodez** [comment]
Are you using bungee version of votingplugin? Changes were made (in 6.0) to cumulative so that bungee would provide the totals to handle if using pluginmessaging.

**Comment by delbertina** [comment]
I'm not using bungee, no. I'm using the builds from here when I say the 6.0 dev builds. [http://bencodez.com/job/VotingPlugin-6.0/](http://bencodez.com/job/VotingPlugin-6.0/)

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin-6.0/

Try build 38

**Comment by delbertina** [comment]
Still having the issue after using build 38. Here's the debug output from console. [https://pastebin.com/sCa8fvzq](https://pastebin.com/sCa8fvzq)

**Comment by BenCodez** [comment]
Build 39?

**Comment by delbertina** [comment]
As far as I tell that seems to have fixed it, but I am getting this error in console when forcing a vote.


```
[14:23:51] [Craft Scheduler Thread - 18/ERROR]: Could not pass event PlayerVoteEvent to VotingPlugin v5.24.1
java.lang.NullPointerException: null
	at com.Ben12345rocks.VotingPlugin.SpecialRewards.SpecialRewards.checkMilestone(SpecialRewards.java:175) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Listeners.PlayerVoteListener.onplayerVote(PlayerVoteListener.java:170) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor958.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-221]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.3.jar:git-Paper-221]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-221]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-221]
	at com.Ben12345rocks.VotingPlugin.Commands.CommandLoader$32.execute(CommandLoader.java:757) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.CommandAPI.CommandHandler$1.run(CommandHandler.java:378) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-221]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.3.jar:git-Paper-221]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Paper-221]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_171]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
```

**Comment by BenCodez** [comment]
Build 40 should fix that.

**Comment by delbertina** [comment]
Seems to have done the trick and fixed the bug with no more of the console errors. As far as I can tell, the bug is fixed now.
