### ISSUE TITLE
java.lang.IndexOutOfBoundsException: No group 1

### ISSUE THREAD

**Issue by AfkF24** [BenCodez/VotingPlugin#1023]
**Versions**
VotingPlugin 5.24.1, Paper 1.16.4 - build 262

**Describe the bug**
Basically, purchasing the package below through the vote shop throws a warning even though the command gets correctly sent by console. It's just for this specific package as others are completely fine.
```
[08:25:49 INFO]: AfkF24 issued server command: /voteshop
[08:25:52 WARN]: java.lang.IndexOutOfBoundsException: No group 1
[08:25:52 WARN]:        at java.util.regex.Matcher.start(Matcher.java:375)
[08:25:52 WARN]:        at java.util.regex.Matcher.appendReplacement(Matcher.java:880)
[08:25:52 WARN]:        at java.util.regex.Matcher.replaceAll(Matcher.java:955)
[08:25:52 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Messages.StringParser.replaceIgnoreCase(StringParser.java:235)
[08:25:52 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Messages.StringParser.replacePlaceHolder(StringParser.java:352)
[08:25:52 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Messages.StringParser.replacePlaceHolder(StringParser.java:347)
[08:25:52 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Messages.StringParser.replacePlaceHolder(StringParser.java:320)
[08:25:52 WARN]:        at com.Ben12345rocks.VotingPlugin.Commands.GUI.PlayerGUIs$8.onClick(PlayerGUIs.java:348)
[08:25:52 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Inventory.BInventoryButton.onClick(BInventoryButton.java:145)
[08:25:52 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Inventory.BInventory.onClick(BInventory.java:438)
[08:25:52 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Inventory.BInventory.access$300(BInventory.java:41)
[08:25:52 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Inventory.BInventory$3.run(BInventory.java:507)
[08:25:52 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[08:25:52 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[08:25:52 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[08:25:52 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[08:25:52 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[08:25:52 WARN]:        at java.lang.Thread.run(Thread.java:748)
[08:25:52 INFO]: CONSOLE issued server command: /eco give AfkF24 10
```

**Screenshots/Configs**
```yaml
  Money:
    Identifier_Name: '$10'
    Material: 'SUNFLOWER'
    Data: 0
    Amount: 1
    Name: '$10'
    Lore:
    - '&aBuy now!'
    Cost: 10
    Permission: ''
    Rewards:
      Commands:
      - 'eco give %player% 10'
```

**Additional context**
Important thing to note is that the reward gets added to the player, its just the warning that pops up before that. Other packages using commands as rewards (other than `eco`) also work just fine.

**Comment by BenCodez** [comment]
Config.yml?
