### ISSUE TITLE
Bungee with MYSQL keeps breaking with no reason

### ISSUE THREAD

**Issue by plebexer** [BenCodez/VotingPlugin#1025]
**Versions**
I use the lastest version of FlameCord for my proxy
in my servers i have the lastest version of paper 1.15.2 (they are not updating 1.15.2 too much

**Describe the bug**
I have my setup with MYSQL to have all the points trough all the network, so if someone buys something with points in the survival server they will get those points removed in the whole network, just as if it where one server, i checked everything and i did everything as intended except for one thing, i proxy the votes to where the player is connected, not to the hub only because i want the server to get some rewards also when voting and i want them to get those depending on the server they are, when i finished the setup i tested the plugin with my staff and everything was fine, if i used the points in the survival server and then go to the hub they were also removed there, but when a certain amount of players is reached, the plugin starts to break itself and basically gives infinite points, this mostly starts to happen when i reach 30+ players in one server, the voting plugin breaks and if i buy something in one server and then go to another the points dont get removed and i get the same amount of points i had before and i could do this as many times as i want, i really dont know what else to do, i dont know if there is another setup that i can get all the vote points trough the whole network as easily as this one.

i tried everything and i checked the faq but that does not help in my case because one day is working fine and the other day it breaks itself

video: (sorry if you dont understand, my server is in spanish)

https://youtu.be/bDD-ZsdViuw

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/wiki/Bungeecoord-Setups

What setup are you using?

Did you enable clear cache options? (All of them should be enabled)

**Comment by plebexer** [comment]
im using BungeeMethod MYSQL, and yes i followed the tutorial as it should be
(except for how votifier sends the votes, as i explained above)

**Comment by plebexer** [comment]
```
ClearCacheOnUpdate: true

# Clear cache on player join always
ClearCacheOnJoin: true

# Clears cache for the player who voted only
# Only effects if using mysql
# Would recommend for some bungee setups
ClearCacheOnVote: true

# Clear cache when player leaves
ClearCacheOnLeave: true

ClearCacheOnVoteShopPurchase: true
```

**Comment by BenCodez** [comment]
You have the latest version of votingplugin?

**Comment by plebexer** [comment]
yes i do have the lastest version updated to spigot

**Comment by BenCodez** [comment]
What version exactly as stated by /av version? 

The latest version should send point related queries immediately to the database to prevent issue like this. If you have all the clear cache options enabled on each server then I can't really do any more without more details on your setup. You could try PLUGINMESSAGING setup (Will require latest 6.0 dev build for one reward per vote on the network, from bencodez.com)

**Comment by plebexer** [comment]
VotingPlugin Version 5.24.1

**Comment by BenCodez** [comment]
Wanna send your bungeesettings.yml?

**Comment by plebexer** [comment]
yes
in the proxy or in all of the servers?

**Comment by BenCodez** [comment]
spigot servers

**Comment by plebexer** [comment]
this is the config i have for the hub:
https://pastebin.com/TGtn0Ane

**Comment by plebexer** [comment]
it would be the same on the others servers

**Comment by BenCodez** [comment]
Wanna send the config.yml as well?

**Comment by plebexer** [comment]
yes

**Comment by plebexer** [comment]
hub config:
https://pastebin.com/JCJxf1tv

**Comment by plebexer** [comment]
also i was just checking and i think i dont have the lastest version on the hub, i think i have the version 5.23.3 there, maybe i forgot to update it, could that be causing this?

**Comment by plebexer** [comment]
i do have the lastest version in survival anyways
i forgot to update the hub version

**Comment by BenCodez** [comment]
You should have the latest version on all servers

**Comment by BenCodez** [comment]
If it doesn't work I would use pluginmessaging (with 6.0 version I said above) and see how that works.

**Comment by plebexer** [comment]
okay, i will try updating that once i can and i will notify you here what happens

**Comment by plebexer** [comment]
i have something else to ask anyways, for some reason today the plugin broke but because lots of people were voting, but then i disabled the command and now when i try it after some time it seems to work fine again, even with the hub in the older version,
could this be related to something else? or is that what you fixed on the lastest version?.
could it be related with some kind of limit in mysql?

**Comment by plebexer** [comment]
because this changes depending on the amount of players using the plugin and voting for the server

**Comment by BenCodez** [comment]
What do you mean by the plugin broke? Errors or something?

The way I recommend setting it up would be with PLUGINMESSAGING

**Comment by plebexer** [comment]
i mean that it broke the way i explained above, the plugin gives you infinite votepoints because they dont update in all of the servers, but then it starts working again if no one uses it and only i use it myself

**Comment by plebexer** [comment]
is it posible to set the same votepoints in the whole network with PLUGINMESSAGING? because that is what i want to do

**Comment by BenCodez** [comment]
Try with a higher max connection setting?

And yes vote points are synced across with plugin messaging.

**Comment by plebexer** [comment]
Lastest version wont load in my hub server :(

```
[00:32:07] [Server thread/ERROR]: Could not load 'plugins/VotingPlugin.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:84) ~[patched_1.15.2.jar:git-Paper-390]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.15.2.jar:git-Paper-390]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.15.2.jar:git-Paper-390]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.15.2.jar:git-Paper-390]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-390]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-390]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
Caused by: org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:170) ~[patched_1.15.2.jar:git-Paper-390]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:82) ~[patched_1.15.2.jar:git-Paper-390]
	... 6 more
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_272]
	at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_272]
	at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_272]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_272]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_272]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:158) ~[patched_1.15.2.jar:git-Paper-390]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:82) ~[patched_1.15.2.jar:git-Paper-390]
	... 6 more
```

**Comment by BenCodez** [comment]
Redownload the jar

**Comment by plebexer** [comment]
everything seems to be working better now, i just got 2 reports of votes dissappearing

**Comment by BenCodez** [comment]
Is there any errors?
Your using pluginmessaging correct?

**Comment by plebexer** [comment]
im using mysql

**Comment by plebexer** [comment]
i will change to pluginmessaging anyways rn

**Comment by plebexer** [comment]
im downloading the lastest dev version to do it as you said

**Comment by plebexer** [comment]
ok so i was checking and in the PLUGINMESSAGING setup it only sends to one server, or to every server, but i want this to be on sinc, for example if a player has one vote in survival he will have it on the hub server, if he spends it on the hub server he will not have the votes he spent in the whole network

**Comment by plebexer** [comment]
oh, and also with the MYSQL setup i started getting this message:
```
[13:11:01 WARN]: org.bukkit.plugin.messaging.ChannelNotRegisteredException: Attempted to send a plugin message through the unregistered channel `votingplugin:votingplugin'.
[13:11:01 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.validatePluginMessage(StandardMessenger.java:544)
[13:11:01 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.sendPluginMessage(CraftPlayer.java:1453)
[13:11:01 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.PluginMessage.PluginMessage.sendPluginMessage(PluginMessage.java:90)
[13:11:01 WARN]:        at com.Ben12345rocks.VotingPlugin.Listeners.PlayerVoteListener$1.run(PlayerVoteListener.java:178)
[13:11:01 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[13:11:01 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[13:11:01 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:11:01 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:11:01 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:11:01 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by BenCodez** [comment]
Are you asking for a per server setup, separate storage? You also need to restart for the bungee setups.

**Comment by plebexer** [comment]
i did not go to pluginmessaging because i dont know how to set it up properly, because in the page the only option it gives is votes per server in the network but i want votes in all of the network to be the same.
so i tried to stick with mysql and i also saw this when shutting down one server:

[16:00:57 INFO]: [VotingPlugin] Shutting down mysql, query size: 914
[16:00:57 INFO]: [VotingPlugin] Shutting down mysql, queries to do: 914, if number is higher than 1000, then something may be wrong

**Comment by BenCodez** [comment]
All bungee methods support global voting. You can use the latest dev build here, should solve the mysql thing:
http://bencodez.com/job/VotingPlugin-6.0/
