### ISSUE TITLE
Console Spam Error

### ISSUE THREAD

**Issue by Khosraw** [BenCodez/VotingPlugin#1040]
**Versions**
This server is running Purpur version git-Purpur-606 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT), [15:50:14 INFO]: VotingPlugin version 5.13.6

**Describe the bug**
Really just getting errors in the console that prevent me from getting vote rewards. I am not sure what exactly is causing it so the best I can do is give you an error.

`[14:29:23 WARN]: [VotingPlugin] Plugin VotingPlugin v5.13.6 generated an exception while executing task 324691
java.lang.IllegalStateException: PlayerVoteEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:595) ~[patched_1.15.2.jar:git-Purpur-606]
        at com.Ben12345rocks.VotingPlugin.Events.VotiferEvent$2.run(VotiferEvent.java:191) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Purpur-606]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Purpur-606]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Purpur-606]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]`

Also it's spamming in the console...

**To Reproduce**
Don't exactly know how to reproduce it other than using the version above with the plugin. Down there are my config file and rewards file in case there is an issue there.

**Expected behavior**
I expected to get rewards like normal when I vote but instead get these errors.

**Screenshots/Configs**
[Config.txt](https://github.com/BenCodez/VotingPlugin/files/5577946/Config.txt)
[VoteSites.txt](https://github.com/BenCodez/VotingPlugin/files/5577947/VoteSites.txt)

**Comment by BenCodez** [comment]
VotingPlugin v5.13.6

Maybe update....

**Comment by Khosraw** [comment]
> VotingPlugin v5.13.6
> 
> Maybe update....

I just realized that lol

**Comment by Khosraw** [comment]
> VotingPlugin v5.13.6
> 
> Maybe update....

You can close this!
