### ISSUE TITLE
Error in console waterfall/bungee

### ISSUE THREAD

**Issue by Tylwen** [BenCodez/VotingPlugin#1050]
**Versions**
Plugin version : 6.0 and spigot version Paper-253

**Describe the bug**
When we vote, the proxy displays an error but we still receive the rewards on the servers.

**Expected behavior**
That there is no such mistake.

**Screenshots/Configs**
[21:59:35 ERROR]: java.net.ConnectException: Connection refused (Connection refused)
[21:59:35 ERROR]:       at java.net.PlainSocketImpl.socketConnect(Native Method)
[21:59:35 ERROR]:       at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[21:59:35 ERROR]:       at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[21:59:35 ERROR]:       at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[21:59:35 ERROR]:       at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[21:59:35 ERROR]:       at java.net.Socket.connect(Socket.java:607)
[21:59:35 ERROR]:       at java.net.Socket.connect(Socket.java:556)
[21:59:35 ERROR]:       at java.net.Socket.<init>(Socket.java:452)
[21:59:35 ERROR]:       at java.net.Socket.<init>(Socket.java:229)
[21:59:35 ERROR]:       at com.bencodez.votingplugin.advancedcore.bungeeapi.sockets.ClientHandler.connect(ClientHandler.java:35)
[21:59:35 ERROR]:       at com.bencodez.votingplugin.advancedcore.bungeeapi.sockets.ClientHandler.sendMessage(ClientHandler.java:46)
[21:59:35 ERROR]:       at com.bencodez.votingplugin.advancedcore.bungeeapi.sockets.ClientHandler.sendMessage(ClientHandler.java:63)
[21:59:35 ERROR]:       at com.bencodez.votingplugin.bungee.VotingPluginBungee.sendServerMessage(VotingPluginBungee.java:451)
[21:59:35 ERROR]:       at com.bencodez.votingplugin.bungee.VotingPluginBungee.sendSocketVote(VotingPluginBungee.java:485)
[21:59:35 ERROR]:       at com.bencodez.votingplugin.bungee.VotingPluginBungee.vote(VotingPluginBungee.java:502)
[21:59:35 ERROR]:       at com.bencodez.votingplugin.bungee.VotingPluginBungee.onVote(VotingPluginBungee.java:401)
[21:59:35 ERROR]:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:59:35 ERROR]:       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:59:35 ERROR]:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:59:35 ERROR]:       at java.lang.reflect.Method.invoke(Method.java:498)
[21:59:35 ERROR]:       at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
[21:59:35 ERROR]:       at net.md_5.bungee.event.EventBus.post(EventBus.java:47)
[21:59:35 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:453)
[21:59:35 ERROR]:       at com.vexsoftware.votifier.bungee.NuVotifier.lambda$onVoteReceived$2(NuVotifier.java:366)
[21:59:35 ERROR]:       at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
[21:59:35 ERROR]:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[21:59:35 ERROR]:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[21:59:35 ERROR]:       at java.lang.Thread.run(Thread.java:748)
[21:59:35 WARN]: Error dispatching event com.vexsoftware.votifier.bungee.events.VotifierEvent@d17b2a to listener com.bencodez.votingplugin.bungee.VotingPluginBungee@75e710b
java.lang.NullPointerException: null
        at com.bencodez.votingplugin.advancedcore.bungeeapi.sockets.ClientHandler.sendMessage(ClientHandler.java:54) ~[?:?]
        at com.bencodez.votingplugin.advancedcore.bungeeapi.sockets.ClientHandler.sendMessage(ClientHandler.java:63) ~[?:?]
        at com.bencodez.votingplugin.bungee.VotingPluginBungee.sendServerMessage(VotingPluginBungee.java:451) ~[?:?]
        at com.bencodez.votingplugin.bungee.VotingPluginBungee.sendSocketVote(VotingPluginBungee.java:485) ~[?:?]
        at com.bencodez.votingplugin.bungee.VotingPluginBungee.vote(VotingPluginBungee.java:502) ~[?:?]
        at com.bencodez.votingplugin.bungee.VotingPluginBungee.onVote(VotingPluginBungee.java:401) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:1d2221d:384]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:1d2221d:384]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:453) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:1d2221d:384]
        at com.vexsoftware.votifier.bungee.NuVotifier.lambda$onVoteReceived$2(NuVotifier.java:366) ~[?:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:1d2221d:384]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_275]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

**Comment by BenCodez** [comment]
Why are you using the socket method in votingplugin?

https://github.com/BenCodez/VotingPlugin/wiki/Bungeecoord-Setups

**Comment by Tylwen** [comment]
It is not clear what is written
I dont understand

**Comment by BenCodez** [comment]
Use one of the methods listed on the wiki page.
