### ISSUE TITLE
/voteall

### ISSUE THREAD

**Issue by elaineandsparky** [BenCodez/VotingPlugin#1052]
Version: 6:0

The command /voteall used to bring up a link for all the votesites in chat but doesn't any more. (no chat/message error just doesn't do anything)

Has this been removed/broken?

**Comment by MCD4U** [comment]
I am experiencing the same problem, here's a relevant console log of the error:
```
26.11 13:18:27 [Server] WARN [VotingPlugin] Plugin VotingPlugin v6.0 generated an exception while executing task 1154644
26.11 13:18:27 [Server] INFO java.lang.NullPointerException: null
26.11 13:18:27 [Server] INFO at com.bencodez.votingplugin.commands.gui.player.VoteURL.<init>(VoteURL.java:44) ~[?:?]
26.11 13:18:27 [Server] INFO at com.bencodez.votingplugin.commands.CommandLoader$100.execute(CommandLoader.java:1941) ~[?:?]
26.11 13:18:27 [Server] INFO at com.bencodez.votingplugin.advancedcore.api.command.CommandHandler$1.run(CommandHandler.java:401) ~[?:?]
26.11 13:18:27 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-206]
26.11 13:18:27 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.3.jar:git-Paper-206]
26.11 13:18:27 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Paper-206]
26.11 13:18:27 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
26.11 13:18:27 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
26.11 13:18:27 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin/

How's that?

**Comment by MCD4U** [comment]
The error no longer shows up, but now it brings up the voting gui when I type /voteall or /votelist. Isn't it supposed to list all the votesites with their urls in chat?

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin/
.
I guess I accidently changed that in the update. That build should do it.

**Comment by MCD4U** [comment]
Thank you, this build worked
