### ISSUE TITLE
Vote GUI

### ISSUE THREAD

**Issue by Bszem** [BenCodez/VotingPlugin#1071]
**Versions**
Plugin version and spigot version.
Plugin version 6.0.1
Spigot version 1.12.2

**Describe the bug**
When I command /vote gui, it won't open

**To Reproduce**

**Expected behavior**
Wanted gui to open

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.
[12:21:12 WARN]: [VotingPlugin] Plugin VotingPlugin v6.0.1 generated an exception while executing task 143468
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.CLOCK
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_272]
        at org.bukkit.Material.valueOf(Material.java:71) ~[patched_1.12.2.jar:git-Paper-1618]
        at com.bencodez.votingplugin.advancedcore.api.item.ItemBuilder.<init>(ItemBuilder.java:119) ~[?:?]
        at com.bencodez.votingplugin.commands.gui.player.VoteGUI.getItemSlot(VoteGUI.java:38) ~[?:?]
        at com.bencodez.votingplugin.commands.gui.player.VoteGUI.onChest(VoteGUI.java:134) ~[?:?]
        at com.bencodez.votingplugin.advancedcore.api.gui.GUIHandler.open(GUIHandler.java:53) ~[?:?]
        at com.bencodez.votingplugin.commands.gui.player.VoteGUI.open(VoteGUI.java:194) ~[?:?]
        at com.bencodez.votingplugin.commands.CommandLoader$79.execute(CommandLoader.java:1664) ~[?:?]
        at com.bencodez.votingplugin.advancedcore.api.command.CommandHandler$1.run(CommandHandler.java:401) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1618]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_272]
**Additional context**

**Comment by BenCodez** [comment]
You need to modify the materials so it uses 1.12 materials
