### ISSUE TITLE
Error Console on join

### ISSUE THREAD

**Issue by SpiderAang** [BenCodez/VotingPlugin#1079]
**Versions**
6.0.3

**Describe the bug**
> [10:08:48] [Craft Scheduler Thread - 11/WARN]: [CTSNCPlus] Plugin CTSNCPlus v9.1 generated an exception while executing task 47
java.lang.NoClassDefFoundError: com/Ben12345rocks/VotingPlugin/UserManager/UserManager
at de.Herbystar.CTSNCPlus.ReplaceString.replaceString(ReplaceString.java:235) ~[?:?]
at de.Herbystar.CTSNCPlus.Tablist$1.run(Tablist.java:30) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
> [10:08:48] [Craft Scheduler Thread - 0/WARN]: [CTSNCPlus] Plugin CTSNCPlus v9.1 generated an exception while executing task 47
java.lang.NoClassDefFoundError: com/Ben12345rocks/VotingPlugin/UserManager/UserManager
at de.Herbystar.CTSNCPlus.ReplaceString.replaceString(ReplaceString.java:235) ~[?:?]
at de.Herbystar.CTSNCPlus.Tablist$1.run(Tablist.java:30) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

**To Reproduce**
1. install the CTSNCPlus plugin and votingPlugin
2. enable rewards on ofline players
3. enable scorebar on ctsncplus and put money player.
4. vote as offline and join on server.
5. see error

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.

**Comment by BenCodez** [comment]
That plugin needs to update for votingplugin 6.0 api
