### ISSUE TITLE
Error and not able to access the main GUI

### ISSUE THREAD

**Issue by Khosraw** [BenCodez/VotingPlugin#1082]
**Versions**
VotingPlugin 6.0.4, Paper version git-Paper-33d42c8e (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Describe the bug**
After doing /vote and trying to go to the main menu with the leaderboard and stuff by clicking the barrier, it does nothing. After clicking it a few times it closes the entire menu and gives the following error in the console:

`[20:02:36 WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.CLOCK
[20:02:36 WARN]:        at java.lang.Enum.valueOf(Enum.java:238)
[20:02:36 WARN]:        at org.bukkit.Material.valueOf(Material.java:71)
[20:02:36 WARN]:        at com.bencodez.votingplugin.advancedcore.api.item.ItemBuilder.<init>(ItemBuilder.java:119)
[20:02:36 WARN]:        at com.bencodez.votingplugin.commands.gui.player.VoteGUI.getItemSlot(VoteGUI.java:38)
[20:02:36 WARN]:        at com.bencodez.votingplugin.commands.gui.player.VoteGUI.onChest(VoteGUI.java:134)
[20:02:36 WARN]:        at com.bencodez.votingplugin.advancedcore.api.gui.GUIHandler.open(GUIHandler.java:53)
[20:02:36 WARN]:        at com.bencodez.votingplugin.commands.CommandLoader$1.onClick(CommandLoader.java:112)
[20:02:36 WARN]:        at com.bencodez.votingplugin.advancedcore.api.inventory.BInventoryButton.onClick(BInventoryButton.java:140)
[20:02:36 WARN]:        at com.bencodez.votingplugin.advancedcore.api.inventory.BInventory.onClick(BInventory.java:404)
[20:02:36 WARN]:        at com.bencodez.votingplugin.advancedcore.api.inventory.BInventoryListener$2.run(BInventoryListener.java:94)
[20:02:36 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[20:02:36 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[20:02:36 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:02:36 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[20:02:36 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[20:02:36 WARN]:        at java.lang.Thread.run(Thread.java:748)`

**To Reproduce**
1. Download VotingPlugin and put it in the plugins folder
2. Restart the server
3. Type /vote
4. Click the barrier to go to the main menu
5. Check console for errror

(I am not sure if this happens on other servers the same way)

**Expected behavior**
Should be able to access the main GUI without any errors. Also found out that trying to get there in any other way such as /vote best will end up giving a similar error.

**Screenshots/Configs**
https://pastebin.com/nmEgMkuf

**Comment by BenCodez** [comment]
You'll need to change the material for 1.12

**Comment by Khosraw** [comment]
> You'll need to change the material for 1.12

Which material exactly?

**Comment by BenCodez** [comment]
CLOCK

**Comment by Khosraw** [comment]
> CLOCK

I got this error after fixing that:
`[02:22:33 WARN]: [VotingPlugin] Plugin VotingPlugin v6.0.4 generated an exception while executing task 45503
java.lang.NoSuchFieldError: BLACK_STAINED_GLASS_PANE
        at com.bencodez.votingplugin.advancedcore.api.inventory.BInventory.openInventory(BInventory.java:497) ~[?:?]
        at com.bencodez.votingplugin.advancedcore.api.inventory.BInventory.openInventory(BInventory.java:454) ~[?:?]
        at com.bencodez.votingplugin.commands.gui.player.VoteTopVoter.onChest(VoteTopVoter.java:133) ~[?:?]
        at com.bencodez.votingplugin.advancedcore.api.gui.GUIHandler.open(GUIHandler.java:53) ~[?:?]
        at com.bencodez.votingplugin.commands.gui.player.VoteGUI$1.onClick(VoteGUI.java:163) ~[?:?]
        at com.bencodez.votingplugin.advancedcore.api.inventory.BInventoryButton.onClick(BInventoryButton.java:140) ~[?:?]
        at com.bencodez.votingplugin.advancedcore.api.inventory.BInventory.onClick(BInventory.java:404) ~[?:?]
        at com.bencodez.votingplugin.advancedcore.api.inventory.BInventoryListener$2.run(BInventoryListener.java:94) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[kSpigot.jar:git-Paper-33d42c8e]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[kSpigot.jar:git-Paper-33d42c8e]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[kSpigot.jar:git-Paper-33d42c8e]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]`

Though I am not sure where that material is.

**Comment by BenCodez** [comment]
In the config.yml it is

      # Prev/Next page tems in GUIs
      PrevItem:
        Material: 'BLACK_STAINED_GLASS_PANE'
        Amount: 1
        Name: '&aPrevious Page'
        
      NextItem:
        Material: 'BLACK_STAINED_GLASS_PANE'
        Amount: 1
        Name: '&aNext Page'

**Comment by Khosraw** [comment]
> In the config.yml it is
> 
> ```
>   # Prev/Next page tems in GUIs
>   PrevItem:
>     Material: 'BLACK_STAINED_GLASS_PANE'
>     Amount: 1
>     Name: '&aPrevious Page'
>     
>   NextItem:
>     Material: 'BLACK_STAINED_GLASS_PANE'
>     Amount: 1
>     Name: '&aNext Page'
> ```

Weird because in my config.yml I don't even have that. I will add it and see if that fixes it.

**Comment by BenCodez** [comment]
Your config might be from an older version?
