### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by 1337god** [BenCodez/VotingPlugin#1085]
**Versions**
VotingPlugin v6.0.4

**Describe the bug**
Database error

**To Reproduce**
```[12:49:02 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-services' at line 1
[12:49:02 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[12:49:02 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[12:49:02 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[12:49:02 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[12:49:02 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
[12:49:02 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:386)
[12:49:02 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[12:49:02 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
[12:49:02 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
[12:49:02 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[12:49:02 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
[12:49:02 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
[12:49:02 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915)
[12:49:02 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2136)
[12:49:02 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2070)
[12:49:02 WARN]:        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5187)
[12:49:02 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2055)
[12:49:02 WARN]:        at com.bencodez.votingplugin.advancedcore.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[12:49:02 WARN]:        at com.bencodez.votingplugin.advancedcore.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[12:49:02 WARN]:        at com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.queries.Query.executeUpdate(Query.java:150)
[12:49:02 WARN]:        at com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.MySQL.<init>(MySQL.java:132)
[12:49:02 WARN]:        at com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin$10.run(AdvancedCorePlugin.java:606)
[12:49:02 WARN]:        at com.bencodez.votingplugin.advancedcore.thread.Thread$ReadThread.run(Thread.java:48)
[12:49:02 WARN]:        at com.bencodez.votingplugin.advancedcore.thread.Thread.run(Thread.java:101)
[12:49:02 WARN]:        at com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadUserAPI(AdvancedCorePlugin.java:601)
[12:49:02 WARN]:        at com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadConfig(AdvancedCorePlugin.java:354)
[12:49:02 WARN]:        at com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadHook(AdvancedCorePlugin.java:394)
[12:49:02 WARN]:        at com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.onEnable(AdvancedCorePlugin.java:777)
[12:49:02 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[12:49:02 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[12:49:02 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[12:49:02 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[12:49:02 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[12:49:02 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:469)
[12:49:02 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239)
[12:49:02 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936)
[12:49:02 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[12:49:02 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)```

**Comment by BenCodez** [comment]
Is that all to the error? Send full startup log?

**Comment by 1337god** [comment]
That's all there is to it
```[17:15:23 INFO]: [VotingPlugin] Enabling VotingPlugin v6.0.4
[17:15:23 INFO]: [BetterSleeping3] You are using the latest version: 3.0.4
[17:15:23 WARN]: [VotingPlugin] Detected no voting sites, this may mean something isn't properly setup
[17:15:23 INFO]: [com.bencodez.votingplugin.advancedcore.hikari.HikariDataSource] HikariPool-1 - Starting...
[17:15:24 INFO]: [com.bencodez.votingplugin.advancedcore.hikari.HikariDataSource] HikariPool-1 - Start completed.
[17:15:24 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-services' at line 1
[17:15:24 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[17:15:24 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[17:15:24 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[17:15:24 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[17:15:24 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
[17:15:24 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:386)
[17:15:24 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[17:15:24 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
[17:15:24 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
[17:15:24 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[17:15:24 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
[17:15:24 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
[17:15:24 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915)
[17:15:24 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2136)
[17:15:24 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2070)
[17:15:24 WARN]:        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5187)
[17:15:24 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2055)
[17:15:24 WARN]:        at com.bencodez.votingplugin.advancedcore.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[17:15:24 WARN]:        at com.bencodez.votingplugin.advancedcore.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[17:15:24 WARN]:        at com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.queries.Query.executeUpdate(Query.java:150)
[17:15:24 WARN]:        at com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.MySQL.<init>(MySQL.java:132)
[17:15:24 WARN]:        at com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin$10.run(AdvancedCorePlugin.java:606)
[17:15:24 WARN]:        at com.bencodez.votingplugin.advancedcore.thread.Thread$ReadThread.run(Thread.java:48)
[17:15:24 WARN]:        at com.bencodez.votingplugin.advancedcore.thread.Thread.run(Thread.java:101)
[17:15:24 WARN]:        at com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadUserAPI(AdvancedCorePlugin.java:601)
[17:15:24 WARN]:        at com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadConfig(AdvancedCorePlugin.java:354)
[17:15:24 WARN]:        at com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadHook(AdvancedCorePlugin.java:394)
[17:15:24 WARN]:        at com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.onEnable(AdvancedCorePlugin.java:777)
[17:15:24 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[17:15:24 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[17:15:24 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[17:15:24 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[17:15:24 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[17:15:24 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:469)
[17:15:24 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239)
[17:15:24 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936)
[17:15:24 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[17:15:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)```

**Comment by BenCodez** [comment]
Config.yml?
