### ISSUE TITLE
Empty Username field for non joined players.

### ISSUE THREAD

**Issue by Skizzles** [BenCodez/VotingPlugin#1093]
**Versions**
Plugin version: 6.0.4
Spigot: 1.16.4

**Describe the bug**
Username shows empty when a player has not joined that specific server.

**To Reproduce**
Attempt voting from the network on a joined mode when not on that specific mode
See empty field

**Expected behavior**
Username shown even for non joined users

**Screenshots/Configs**
https://screenshots.skizzles.me/wAnA3/GAwiTAqu19.png

**Additional context**
[22:38:13 INFO]: Void Realms »  has voted for the server on Vote Site 5!
[22:38:13 WARN]: java.lang.IllegalArgumentException: Name cannot be empty
[22:38:13 WARN]:        at org.apache.commons.lang.Validate.notEmpty(Validate.java:321)
[22:38:13 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.getOfflinePlayer(CraftServer.java:1574)
[22:38:13 WARN]:        at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:928)
[22:38:13 WARN]:        at com.bencodez.votingplugin.advancedcore.api.misc.PlayerUtils.getUUID(PlayerUtils.java:191)
[22:38:13 WARN]:        at com.bencodez.votingplugin.advancedcore.api.user.AdvancedCoreUser.<init>(AdvancedCoreUser.java:90)
[22:38:13 WARN]:        at com.bencodez.votingplugin.user.VotingPluginUser.<init>(VotingPluginUser.java:52)
[22:38:13 WARN]:        at com.bencodez.votingplugin.user.UserManager.getVotingPluginUser(UserManager.java:58)
[22:38:13 WARN]:        at com.bencodez.votingplugin.listeners.PlayerVoteListener.onplayerVote(PlayerVoteListener.java:81)
[22:38:13 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1092.execute(Unknown Source)
[22:38:13 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[22:38:13 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[22:38:13 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[22:38:13 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[22:38:13 WARN]:        at com.bencodez.votingplugin.user.VotingPluginUser$3.run(VotingPluginUser.java:210)
[22:38:13 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[22:38:13 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
[22:38:13 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:38:13 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[22:38:13 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[22:38:13 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by BenCodez** [comment]
Are you using a bungee method?

**Comment by Skizzles** [comment]
Pluginmessaging yes

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin/

That better? Anything on bungee log as well?

**Comment by Skizzles** [comment]
I don't see anything in bungee log, will give this a go

**Comment by Skizzles** [comment]
Started throwing this, then I set AllowUnjoined to true
[00:17:27 INFO]: Void Realms »  has voted for the server on Vote Site 5!
[00:17:27 WARN]: [VotingPlugin] Player  has not joined before, disregarding vote, set AllowUnjoined to true to prevent this

This was thrown after
[00:18:02 INFO]: Void Realms »  has voted for the server on Vote Site 8!
[00:18:02 WARN]: [VotingPlugin] Empty player name for vote

**Comment by BenCodez** [comment]
Can you send the full log on a vote?

**Comment by Skizzles** [comment]
That is the only stuff shown in console/logs, I can turn on more debug?

**Comment by BenCodez** [comment]
Are you using pluginmessaging in votifier or votingplugin?
https://github.com/BenCodez/VotingPlugin/wiki/Bungeecoord-Setups

**Comment by Skizzles** [comment]
Using votingplugin

**Comment by BenCodez** [comment]
So on a vote, send the log from bungee and then the spigot log from that vote. Might wanna enable debug on bungee votingplugin and set debuglevel to EXTRA on spigot. Should provide enough info to see the issue I hope.

**Comment by Skizzles** [comment]
Toggled both on, awaiting more details to give.

**Comment by Skizzles** [comment]
[04:06:44 INFO]: [VotingPlugin] ExtraDebug: Query Size: 8, usebatchupdates: true
[04:07:14 INFO]: [VotingPlugin] Debug: pluginmessaging vote received from Loihoan22 on MCSL
[04:07:14 INFO]: [VotingPlugin] Debug: Pluginmessaging vote for  on MCSL
[04:07:14 INFO]: Void Realms »  has voted for the server on Vote Site 7!
[04:07:14 WARN]: [VotingPlugin] Empty player name for vote
[04:08:05 INFO]: [VotingPlugin] Debug: pluginmessaging vote received from Loihoan22 on Minecraft-Server.net
[04:08:05 INFO]: [VotingPlugin] Debug: Pluginmessaging vote for  on Minecraft-Server.net
[04:08:05 INFO]: Void Realms »  has voted for the server on Vote Site 4!
[04:08:05 WARN]: [VotingPlugin] Empty player name for vote
[04:08:15 INFO]: [VotingPlugin] Debug: pluginmessaging vote received from Loihoan22 on TopG.org
[04:08:15 INFO]: [VotingPlugin] Debug: Pluginmessaging vote for  on TopG.org
[04:08:15 INFO]: Void Realms »  has voted for the server on Vote Site 5!
[04:08:15 WARN]: [VotingPlugin] Empty player name for vote
[04:08:15 INFO]: [VotingPlugin] Debug: Clearing cache
[04:08:15 INFO]: [VotingPlugin] Debug: Clearing cache basic
[04:08:15 INFO]: [VotingPlugin] Debug: Starting background task
[04:08:15 INFO]: [VotingPlugin] Debug: Finished loading player data in 0 seconds, 558 users
[04:08:15 INFO]: [VotingPlugin] Debug: Number of users to check top voter: 558
[04:08:15 INFO]: [VotingPlugin] Debug: AllTime TopVoter loaded
[04:08:15 INFO]: [VotingPlugin] Debug: Monthly TopVoter loaded
[04:08:15 INFO]: [VotingPlugin] Debug: Updated TopVoter
[04:08:15 INFO]: [VotingPlugin] Debug: Updated VoteToday
[04:08:15 INFO]: [VotingPlugin] Debug: Signs updated
[04:08:15 INFO]: [VotingPlugin] ExtraDebug: Checking offline vote site votes
[04:08:15 INFO]: [VotingPlugin] ExtraDebug: Checking offline vote site votes
[04:08:15 INFO]: [VotingPlugin] ExtraDebug: Checking offline vote site votes
[04:08:15 INFO]: [VotingPlugin] ExtraDebug: Checking offline vote site votes
[04:08:15 INFO]: [VotingPlugin] ExtraDebug: Checking offline vote site votes
[04:08:15 INFO]: [VotingPlugin] Debug: Background task finished in 0 seconds
[04:08:18 INFO]: [BuycraftX] Fetching all due players...
[04:08:18 INFO]: [BuycraftX] Fetched due players (0 found).
[04:08:32 INFO]: [VotingPlugin] Debug: pluginmessaging vote received from Loihoan22 on PlanetMinecraft.com
[04:08:32 INFO]: [VotingPlugin] Debug: Pluginmessaging vote for  on PlanetMinecraft.com
[04:08:32 INFO]: Void Realms »  has voted for the server on Vote Site 2!
[04:08:32 WARN]: [VotingPlugin] Empty player name for vote

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin/

This might solve it.

**Comment by Skizzles** [comment]
Still testing and waiting to see if this is fixed. Will update when I have more info.

**Comment by Skizzles** [comment]
Seems resolved.
