### ISSUE TITLE
Major/Minor Error

### ISSUE THREAD

**Issue by JumanjiCraft** [BenCodez/VotingPlugin#115]
I get a version error (unsupported). I'm using a recent spigot, 1.10.2. I don't understand what could be causing this. 

[07:25:22] [Server thread/ERROR]: Could not load 'plugins/VotingPlugin.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/Ben12345rocks/VotingPlugin/Main : Unsupported major.minor version 52.0
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-e0e1771-5e5cf84]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-e0e1771-5e5cf84]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-e0e1771-5e5cf84]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:297) [spigot.jar:git-Spigot-e0e1771-5e5cf84]
    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot.jar:git-Spigot-e0e1771-5e5cf84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot.jar:git-Spigot-e0e1771-5e5cf84]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_101]
Caused by: java.lang.UnsupportedClassVersionError: com/Ben12345rocks/VotingPlugin/Main : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_101]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:803) ~[?:1.7.0_101]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_101]
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_101]
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_101]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_101]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_101]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_101]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_101]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-e0e1771-5e5cf84]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-e0e1771-5e5cf84]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_101]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_101]
    at java.lang.Class.forName0(Native Method) ~[?:1.7.0_101]
    at java.lang.Class.forName(Class.java:278) ~[?:1.7.0_101]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-e0e1771-5e5cf84]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-e0e1771-5e5cf84]
    ... 6 more

**Comment by BenCodez** [comment]
You need Java 8.

**Comment by JumanjiCraft** [comment]
thanks!
