### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#1160]
**Versions**
VotingPlugin 6.3.2
Purpur (paper fork) 1.16.5

**Describe the bug**
```
[12:25:10] [Craft Scheduler Thread - 335 - VotingPlugin/WARN]: [VotingPlugin] Plugin VotingPlugin v6.3.2 generated an exception while executing task 7886
java.lang.NullPointerException: null
	at com.bencodez.votingplugin.advancedcore.api.rewards.RewardHandler$2.run(RewardHandler.java:480) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1151]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Purpur-1151]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Purpur-1151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**To Reproduce**
Not sure how this can be reproduced. This happened in the hub server where nothing special happens. There are no rewards there in this server. Not sure what the RewardHandler has to do with this.
This happens with only a couple of seemly unrelated players.

**Expected behavior**
No error

**Screenshots/Configs**

**Additional context**

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin/ this should silence it. you can set debuglevel to EXTRA and send the log, would tell me where the problem is exactly

**Comment by x1p** [comment]
Installed. I assume you only need to be notified if the NPE happens again. This might take a while because I have only 2 NPE's after 14 hours,

**Comment by BenCodez** [comment]
it should go away with that, let me know if it comes back

**Comment by x1p** [comment]
Without knowing when it happens and how it shows, I'm only able to give you the logs it gives atm.

**Comment by BenCodez** [comment]
Yeah, I'm not worried about it though

**Comment by x1p** [comment]
Log.txt

**Comment by BenCodez** [comment]
You should see a Reward == null message if the error would pop up.

**Comment by x1p** [comment]
I think I have one. Line 755
Log.txt

**Comment by BenCodez** [comment]
What do you have for AllSites reward?

**Comment by x1p** [comment]
SpecialRewards.yml
```yaml
# All vote rewards
# Reward for voting on all sites in one day
AllSites: []
  #Messages:
    #Player: '&aYou voted on all sites in 1 day!'
```
Until today I used [square brackets] but I think `{}` would be better

**Comment by BenCodez** [comment]
Ah, that might be it. Shouldn't cause any problems though, I'll add a note to test that though.

**Comment by x1p** [comment]
After I implemented the advices given in commit https://github.com/BenCodez/VotingPlugin/commit/0fbbaaee5d1102e2e41a84d803207fd06f2253ad there were no more NPE's
