### ISSUE TITLE
which version for 1.7.10

### ISSUE THREAD

**Issue by brobon** [BenCodez/VotingPlugin#130]
Hey,
I need a compatible version for 1.7.10.
same for core

THX

**Comment by BenCodez** [comment]
Just use the latest version of both.

**Comment by brobon** [comment]
`[18:12:12 WARN]: Exception in thread "Craft Scheduler Thread - 27"
[18:12:12 WARN]: org.apache.commons.lang.UnhandledException: Plugin VotingPlugin v4.3.4 generated an exception while executing task 30
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: com/Ben12345rocks/VotingPlugin/Objects/User
        at com.Ben12345rocks.VotingPlugin.VoteReminding.VoteReminding$1.run(VoteReminding.java:92)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
Caused by: java.lang.ClassNotFoundException: Failed to remap class com.Ben12345rocks.VotingPlugin.Objects.User
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:534)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:455)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 6 more
Caused by: java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
        at org.objectweb.asm.MethodVisitor.visitMethodInsn(Unknown Source)
        at org.objectweb.asm.ClassReader.a(Unknown Source)
        at org.objectweb.asm.ClassReader.b(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:246)
        at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:232)
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:499)
        ... 10 more

`

**Comment by BenCodez** [comment]
@brobon  Did you try to use specialsource?

**Comment by brobon** [comment]
emm... specialsource?

**Comment by BenCodez** [comment]
@brobon Try redownloading the jars.

**Comment by BenCodez** [comment]
@brobon Also make sure your server is running on spigot, not craftbukkit.

**Comment by brobon** [comment]
restarting the server.
I run the server with Thermos. Spigot is included

**Comment by brobon** [comment]
`org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.57]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.57]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.57]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.57]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2069) [nh.class:?]
        at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32) [ix.class:?]
        at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10) [ix.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoClassDefFoundError: com/Ben12345rocks/VotingPlugin/Objects/User
        at com.Ben12345rocks.VotingPlugin.Commands.Executers.CommandAdminVote$6.onClick(CommandAdminVote.java:299) ~[?:?]
        at com.Ben12345rocks.AdvancedCore.Util.Inventory.BInventory.onInventoryClick(BInventory.java:221) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.57]
        ... 13 more
Caused by: java.lang.ClassNotFoundException: Failed to remap class com.Ben12345rocks.VotingPlugin.Objects.User
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:534) ~[PluginClassLoader.class:1.7.10-1614.57]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:455) ~[PluginClassLoader.class:1.7.10-1614.57]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1614.57]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
        at com.Ben12345rocks.VotingPlugin.Commands.Executers.CommandAdminVote$6.onClick(CommandAdminVote.java:299) ~[?:?]
        at com.Ben12345rocks.AdvancedCore.Util.Inventory.BInventory.onInventoryClick(BInventory.java:221) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.57]
        ... 13 more
Caused by: java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
        at org.objectweb.asm.MethodVisitor.visitMethodInsn(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
        at org.objectweb.asm.ClassReader.a(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
        at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
        at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
        at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
        at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:246) ~[JarRemapper.class:?]
        at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:232) ~[JarRemapper.class:?]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:499) ~[PluginClassLoader.class:1.7.10-1614.57]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:455) ~[PluginClassLoader.class:1.7.10-1614.57]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1614.57]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
        at com.Ben12345rocks.VotingPlugin.Commands.Executers.CommandAdminVote$6.onClick(CommandAdminVote.java:299) ~[?:?]
        at com.Ben12345rocks.AdvancedCore.Util.Inventory.BInventory.onInventoryClick(BInventory.java:221) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.57]
        ... 13 more
`

**# tested the gui ingame**

**Comment by BenCodez** [comment]
@brobon Try running your server on spigot (not something with spigot included), see if that fixes it.

**Comment by brobon** [comment]
but Thermos is based on Spigot. I need Thermos tu run modpacks

**Comment by BenCodez** [comment]
@brobon Oh, well Thermos appears to not have everything spigot has, which is why you are getting those errors. Sorry, but there isn't much I can do.

**Comment by brobon** [comment]
ok
Thy for your time :)
