### ISSUE TITLE
Error opening Anvil GUI

### ISSUE THREAD

**Issue by Eufranio** [BenCodez/VotingPlugin#138]
I'm running Thermos, build 58 on a 1.7.10 server, and the Anvil GUI's won't show, with the error:

```
[23:51:06 WARN]: java.lang.NullPointerException
[23:51:06 WARN]:        at com.Ben12345rocks.AdvancedCore.Util.AnvilInventory.AInventory.open(AInventory.java:358)
[23:51:06 WARN]:        at com.Ben12345rocks.AdvancedCore.Util.ValueRequest.Requesters.StringRequester.request(StringRequester.java:143)
[23:51:06 WARN]:        at com.Ben12345rocks.AdvancedCore.Util.ValueRequest.ValueRequest.requestString(ValueRequest.java:54)
[23:51:06 WARN]:        at com.Ben12345rocks.AdvancedCore.Commands.Commands$3.onClick(Commands.java:128)
[23:51:06 WARN]:        at com.Ben12345rocks.AdvancedCore.Util.Inventory.BInventory.onInventoryClick(BInventory.java:331)
[23:51:06 WARN]:        at sun.reflect.GeneratedMethodAccessor545.invoke(Unknown Source)
[23:51:06 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:51:06 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[23:51:06 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334)
[23:51:06 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[23:51:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507)
[23:51:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492)
[23:51:06 WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2069)
[23:51:06 WARN]:        at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32)
[23:51:06 WARN]:        at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10)
[23:51:06 WARN]:        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
[23:51:06 WARN]:        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181)
[23:51:06 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023)
[23:51:06 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[23:51:06 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
[23:51:06 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
[23:51:06 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

I have ASM5 installed.

**Comment by BenCodez** [comment]
Don't think it fully works on 1.7.10.

**Comment by Eufranio** [comment]
Only the anvil GUI won't work... Could you fix? VotingPlugin is really a amazing plugin =/

**Comment by BenCodez** [comment]
It uses nms, I'll see What I can do. Not sure if it's even possible in 1.7.

**Comment by BenCodez** [comment]
@Eufranio So I have taken a look at it and it appears possible but requires a lot of work due to the changes from 1.7 to 1.8, so I may or may not add support for it, since 1.7.10 is a really old version.

**Comment by Eufranio** [comment]
You could just add a option to type the values in the chat, instead a anvil GUI.

**Comment by BenCodez** [comment]
@Eufranio Already can be done. Use /acore setrequestmethod (method) hit tab to see a list.

**Comment by Eufranio** [comment]
Thanks, you may need to update your wiki :P

**Comment by BenCodez** [comment]
@Eufranio Exactly where? :)

**Comment by Eufranio** [comment]
That command isn't in any wiki, you could add it in AdvancedCore or VotingPlugin wiki

**Comment by BenCodez** [comment]
@Eufranio Its listed in the plugin page of AdvancedCore.

**Comment by BenCodez** [comment]
@Eufranio Gonna close this as I may or may not add this, and that this should really be in AdvancedCore.

**Comment by BenCodez** [comment]
@Eufranio Just fyi, I attempted to added 1.7.10 support. Not sure if it works, since I don't have a 1.7.10 server and don't feel like putting one up.

**Comment by Eufranio** [comment]
```
[17:11:15 INFO]: [ERROR] This plugin is not compatible with this server version (v1_7_R4).
[17:11:15 INFO]: [ERROR] Could not send chat packet!
```
rip

**Comment by BenCodez** [comment]
Hmm, didn't think about that. It should still work, message might not send though.

**Comment by Eufranio** [comment]
The wiki is outdated, and I can't even see the help commands 😦

**Comment by BenCodez** [comment]
Some of that stuff won't work. Thats what happens when your 4 versions
behind. The wiki page is updated.
