### ISSUE TITLE
Random error when receiving votes

### ISSUE THREAD

**Issue by Eufranio** [BenCodez/VotingPlugin#161]
Sometimes, an error shows in console when receiving a vote. 
```
[10:21:15 WARN]: Exception in thread "Craft Scheduler Thread - 103"
[10:21:15 WARN]: org.apache.commons.lang.UnhandledException: Plugin VotingPlugin v5.1.5 generated an exception while executing task 5760
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException
```
Running VotingPlugin 5.2.5 on a Thermos 1.7.10 server build 58 and Forge 1614

**Comment by BenCodez** [comment]
Your running v5.1.5,and I need the full error

**Comment by Eufranio** [comment]
lol what? 
I will update (again, rip) and see if it still happening. The full error won't show up in console, that's all

**Comment by BenCodez** [comment]
Look in the log file
