### ISSUE TITLE
Load the database at runtime instead on startup

### ISSUE THREAD

**Issue by Eufranio** [BenCodez/VotingPlugin#173]
When I started using VotingPlugin, the server gradually started taking more and more time to start, due to the plugin loading. I suggest that you do (if you don't yet) your datastore logic after the server starts, at runtime, and Async if possible, so it wouldn't cause lag to the server thread.

**Comment by BenCodez** [comment]
It is async. There is no lag on server thread, could be something else. Loading it at runtime would cause problems the road. I just came up if an idea so I wouldn't have to preload the table. Just preload it when the player joins, which would be slightly more efficient. Might make that what happens when preload is false. No time today though, busy with school.

**Comment by Eufranio** [comment]
The plugin will not start while not load all the stuff, so if you have a lot of players, votes or data (like I have), it will take a good time to start, and the server will wait UNTIL the plugin finishes loading to pass to the next plugin, and etc, causing a quite slow server starting time.

**Comment by BenCodez** [comment]
Will look into that tomorrow, got too much school todo today.

**Comment by BenCodez** [comment]
How does this help:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Eufranio** [comment]
Will test tomorrow when I get some time.

**Comment by BenCodez** [comment]
Sounds good, make sure to also test with preload table off.

**Comment by BenCodez** [comment]
Did some upgrades. Everything is now cached. Should fix your problem and such.
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Eufranio** [comment]
Testing it right now. Startup was quite faster now, and no TPS problems. Can I know when the MySQL requests are made?

**Comment by Eufranio** [comment]
Of course, it was faster because the plugin didn't even loaded :P
```
[19:52:20] [Server thread/INFO] [com.Ben12345rocks.VotingPlugin.Main/]: [VotingPlugin] Enabling VotingPlugin v5.5.1
[19:52:20] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling VotingPlugin v5.5.1 (Is it up to date?)
java.lang.NoSuchMethodError: guava10.com.google.common.cache.CacheBuilder.maximumSize(J)Lguava10/com/google/common/cache/CacheBuilder;
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.<init>(MySQL.java:31) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Main$32.run(Main.java:670) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Thread.Thread$ReadThread.run(Thread.java:26) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Thread.Thread.run(Thread.java:79) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Main.updateAdvancedCoreHook(Main.java:662) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Main.onEnable(Main.java:486) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.58]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.58]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111-internal]
```

**Comment by BenCodez** [comment]
Why must thermos be so difficult. Every server has that package...

**Comment by Eufranio** [comment]
Every server since 1.8 at least. That's why some plugins make `legacy` versions =/

**Comment by BenCodez** [comment]
You know of anyway to manually add that other than me compiling it in the jar?

**Comment by Eufranio** [comment]
Nope :X

**Comment by BenCodez** [comment]
Another plugin with it in? :) Its like 3 mb to have that in the jar

**Comment by Eufranio** [comment]
AuthMe, LuckPerms...

**Comment by BenCodez** [comment]
Looks like an older version?
java.lang.NoSuchMethodError

**Comment by Eufranio** [comment]
idk.

**Comment by BenCodez** [comment]
This will probably do it:
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

Due note that your are using 1.7 (which is really old) and thermos (no longer maintained) and I intend on dropping support for craftbukkit (might change my mind, if possible) in order to support 1.12, when that comes out, since thermos uses craftbukkit, it may not fully work. Just a heads up.

**Comment by Eufranio** [comment]
So I'm better switching my vote plugin?

**Comment by BenCodez** [comment]
Your better off updating. I might make an effort to make it work.

**Comment by BenCodez** [comment]
Should work right now though

**Comment by Eufranio** [comment]
Will test tomorrow.

**Comment by BenCodez** [comment]
Sounds good, can you check the other issues and make sure those are solved? I'm thinking of releasing a version on Sunday.

**Comment by Eufranio** [comment]
Didn't load:
```
[17:29:12] [Server thread/ERROR]: Error occurred while enabling VotingPlugin v5.5.1 (Is it up to date?)
java.lang.NoSuchMethodError: guava10.com.google.common.cache.CacheBuilder.maximumSize(J)Lguava10/com/google/common/cache/CacheBuilder;
    at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Misc.CompatibleCacheBuilder.maximumSize(CompatibleCacheBuilder.java:154) ~[?:?]
    at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.<init>(MySQL.java:31) ~[?:?]
    at com.Ben12345rocks.VotingPlugin.Main$32.run(Main.java:670) ~[?:?]
    at com.Ben12345rocks.VotingPlugin.AdvancedCore.Thread.Thread$ReadThread.run(Thread.java:26) ~[?:?]
    at com.Ben12345rocks.VotingPlugin.AdvancedCore.Thread.Thread.run(Thread.java:79) ~[?:?]
    at com.Ben12345rocks.VotingPlugin.Main.updateAdvancedCoreHook(Main.java:662) ~[?:?]
    at com.Ben12345rocks.VotingPlugin.Main.onEnable(Main.java:486) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.58]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.58]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.58]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.58]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.58]
    at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111-internal]
```

**Comment by BenCodez** [comment]
Will look at it later

**Comment by BenCodez** [comment]
This help?
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by Eufranio** [comment]
This fixes this issue.

**Comment by BenCodez** [comment]
@Eufranio Thought I let you know I found a way to keep support for craftbukkit (atleast for 1.11 and below) which means you shouldn't have to worry about switching plugins :)
