### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by ghost** [BenCodez/VotingPlugin#196]
Hey. I get this error from time to time, what's wrong?

```
[13:08:23] [Server thread/INFO]: [VotingPlugin] Recieved a vote from 'MinecraftForum.net' by player 'minecraftforum'!
[13:08:23] [Craft Scheduler Thread - 98/WARN]: [VotingPlugin] Player minecraftforum has not joined before, disregarding vote, set AllowUnjoined to true to prevent this
[13:08:28] [Thread-26/WARN]: [Votifier] Unable to decrypt vote record. Make sure that that your public key
[13:08:28] [Thread-26/WARN]: [Votifier] matches the one you gave the server list.
javax.crypto.BadPaddingException: Decryption error
	at sun.security.rsa.RSAPadding.unpadV15(RSAPadding.java:380) ~[?:1.8.0_131]
	at sun.security.rsa.RSAPadding.unpad(RSAPadding.java:291) ~[?:1.8.0_131]
	at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:363) ~[sunjce_provider.jar:1.8.0_112]
	at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389) ~[sunjce_provider.jar:1.8.0_112]
	at javax.crypto.Cipher.doFinal(Cipher.java:2165) ~[?:1.8.0_121]
	at com.vexsoftware.votifier.crypto.RSA.decrypt(RSA.java:65) ~[votifier-1.9.jar:?]
	at com.vexsoftware.votifier.net.VoteReceiver.run(VoteReceiver.java:130) [votifier-1.9.jar:?]
```

**Comment by BenCodez** [comment]
Looks like your public key doesn't match. Not directly an issue with my plugin.
