### ISSUE TITLE
Servers rewards

### ISSUE THREAD

**Issue by Zed9K** [BenCodez/VotingPlugin#258]
Hello,

so i have a bungeecord server, i have nuvotifier and your VotingPlugin
and i setup everything,

now when a player vote , the first server he get on, he receive his reward in it
but when he go to another server, he don't get a reward

while i setup the rewards and everything in all the servers

Like, if you are in Factions, and you voted, you will get the money/items in Factions
but when you go to Prison, it won't say that you have voted 

What i did wrong ?

Ill list nuvotifier/VotingPlugin config files 
just in case they are neeeded

[GitHub.zip](https://github.com/Ben12345rocks/VotingPlugin/files/1273288/GitHub.zip)

**Comment by BenCodez** [comment]
Are you forwarding the votes?

**Comment by Zed9K** [comment]
How to make sure ?

**Comment by BenCodez** [comment]
Look in the nuvotifier config?

**Comment by Zed9K** [comment]
Bungeecord's ?

**Comment by BenCodez** [comment]
Whichever server gets the vote.

**Comment by Zed9K** [comment]
i have include all the Config files In The ( GitHub.Zip )

**Comment by BenCodez** [comment]
I don't know nuvotifer that well, plus I shouldn't have to look through the configs.

I can tell you right now its a forwarding issue.

**Comment by Zed9K** [comment]
forwarding:
  method: pluginMessaging 
  pluginMessaging:
    channel: NuVotifier


^ all the Servers ( except the Bungeecord like this ) ^

**Comment by BenCodez** [comment]
Use the proxy method on bungeecoord, I think thats the one.

**Comment by Zed9K** [comment]
and Bungee's is
forwarding:
  method: proxy
  pluginMessaging:
    channel: NuVotifier

**Comment by BenCodez** [comment]
Worst case just use a seperate plugin to forward the votes, no idea how nuvotifier configs work, never used it.

**Comment by Zed9K** [comment]
i can add SendVote plugin with nuvotifier ?

**Comment by BenCodez** [comment]
Yes. Just not in bungeecord.

**Comment by Zed9K** [comment]
a question, some of the vote links don't give rewards
Like, when you vote, it won't give anything 
Like no one have voted on them

**Comment by BenCodez** [comment]
Check your service site in that case. Should be something console.

**Comment by Zed9K** [comment]
https://hastebin.com/selaqemefu.bash

**Comment by Zed9K** [comment]
Thats my VoteSites.yml
for Prison

can you check if i did anything wrong ?

**Comment by Zed9K** [comment]
Can you give me a link for SendVote ?

there is alot of plugins have this name
can you send me the best one of them link ?

**Comment by BenCodez** [comment]
Looks okay, only thing is like what I said about the service sites, I can't see if those are correct. Vote on the links and they will show the service site in console, case sensitive as well.

**Comment by BenCodez** [comment]
You can use this:
https://www.spigotmc.org/resources/voteforwarder.30613/

It's also my plugin.

**Comment by Zed9K** [comment]
Where should i download it on ?

all the servers ?
or only Bungeecord ?
Or ?

**Comment by BenCodez** [comment]
On a server that gets the votes.

**Comment by Zed9K** [comment]
and the list will be the other servers that i want them to get the vote ?

Like
if i want the vote to be only on Prison and Factions

Should i put the plugin only on them 
and list only those 2 Servers in their config ?

**Comment by BenCodez** [comment]
Pick on server that the voting websites are linked to.

On that server put all the servers votifier information on their.

Done.

**Comment by Zed9K** [comment]
![image](https://user-images.githubusercontent.com/31599865/30007301-6104f912-9114-11e7-86f0-111143089c89.png)

**Comment by Zed9K** [comment]
[01:01:33 ERROR]: Could not pass event VotifierEvent to VoteForwarder v1.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at com.vexsoftware.votifier.NuVotifierBukkit$3.run(NuVotifierBukkit.java:350) [nuvotifier-universal-2.3.5.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoClassDefFoundError: com/vexsoftware/votifier/crypto/RSA
        at com.Ben12345rocks.VoteForwarder.VoteForward.sendBungeeVoteServer(VoteForward.java:120) ~[?:?]
        at com.Ben12345rocks.VoteForwarder.VoteForward.sendVote(VoteForward.java:152) ~[?:?]
        at com.Ben12345rocks.VoteForwarder.VotiferEvent.onVotiferEvent(VotiferEvent.java:52) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
        ... 11 more

**Comment by BenCodez** [comment]
Guess you'll need the normal votifier.

**Comment by Zed9K** [comment]
Okay, but it will work well on Bungeecord ?

**Comment by BenCodez** [comment]
You can't use voteforwarder on bungeecoord.

**Comment by Zed9K** [comment]
Should i replace nuvotifier  with votifier on all the servers ? even Bungeecord ?
and keep the settings the same ? or ?

or ?

**Comment by BenCodez** [comment]
1. You won't need votifier on bungeecord
2. It won't really matter. Just the server with voteforwarder.

**Comment by Zed9K** [comment]
So 
voteforwarder + votifier  + VotingPlugin 

only on the servers i want the votes to be sent to ?

**Comment by BenCodez** [comment]
....

Sever 1 (The one configured to get votes from a website) has voteforwarder (configured to send to server 2....n) + votifier + votingplugin

Server 2.....n votifier + votingplugin.

**Comment by BenCodez** [comment]
Any update on this?

**Comment by Zed9K** [comment]
yea sorry i forgot to close it
everything is working well

But some players say that when they vote on Factions 
they don't get the vote on prison

**not all the time**
when you take time to go to Prison after voting on factions

**Comment by BenCodez** [comment]
It should give it after a relog I'm assuming.

**Comment by Zed9K** [comment]
Nope, they don't get it all sometimes. :cry:

**Comment by BenCodez** [comment]
Running the latest version?

**Comment by Zed9K** [comment]
Yes, im Running 1.1

**Comment by BenCodez** [comment]
1.1? Latest version is 5.10.1

**Comment by Zed9K** [comment]
i meant the VoteForwarder Ver is 1.1
The VotingPlugin Ver is 5.10.1

**Comment by BenCodez** [comment]
Any errors? Console logs? Turn debug on in VotingPlugin and see what happens.

**Comment by Zed9K** [comment]
[Log.txt](https://github.com/Ben12345rocks/VotingPlugin/files/1341630/Log.txt)
Thats the Logs for Voting Plugin ( with Extra Debug )

**Comment by BenCodez** [comment]
Everything looks fine. 

What problem are you still having?

**Comment by Zed9K** [comment]
im gonna check and let you know if it still working ( Since i updated VoteForwarder today )

**Comment by BenCodez** [comment]
Any update?
