### ISSUE TITLE
Some Weird Error

### ISSUE THREAD

**Issue by Zed9K** [BenCodez/VotingPlugin#301]
i keep getting this error on my console 
[17:17:37 INFO]: Reloading VotingPlugin...
[17:17:37 INFO]: HikariPool-2 - Starting...
[17:17:37 INFO]: HikariPool-2 - Start completed.
[17:17:39 WARN]: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 20000ms.
[17:17:39 WARN]:        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:591)
[17:17:39 WARN]:        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:194)
[17:17:39 WARN]:        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146)
[17:17:39 WARN]:        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
[17:17:39 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.api.ConnectionManager.getConnection(ConnectionManager.java:76)
[17:17:39 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.api.queries.Query.<init>(Query.java:20)
[17:17:39 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.getExactQuery(MySQL.java:212)
[17:17:39 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.loadPlayer(MySQL.java:316)
[17:17:39 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.getExact(MySQL.java:202)
[17:17:39 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.UserData.getMySqlRow(UserData.java:104)
[17:17:39 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.UserData.getString(UserData.java:129)
[17:17:39 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.UserData.getStringList(UserData.java:161)
[17:17:39 WARN]:        at com.Ben12345rocks.VotingPlugin.Objects.User.getLastVotes(User.java:310)
[17:17:39 WARN]:        at com.Ben12345rocks.VotingPlugin.Objects.User.getTime(User.java:384)
[17:17:39 WARN]:        at com.Ben12345rocks.VotingPlugin.Objects.User.canVoteSite(User.java:188)
[17:17:39 WARN]:        at com.Ben12345rocks.VotingPlugin.Objects.User.canVoteAll(User.java:170)
[17:17:39 WARN]:        at com.Ben12345rocks.VotingPlugin.VoteReminding.VoteReminding.checkRemind(VoteReminding.java:61)
[17:17:39 WARN]:        at com.Ben12345rocks.VotingPlugin.VoteReminding.VoteReminding$1.run(VoteReminding.java:93)
[17:17:39 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[17:17:39 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[17:17:39 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[17:17:39 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[17:17:39 WARN]:        at java.lang.Thread.run(Thread.java:748)
[17:17:39 WARN]: [VotingPlugin] Plugin VotingPlugin v5.10.5 generated an exception while executing task 105
java.lang.NullPointerException: null

**Comment by BenCodez** [comment]
Must be having an issue with the connection. Mysql is working fine.

**Comment by Zed9K** [comment]
Ben, can you tell me how to know which plugin is the cause of this ?
[17:21:32 WARN]: org.sqlite.SQLiteException: [SQLITE_CORRUPT]  The database disk image is malformed (database disk image is malformed)
[17:21:32 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:909)
[17:21:32 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:921)
[17:21:32 WARN]:        at org.sqlite.core.DB.execute(DB.java:825)
[17:21:32 WARN]:        at org.sqlite.core.DB.executeUpdate(DB.java:863)
[17:21:32 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:99)
[17:21:32 WARN]:        at net.coreprotect.database.Database.insertEntity(Database.java:274)
[17:21:32 WARN]:        at net.coreprotect.database.Logger.log_entity_kill(Logger.java:327)
[17:21:32 WARN]:        at net.coreprotect.consumer.Process.processEntityKill(Process.java:283)
[17:21:32 WARN]:        at net.coreprotect.consumer.Process.processConsumer(Process.java:132)
[17:21:32 WARN]:        at net.coreprotect.consumer.Consumer.run(Consumer.java:105)
[17:21:32 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by Zed9K** [comment]
and VotingPlugin keep spamming this 
[00:04:56] [Timer-4/WARN]: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 20000ms.
[00:04:56] [Timer-4/WARN]: 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:591)
[00:04:56] [Timer-4/WARN]: 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:194)
[00:04:56] [Timer-4/WARN]: 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146)
[00:04:56] [Timer-4/WARN]: 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
[00:04:56] [Timer-4/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.api.ConnectionManager.getConnection(ConnectionManager.java:76)
[00:04:56] [Timer-4/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.api.queries.Query.<init>(Query.java:20)
[00:04:56] [Timer-4/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.getExactQuery(MySQL.java:212)
[00:04:56] [Timer-4/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.loadPlayer(MySQL.java:316)
[00:04:56] [Timer-4/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.getExact(MySQL.java:202)
[00:04:56] [Timer-4/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.UserData.getMySqlRow(UserData.java:104)
[00:04:56] [Timer-4/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.UserData.getString(UserData.java:129)
[00:04:56] [Timer-4/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Misc.PlayerUtils.getPlayerName(PlayerUtils.java:90)
[00:04:56] [Timer-4/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.User.<init>(User.java:109)
[00:04:56] [Timer-4/WARN]: 	at com.Ben12345rocks.VotingPlugin.Objects.User.<init>(User.java:67)
[00:04:56] [Timer-4/WARN]: 	at com.Ben12345rocks.VotingPlugin.UserManager.UserManager.getVotingPluginUser(UserManager.java:50)
[00:04:56] [Timer-4/WARN]: 	at com.Ben12345rocks.VotingPlugin.TopVoter.TopVoterHandler.onDayChange(TopVoterHandler.java:95)
[00:04:56] [Timer-4/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:04:56] [Timer-4/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:04:56] [Timer-4/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:04:56] [Timer-4/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[00:04:56] [Timer-4/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[00:04:56] [Timer-4/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[00:04:56] [Timer-4/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[00:04:56] [Timer-4/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:481)
[00:04:56] [Timer-4/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.TimeChecker.TimeChecker.forceChanged(TimeChecker.java:49)
[00:04:56] [Timer-4/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.TimeChecker.TimeChecker.update(TimeChecker.java:137)
[00:04:56] [Timer-4/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.update(AdvancedCoreHook.java:948)
[00:04:56] [Timer-4/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook$4.run(AdvancedCoreHook.java:462)
[00:04:56] [Timer-4/WARN]: 	at java.util.TimerThread.mainLoop(Timer.java:555)
[00:04:56] [Timer-4/WARN]: 	at java.util.TimerThread.run(Timer.java:505)
[00:04:56] [Timer-4/ERROR]: Could not pass event DayChangeEvent to VotingPlugin v5.10.5
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-da42974-8f47214]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-da42974-8f47214]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-da42974-8f47214]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:481) [spigot.jar:git-Spigot-da42974-8f47214]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.TimeChecker.TimeChecker.forceChanged(TimeChecker.java:49) [VotingPlugin-5.10.5.jar:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.TimeChecker.TimeChecker.update(TimeChecker.java:137) [VotingPlugin-5.10.5.jar:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.update(AdvancedCoreHook.java:948) [VotingPlugin-5.10.5.jar:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook$4.run(AdvancedCoreHook.java:462) [VotingPlugin-5.10.5.jar:?]
	at java.util.TimerThread.mainLoop(Timer.java:555) [?:1.8.0_131]
	at java.util.TimerThread.run(Timer.java:505) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
[00:04:56] [Craft Scheduler Thread - 9077/WARN]: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 20000ms.
[00:04:56] [Craft Scheduler Thread - 9077/WARN]: 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:591)
[00:04:56] [Craft Scheduler Thread - 9077/WARN]: 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:194)
[00:04:56] [Craft Scheduler Thread - 9077/WARN]: 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146)
[00:04:56] [Craft Scheduler Thread - 9077/WARN]: 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
[00:04:56] [Craft Scheduler Thread - 9077/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.api.ConnectionManager.getConnection(ConnectionManager.java:76)
[00:04:56] [Craft Scheduler Thread - 9077/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.api.queries.Query.<init>(Query.java:20)
[00:04:56] [Craft Scheduler Thread - 9077/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.getColumnsQueury(MySQL.java:181)
[00:04:56] [Craft Scheduler Thread - 9077/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.clearCacheBasic(MySQL.java:132)
[00:04:56] [Craft Scheduler Thread - 9077/WARN]: 	at com.Ben12345rocks.VotingPlugin.Main$37.run(Main.java:887)
[00:04:56] [Craft Scheduler Thread - 9077/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[00:04:56] [Craft Scheduler Thread - 9077/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[00:04:56] [Craft Scheduler Thread - 9077/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[00:04:56] [Craft Scheduler Thread - 9077/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[00:04:56] [Craft Scheduler Thread - 9077/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[00:04:56] [Craft Scheduler Thread - 9077/WARN]: [VotingPlugin] Plugin VotingPlugin v5.10.5 generated an exception while executing task 204623923
java.lang.NullPointerException: null
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.api.queries.Query.<init>(Query.java:21) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.getColumnsQueury(MySQL.java:181) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.clearCacheBasic(MySQL.java:132) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Main$37.run(Main.java:887) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-da42974-8f47214]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-da42974-8f47214]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by Zed9K** [comment]
https://hastebin.com/ojafoqegil.md

**Comment by BenCodez** [comment]
There is a problem with your mysql connection. Not really anything I can do.

**Comment by Zed9K** [comment]
Okay listen, i have something to talk about
i really can't find a fix for it

i have my own VPS, and i have my servers on it, and i have setup MySQL and phpmyadmin on it
but mysql have connections limit and i tried to change it from the phpmyadmin's site from my vps's ip you know that site for phpmyadmin but i got this problem ( https://imgur.com/B7x23Tv )
and i tried to do it from the console too, i use putty so i gone to the console and entered mysql by doing 
mysql -r -p
and wrote my password
Then i entered then did 
set global max_connections = 500;     
i did 500, since mine is on 214 and a lot of plugins uses Mysql
anyway when i did the command ( set global max_connections = 500; )
i got this ( https://imgur.com/WBRwp3h )
i use root user and i have access to every single file in my VPS even / 
or /etc ..etc

how im supposed to change the mysql max_connections limit :( ? please anything
i have been searching google for this all the time ....

**Comment by BenCodez** [comment]
Don't think you can do that. You could switch to SQLITE in the meantime. (There is a converter for to convert MySQL to SQLITE)

**Comment by Zed9K** [comment]
What is the diff between them ?

**Comment by BenCodez** [comment]
SQLITE is the same as mysql but is a file instead

**Comment by BenCodez** [comment]
Any update on this?
