### ISSUE TITLE
Invalid UUID String

### ISSUE THREAD

**Issue by AndrewB6** [BenCodez/VotingPlugin#333]
I get this error whenever votingplugin tries to do something other than show a help page. Any help would be appreciated. Thanks.

[Craft Scheduler Thread - 3278/WARN]: [VotingPlugin] Plugin VotingPlugin v5.12 generated an exception while executing task 1725684
java.lang.IllegalArgumentException: Invalid UUID string: 
	at java.util.UUID.fromString(UUID.java:194) ~[?:1.8.0_151]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Misc.PlayerUtils.getPlayerName(PlayerUtils.java:92) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.User.<init>(User.java:109) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserManager.getUser(UserManager.java:122) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserManager.userExist(UserManager.java:159) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Misc.PlayerUtils.getUUID(PlayerUtils.java:133) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.User.<init>(User.java:92) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Objects.User.<init>(User.java:57) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.UserManager.UserManager.getVotingPluginUser(UserManager.java:45) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.UserManager.UserManager.getVotingPluginUser(UserManager.java:40) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Events.PlayerJoinEvent$1.run(PlayerJoinEvent.java:55) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-bb614f8-595eaaa]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-bb614f8-595eaaa]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by BenCodez** [comment]
Thus fix it?
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by AndrewB6** [comment]
Yes, it works now. Thank you.

**Comment by AndrewB6** [comment]
Unforunately, it turns out my players cannot do /vote, but I can. They can however do any derivative of /vote. /v points and /v shop work fine. They just don't seem to have permission for /vote. I have given them VotingPlugin.Player and VotingPlugin.Commands.Vote.* but neither of them work.

**Comment by BenCodez** [comment]
This better?
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by ashleyekm** [comment]
I had this exact issue today with the console error. I took that above jar ^, hope thats ok. Seems everything works for me now.
