### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheTechnologyStudio** [BenCodez/VotingPlugin#356]
This error appeared in my console.

`[14:34:13] [Netty Server IO #0/ERROR]: [VotingPlugin] Unhandled exception occured in onPacketReceiving(PacketEvent) for VotingPlugin
com.comphenix.protocol.reflect.FieldAccessException: No field with type [Ljava.lang.String; exists in class PacketPlayInUpdateSign.
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:219) ~[ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:198) ~[ProtocolLib.jar:4.3.0]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sign.SignMenu$1.onPacketReceiving(SignMenu.java:83) ~[VotingPlugin.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:531) [ProtocolLib.jar:4.3.0]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched.jar:git-PaperSpigot-"4c7641d"]
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:263) [ProtocolLib.jar:4.3.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
[14:34:13] [Netty Server IO #0/ERROR]: Parameters: 
  net.minecraft.server.v1_8_R3.PacketPlayInUpdateSign@267601d2[
    a=BlockPosition{x=-14962, y=192, z=-14962}
    b={TextComponent{text='', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}},TextComponent{text='', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}},TextComponent{text='', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}},TextComponent{text='', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}}
  ]`

**Comment by BenCodez** [comment]
It's only because your running 1.8. Just ignore it.

**Comment by TheTechnologyStudio** [comment]
Not very professional. I dont want errors spamming my console. Please fix it.

**Comment by BenCodez** [comment]
Update your server then.

**Comment by TheTechnologyStudio** [comment]
Cant, Its factions. Also 90% of mc servers use 1.8.8. So please fix the error.

**Comment by BenCodez** [comment]
I've got this bug report like 100+ times and so far haven't fixed it. Also 90% of servers don't use 1.8. Demanding me to fix a bug that only happens because you use a 3 year old version will just make me not want to fix it.

**Comment by BenCodez** [comment]
I'm at the point to just drop support for 1.8 in general. Almost all the bugs I fix are just for 1.8.

**Comment by TheTechnologyStudio** [comment]
bstats.org and look at server versions. 50% use 1.8.8

**Comment by BenCodez** [comment]
More like 30% but you shouldn't be expecting support on using a 3 year old version. The more people tell me to fix errors in 1.8 the more I want to drop support.

**Comment by TheTechnologyStudio** [comment]
The reason so many people use 1.8 is because 1.9 update ruined so many systems to do with so many game modes. between the combat updates and other updates.

**Comment by BenCodez** [comment]
Just use a plugin to revert the changes, it's not that hard.

**Comment by TheTechnologyStudio** [comment]
theres no plugins to revert cannoning systems.

**Comment by BenCodez** [comment]
https://www.spigotmc.org/resources/1-8-pvp-for-1-9-1-10-and-1-11.19291/

You sure?

**Comment by TheTechnologyStudio** [comment]
thats pvp, not cannoning.

**Comment by BenCodez** [comment]
Never heard of cannoning. 

Anyway, I'm thinking I'm outright dropping support for 1.8. Getting pretty tired of it.

**Comment by TheTechnologyStudio** [comment]
then gl with ur plugin. you will lose like 50% or more of your plugin users.

**Comment by BenCodez** [comment]
It's better than fixing every single little issue. Only like 10% of my current users are 1.8, so whatever.
