### ISSUE TITLE
Command Dispatched Async: vote reward error

### ISSUE THREAD

**Issue by andris155** [BenCodez/VotingPlugin#363]
```
[10:05:40] [Server thread/INFO]: andris155 issued server command: /vote Reward
[10:05:41] [Craft Scheduler Thread - 390/ERROR]: Command Dispatched Async: vote reward TopG_org
[10:05:41] [Craft Scheduler Thread - 390/ERROR]: Please notify author of plugin causing this execution to fix this bug! see: http://bit.ly/1oSiM6C
java.lang.Throwable: null
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:659) [patched_1.12.2.jar:git-Paper-1331]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:354) [patched_1.12.2.jar:git-Paper-1331]
	at com.Ben12345rocks.VotingPlugin.Commands.GUI.PlayerGUIs$33.onClick(PlayerGUIs.java:648) [VotingPlugin.jar:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Inventory.BInventory$1.run(BInventory.java:412) [VotingPlugin.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.12.2.jar:git-Paper-1331]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1331]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1331]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by BenCodez** [comment]
Oh, will fix it later

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/31/changes

You can download a fix there.
