### ISSUE TITLE
MYSQL issue

### ISSUE THREAD

**Issue by Zoiter7** [BenCodez/VotingPlugin#401]
Hello, I have two servers connected to the same mysql database for sync the votes that player done.
It's works well but sometime I had this crashes in console. Any idea how to solve it?

``[16:20:29 WARN]: java.sql.SQLTransientConnectionException: HikariPool-0 - Connection is not available, request timed out after 20000ms.
[16:20:29 WARN]:        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:195)
[16:20:29 WARN]:        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
[16:20:29 WARN]:        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
[16:20:29 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.api.ConnectionManager.getConnection(ConnectionManager.java:80)
[16:20:29 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.api.queries.Query.<init>(Query.java:20)
[16:20:29 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.getRowsQuery(MySQL.java:359)
[16:20:29 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.getUuidsQuery(MySQL.java:385)
[16:20:29 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.getUuids(MySQL.java:376)
[16:20:29 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.update(MySQL.java:465)
[16:20:29 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.UserData.setString(UserData.java:246)
[16:20:29 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.User.updateName(User.java:980)
[16:20:29 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.User.setPlayerName(User.java:941)
[16:20:29 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.User.<init>(User.java:109)
[16:20:29 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserManager.getUser(UserManager.java:157)
[16:20:29 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Misc.PlayerUtils.getUUIDLookup(PlayerUtils.java:162)
[16:20:29 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Misc.PlayerUtils.getUUID(PlayerUtils.java:131)
[16:20:29 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.User.<init>(User.java:92)
[16:20:29 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserManager.getUser(UserManager.java:145)
[16:20:29 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserManager.getUser(UserManager.java:133)
[16:20:29 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Listeners.PlayerJoinEvent$1.run(PlayerJoinEvent.java:68)
[16:20:29 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[16:20:29 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[16:20:29 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[16:20:29 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[16:20:29 WARN]:        at java.lang.Thread.run(Thread.java:748)
[16:20:29 WARN]: Exception in thread "Craft Scheduler Thread - 42"
[16:20:29 WARN]: org.apache.commons.lang.UnhandledException: Plugin VotingPlugin v5.13.3 generated an exception while executing task 34619
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.api.queries.Query.<init>(Query.java:21)
        at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.getRowsQuery(MySQL.java:359)
        at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.getUuidsQuery(MySQL.java:385)
        at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.getUuids(MySQL.java:376)
        at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.update(MySQL.java:465)
        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.UserData.setString(UserData.java:246)
        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.User.updateName(User.java:980)
        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.User.setPlayerName(User.java:941)
        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.User.<init>(User.java:109)
        at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserManager.getUser(UserManager.java:157)
        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Misc.PlayerUtils.getUUIDLookup(PlayerUtils.java:162)
        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Misc.PlayerUtils.getUUID(PlayerUtils.java:131)
        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.User.<init>(User.java:92)
        at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserManager.getUser(UserManager.java:145)
        at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserManager.getUser(UserManager.java:133)
        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Listeners.PlayerJoinEvent$1.run(PlayerJoinEvent.java:68)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by BenCodez** [comment]
Are you on the latest version?

**Comment by Zoiter7** [comment]
Yes, I'm on the last stable version from Spigot page.

**Comment by BenCodez** [comment]
Does it still happen after a reload?

**Comment by Zoiter7** [comment]
Oh I saw the log now about this day and after reload the plugin the crash not presented any more.
And only the crash appears on the second server.

**Comment by BenCodez** [comment]
The crash? The plugin isn't crashing, it just can't connect to mysql

**Comment by Zoiter7** [comment]
Yes I know, I'm refer to the exception error in the console about the mysql.

**Comment by BenCodez** [comment]
Does it happen a lot?

**Comment by Zoiter7** [comment]
Ups, hello I'm sorry, I forgot to answer. 
After that day the exception doesn't appear any more. So everything is ok.
Thank you for your time and support
