### ISSUE TITLE
Mysql Error

### ISSUE THREAD

**Issue by rgomunita** [BenCodez/VotingPlugin#408]
this connect to the database for a moment...

```
[05:40:16] [Server thread/INFO]: [VotingPlugin] Enabling VotingPlugin v5.13.5
[05:40:16] [Server thread/WARN]: 20987 [Server thread] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...

[05:40:17] [Server thread/WARN]: 21528 [Server thread] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.

[05:40:17] [pool-27-thread-1/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-network' at line 1
[05:40:17] [pool-27-thread-1/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[05:40:17] [pool-27-thread-1/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[05:40:17] [pool-27-thread-1/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[05:40:17] [pool-27-thread-1/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[05:40:17] [pool-27-thread-1/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[05:40:17] [pool-27-thread-1/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[05:40:17] [pool-27-thread-1/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[05:40:17] [pool-27-thread-1/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[05:40:17] [pool-27-thread-1/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[05:40:17] [pool-27-thread-1/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[05:40:17] [pool-27-thread-1/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[05:40:17] [pool-27-thread-1/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
[05:40:17] [pool-27-thread-1/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[05:40:17] [pool-27-thread-1/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
[05:40:17] [pool-27-thread-1/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
[05:40:17] [pool-27-thread-1/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
[05:40:17] [pool-27-thread-1/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
[05:40:17] [pool-27-thread-1/WARN]: 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[05:40:17] [pool-27-thread-1/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[05:40:17] [pool-27-thread-1/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.api.queries.Query.executeUpdate(Query.java:163)
[05:40:17] [pool-27-thread-1/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.api.queries.Query$3.run(Query.java:199)
[05:40:17] [pool-27-thread-1/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[05:40:17] [pool-27-thread-1/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[05:40:17] [pool-27-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[05:40:17] [pool-27-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[05:40:17] [pool-27-thread-1/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[05:40:17] [Server thread/INFO]: [VotingPlugin] Enabled VotingPlugin 5.13.5
```

**Comment by BenCodez** [comment]
I have no idea, need more details.

**Comment by rgomunita** [comment]
I try to connect to a MariaDB database through MYSQL, the plugin manages the connection but sends that error, it is assumed that MariaDB and MYSQL are compatible ...

**Comment by BenCodez** [comment]
I have no idea

**Comment by BenCodez** [comment]
I guess you need the proper version of mariadb for the one that matches the mysql version (so no idea which one you need)

**Comment by rgomunita** [comment]
Server: Localhost via UNIX socket
Server type: MariaDB
Server connection: SSL is not being used Documentation
Server version: 10.1.34-MariaDB - Source distribution
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)

**Comment by BenCodez** [comment]
Are you on the latest version of the plugin? Full console log with debug enabled?

**Comment by rgomunita** [comment]
[18:02:27] [Server thread/INFO]: [VotingPlugin] Enabling VotingPlugin v5.13.6
[18:02:27] [Server thread/WARN]: 1423 [Server thread] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Starting...

[18:02:27] [Server thread/WARN]: 1468 [Server thread] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Start completed.

[18:02:27] [Server thread/INFO]: [VotingPlugin] Debug: Altering column uuid to VARCHAR(37)
[18:02:28] [Server thread/INFO]: [VotingPlugin] Debug: Clearing cache basic
[18:02:28] [Server thread/INFO]: [VotingPlugin] Debug: Using AdvancedCore '2.13.6' built on '2018-07-15 23:09'
[18:02:28] [Server thread/INFO]: [VotingPlugin] Debug: UseBatchUpdates: true
[18:02:28] [pool-71-thread-1/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-network' at line 1
[18:02:28] [pool-71-thread-1/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:02:28] [pool-71-thread-1/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[18:02:28] [pool-71-thread-1/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:02:28] [pool-71-thread-1/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[18:02:28] [pool-71-thread-1/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[18:02:28] [pool-71-thread-1/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[18:02:28] [pool-71-thread-1/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[18:02:28] [pool-71-thread-1/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[18:02:28] [pool-71-thread-1/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[18:02:28] [pool-71-thread-1/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[18:02:28] [pool-71-thread-1/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[18:02:28] [pool-71-thread-1/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
[18:02:28] [pool-71-thread-1/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[18:02:28] [pool-71-thread-1/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
[18:02:28] [pool-71-thread-1/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
[18:02:28] [pool-71-thread-1/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
[18:02:28] [pool-71-thread-1/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
[18:02:28] [pool-71-thread-1/WARN]: 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[18:02:28] [pool-71-thread-1/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[18:02:28] [pool-71-thread-1/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.api.queries.Query.executeUpdate(Query.java:163)
[18:02:28] [pool-71-thread-1/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.api.queries.Query$3.run(Query.java:199)
[18:02:28] [pool-71-thread-1/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:02:28] [pool-71-thread-1/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:02:28] [pool-71-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[18:02:28] [pool-71-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[18:02:28] [pool-71-thread-1/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[18:02:28] [Server thread/INFO]: [VotingPlugin] Debug: Failed to load command and tab completer for /voteToggleBroadcast
[18:02:28] [Server thread/INFO]: [VotingPlugin] Debug: Failed to load command and tab completer for /adminvoteDownloadJenkins: null
[18:02:28] [Server thread/INFO]: [VotingPlugin] Debug: Loaded Commands
[18:02:28] [Server thread/INFO]: [VotingPlugin] Debug: Loaded Events
[18:02:28] [Server thread/INFO]: [VotingPlugin] Debug: Loaded Metrics
[18:02:28] [Server thread/INFO]: [VotingPlugin] Debug: Altering column TopVoterIgnore to VARCHAR(5)
[18:02:28] [Server thread/INFO]: [VotingPlugin] Debug: Altering column CheckWorld to VARCHAR(5)
[18:02:28] [Server thread/INFO]: [VotingPlugin] Debug: Altering column Reminded to VARCHAR(5)
[18:02:28] [Server thread/INFO]: [VotingPlugin] Debug: Altering column DisableBroadcast to VARCHAR(5)
[18:02:28] [Server thread/INFO]: [VotingPlugin] Debug: Altering column DailyTotal to VARCHAR(10)
[18:02:28] [Server thread/INFO]: [VotingPlugin] Enabled VotingPlugin 5.13.6
[18:02:28] [Server thread/WARN]: [VotingPlugin] No vote has been recieved from minecraft-server-list.com, may be an invalid service site. Vote on the site and look in console for a service site, if you get nothing then there is an issue with votifier

**Comment by BenCodez** [comment]
Mysql works though?

**Comment by rgomunita** [comment]
I changed the name of  my database "server-network" to "server" and now it works perfect, I think the error is that it does not support special characters like name in the database (in my case it was "-")

**Comment by BenCodez** [comment]
That's good to know. Good that you found that.
