### ISSUE TITLE
An issue with /av gui command

### ISSUE THREAD

**Issue by Nelfis** [BenCodez/VotingPlugin#425]
[20:59:35 WARN]: Exception in thread "
[20:59:35 WARN]: Craft Scheduler Thread - 2
[20:59:35 WARN]: "
[20:59:35 WARN]: org.apache.commons.lang.UnhandledException: Plugin VotingPlugin v5.15 generated an exception while executing task 252
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchFieldError: PLAYER_HEAD
        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Commands.GUI.AdminGUI.openGUI(AdminGUI.java:95)
        at com.Ben12345rocks.VotingPlugin.Commands.CommandLoader$17.execute(CommandLoader.java:420)
        at com.Ben12345rocks.VotingPlugin.AdvancedCore.CommandAPI.CommandHandler$1.run(CommandHandler.java:387)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

I haven't changed anything in plugin's config!

**Comment by BenCodez** [comment]
That version doesn't work in 1.8, use 5.13.6 or lower.

**Comment by Nelfis** [comment]
Hello. I didn't find 5.13.6 version on GitHub. On dev builds I've found
only #122 builds.

**Comment by BenCodez** [comment]
Use spigot to get them.
