### ISSUE TITLE
TopVoter reward

### ISSUE THREAD

**Issue by Straikerinos** [BenCodez/VotingPlugin#441]
Need help if automatic reward (top voter 1) get reward i get this error .. i think this is error
Exception in thread "Timer-2" 
[07:30:18 WARN]: java.lang.NoClassDefFoundError: com/Ben12345rocks/VotingPlugin/Objects/User$1
[07:30:18 WARN]: at com.Ben12345rocks.VotingPlugin.Objects.User.getTotal(User.java:581)
[07:30:18 WARN]: at com.Ben12345rocks.VotingPlugin.TopVoter.TopVoterHandler.updateTopVoters(TopVoterHandler.java:624)
[07:30:18 WARN]: at com.Ben12345rocks.VotingPlugin.Main.update(Main.java:1008)
[07:30:18 WARN]: at com.Ben12345rocks.VotingPlugin.Main$1$1.run(Main.java:370)
[07:30:18 WARN]: at java.util.TimerThread.mainLoop(Timer.java:555)
[07:30:18 WARN]: at java.util.TimerThread.run(Timer.java:505)
[07:30:18 WARN]: Caused by: java.lang.ClassNotFoundException: com.Ben12345rocks.VotingPlugin.Objects.User$1
[07:30:18 WARN]: at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[07:30:18 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154)
[07:30:18 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
[07:30:18 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[07:30:18 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[07:30:18 WARN]: ... 6 more

**Comment by BenCodez** [comment]
Latest version?

**Comment by Straikerinos** [comment]
yes.. 5.16.1

**Comment by BenCodez** [comment]
It works fine for me. Redownload the jar?

**Comment by Straikerinos** [comment]
hm config?

**Comment by BenCodez** [comment]
I used the default config. Just redownload the jar. I think that will solve it.

**Comment by Straikerinos** [comment]
well i'll try otherwise thank you
