### ISSUE TITLE
av download error

### ISSUE THREAD

**Issue by LogGits** [BenCodez/VotingPlugin#446]
```
WARN 16/11/2018 00:18:11
00:18:11java.io.FileNotFoundException: https://api.spiget.org/v2/resources/15358/download
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
at java.net.URL.openStream(URL.java:1045)
at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Updater.UpdateDownloader.download(UpdateDownloader.java:53)
at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Updater.UpdateDownloader.download(UpdateDownloader.java:43)
at com.Ben12345rocks.VotingPlugin.AdvancedCore.Commands.CommandLoader$14.execute(CommandLoader.java:220)
at com.Ben12345rocks.VotingPlugin.AdvancedCore.CommandAPI.CommandHandler$1.run(CommandHandler.java:355)
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by BenCodez** [comment]
I'll look at this later.

**Comment by BenCodez** [comment]
It should be fixed whenever the next version is released, guess the files on a lifespan for downloading

**Comment by BenCodez** [comment]
Should fix itself in a hour or so
