### ISSUE TITLE
Error on latest update

### ISSUE THREAD

**Issue by lukeeexd** [BenCodez/VotingPlugin#450]
`[22:40:43 ERROR]: Could not load 'plugins/VotingPlugin.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[patched_1.13.2.jar:git-Paper-455]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136) ~[patched_1.13.2.jar:git-Paper-455]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:329) ~[patched_1.13.2.jar:git-Paper-455]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-455]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-455]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.util.zip.ZipException: zip file is empty
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_181]
        at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_181]
        at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_181]
        at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_181]
        at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[patched_1.13.2.jar:git-Paper-455]
        ... 5 more
`

**Comment by BenCodez** [comment]
Redownload the jar
