### ISSUE TITLE
Error placeholder

### ISSUE THREAD

**Issue by LogGits** [BenCodez/VotingPlugin#454]
I think a recent update broke the placeholders feature. I am using papi, votingplugin placeholders now give me errors (yes ik this says CMI):
```
WARN 22/11/2018 09:55:27
09:55:27[CMI]: Plugin CMI v8.1.0.0 generated an exception while executing task 561632
Console 22/11/2018 09:55:27
09:55:27java.lang.NoClassDefFoundError: com/Ben12345rocks/VotingPlugin/AdvancedCore/Util/Javascript/JavascriptEngine
at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Misc.StringUtils.replaceJavascript(StringUtils.java:208) ~[?:?]
at com.Ben12345rocks.VotingPlugin.Util.PlaceHolders.PlaceHolders.getPlaceHolder(PlaceHolders.java:65) ~[?:?]
at com.Ben12345rocks.VotingPlugin.PlaceHolderAPI.expansion.VotingPliuginExpansion.onRequest(VotingPliuginExpansion.java:85) ~[?:?]
at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:237) ~[?:?]
at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:377) ~[?:?]
at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:362) ~[?:?]
at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:320) ~[?:?]
at com.Zrips.CMI.Modules.TabList.TabListManager$3.run(TabListManager.java:378) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-456]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-456]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-456]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by BenCodez** [comment]
Also works fine for me. Redownload the jar?

**Comment by LogGits** [comment]
I tested with http://ben12345rocks.com/job/VotingPlugin/434/ but il give it another go

**Comment by BenCodez** [comment]
That should work, but I got no idea.

**Comment by LogGits** [comment]
Also noticed "VotingPliuginExpansion":
`at com.Ben12345rocks.VotingPlugin.PlaceHolderAPI.expansion.VotingPliuginExpansion.onRequest(VotingPliuginExpansion.java:85) ~[?:?]`

**Comment by BenCodez** [comment]
That doesn't matter. Does /papi parse work?

**Comment by LogGits** [comment]
just noticed 
```
10:28:56USERNAME issued server command: /av placeholders
ERROR 23/11/2018 10:28:56
10:28:56null
Console 23/11/2018 10:28:56
10:28:56org.bukkit.command.CommandException: Unhandled exception executing command 'av' in plugin VotingPlugin v5.16.2
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-456]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-456]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-456]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1798) ~[patched_1.13.2.jar:git-Paper-456]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1602) ~[patched_1.13.2.jar:git-Paper-456]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-456]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-456]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-456]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-456]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-456]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-456]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-456]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-456]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoClassDefFoundError: com/Ben12345rocks/VotingPlugin/AdvancedCore/CommandAPI/CommandHandler$1
at com.Ben12345rocks.VotingPlugin.AdvancedCore.CommandAPI.CommandHandler.runCommand(CommandHandler.java:371) ~[?:?]
at com.Ben12345rocks.VotingPlugin.Commands.Executers.CommandAdminVote.onCommand(CommandAdminVote.java:65) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-456]
... 15 more
Caused by: java.lang.ClassNotFoundException: com.Ben12345rocks.VotingPlugin.AdvancedCore.CommandAPI.CommandHandler$1
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_181]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.13.2.jar:git-Paper-456]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.13.2.jar:git-Paper-456]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.CommandAPI.CommandHandler.runCommand(CommandHandler.java:371) ~[?:?]
at com.Ben12345rocks.VotingPlugin.Commands.Executers.CommandAdminVote.onCommand(CommandAdminVote.java:65) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-456]
... 15 more
```

**Comment by BenCodez** [comment]
Download the plugin from the plugin page?

**Comment by LogGits** [comment]
Ok i just downloaded from the plugin page and it works. I think i just had a bad download. Thanks for your help 👍
