### ISSUE TITLE
Everything got reset

### ISSUE THREAD

**Issue by LogGits** [BenCodez/VotingPlugin#466]
So everyones data on the server got reset. All votes, votesteaks etc. Is there a way i can get this stuff back and prevent it from happening in the future? I did see a "PurgeOldData" is set to false. I don't know what could have caused this. Everytime a user votes it also says that it's their first time voting.

VotingPlugin build 5.16.3
Paper build 475 1.13.2

**Comment by LogGits** [comment]
I just updated to 5.17.0 and got this error:
```
WARN 15/12/2018 17:26:33
17:26:33 at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613)
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575)
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435)
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791)
at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Annotation.AnnotationHandler.load(AnnotationHandler.java:77)
at com.Ben12345rocks.VotingPlugin.Config.Config.loadValues(Config.java:1385)
at com.Ben12345rocks.VotingPlugin.Main.setupFiles(Main.java:912)
at com.Ben12345rocks.VotingPlugin.Main.onEnable(Main.java:703)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613)
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575)
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435)
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791)
at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Annotation.AnnotationHandler.load(AnnotationHandler.java:77)
at com.Ben12345rocks.VotingPlugin.Config.Config.loadValues(Config.java:1385)
at com.Ben12345rocks.VotingPlugin.Main.setupFiles(Main.java:912)
at com.Ben12345rocks.VotingPlugin.Main.onEnable(Main.java:703)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613)
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575)
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435)
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791)
at java.lang.Thread.run(Thread.java:748)
```
Is there a way to restore from previous backup in the backups folder?

**Comment by BenCodez** [comment]
Are you using mysql? Any other errors?

This help?
http://ben12345rocks.com/job/VotingPlugin/

**Comment by LogGits** [comment]
Using sqlite, i didnt notice any other errors but im downloading logs from the past week to check. The build that i am using 5.17.0 that gave the previous error does seem to allow players to vote but i think its also broken commands. I will check in a sec.

**Comment by BenCodez** [comment]
Try the latest update

**Comment by BenCodez** [comment]
There should also be a backup folder.

**Comment by LogGits** [comment]
Latest update fixes error and commands work now. How do i restore from a backup?

**Comment by BenCodez** [comment]
Copy the files and replace? Don't have any other way

**Comment by LogGits** [comment]
Will it also restore votestreak?

**Comment by BenCodez** [comment]
Maybe, It should in theory

**Comment by LogGits** [comment]
Ok, it didn't restore votestreak people lost votestreaks but their vote info is back. That's a scary issue.

**Comment by LogGits** [comment]
This happened again. Lost all votes, no errors in logs.

**Comment by BenCodez** [comment]
Latest version?

**Comment by LogGits** [comment]
5.18.1 but you added player heads thingy so i dont think that it matters if i am 1 version behind.

**Comment by LogGits** [comment]
Idk if this has an impact but i recently changed the server.properties `level.name` to `world2` cause we reset the world map.

**Comment by BenCodez** [comment]
Shouldn't matter. Unless you somehow deleted it.

**Comment by LogGits** [comment]
Ah ok, yeah that wasnt deleted

**Comment by BenCodez** [comment]
I got no idea. I need more details in order to be able to help at all. Difference in data from before and after would help.
