### ISSUE TITLE
New update error

### ISSUE THREAD

**Issue by LogGits** [BenCodez/VotingPlugin#472]
Build 512 1.13.2 paperspigot 470
```
ERROR 17/12/2018 18:09:57
18:09:57Could not pass event PlayerVoteEvent to VotingPlugin v5.17.1
Console 17/12/2018 18:09:57
18:09:57org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-481]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.13.2.jar:git-Paper-481]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-481]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-481]
at com.Ben12345rocks.VotingPlugin.Listeners.VotiferEvent$2.run(VotiferEvent.java:93) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-481]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-481]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-481]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NumberFormatException: For input string: ""
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_181]
at java.lang.Long.parseLong(Long.java:601) ~[?:1.8.0_181]
at java.lang.Long.parseLong(Long.java:631) ~[?:1.8.0_181]
at com.Ben12345rocks.VotingPlugin.Objects.User.getDayVoteStreakLastUpdate(User.java:144) ~[?:?]
at com.Ben12345rocks.VotingPlugin.Objects.User.voteStreakUpdatedToday(User.java:140) ~[?:?]
at com.Ben12345rocks.VotingPlugin.Objects.User.checkDayVoteStreak(User.java:129) ~[?:?]
at com.Ben12345rocks.VotingPlugin.Listeners.PlayerVoteListener.onplayerVote(PlayerVoteListener.java:141) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor372.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-481]
... 10 more
```

**Comment by BenCodez** [comment]
That with the dev build?

**Comment by LogGits** [comment]
yes this build http://ben12345rocks.com/job/VotingPlugin/512/changes

**Comment by BenCodez** [comment]
I'll fix that later then.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

This work?

Make sure it's build 513, 514 might not work. I made a change on something else.

**Comment by LogGits** [comment]
I tried on 514 and it works 👍Thanks a tonne for adding this :heart:
