### ISSUE TITLE
IllegalAccessError: tried to access method com.zaxxer.hikari.pool.HikariProxyStatement

### ISSUE THREAD

**Issue by mibby** [BenCodez/VotingPlugin#501]
VotingPlugin dev 596

@Ben12345rocks Caused by commit change here https://github.com/Ben12345rocks/AdvancedCore/commit/9a61911cda1ce4c65b208ee9b4b4fdc0f36e6d88?
```
[23:47:07] [Timer-3/WARN]: Exception in thread "Timer-3" java.lang.IllegalAccessError: tried to access method com.zaxxer.hikari.pool.HikariProxyStatement.<init>(Lcom/zaxxer/hikari/pool/ProxyConnection;Ljava/sql/Statement;)V from class com.zaxxer.hikari.pool.ProxyFactory
[23:47:07] [Timer-3/WARN]: 	at com.zaxxer.hikari.pool.ProxyFactory.getProxyStatement(ProxyFactory.java)
[23:47:07] [Timer-3/WARN]: 	at com.zaxxer.hikari.pool.ProxyConnection.createStatement(ProxyConnection.java:273)
[23:47:07] [Timer-3/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyConnection.createStatement(HikariProxyConnection.java)
[23:47:07] [Timer-3/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.updateBatch(MySQL.java:542)
[23:47:07] [Timer-3/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL$3.run(MySQL.java:142)
[23:47:07] [Timer-3/WARN]: 	at java.util.TimerThread.mainLoop(Timer.java:555)
[23:47:07] [Timer-3/WARN]: 	at java.util.TimerThread.run(Timer.java:505)
```

Downgrading to dev 590, everything is working fine.

**Comment by BenCodez** [comment]
Will look at later

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

This better?

**Comment by mibby** [comment]
No. See commint linked above, I think that's the cause.

Dev 598
```
[22:56:47] [Timer-3/WARN]: Exception in thread "Timer-3" java.lang.IllegalAccessError: tried to access method com.zaxxer.hikari.pool.HikariProxyStatement.<init>(Lcom/zaxxer/hikari/pool/ProxyConnection;Ljava/sql/Statement;)V from class com.zaxxer.hikari.pool.ProxyFactory
[22:56:47] [Timer-3/WARN]: 	at com.zaxxer.hikari.pool.ProxyFactory.getProxyStatement(ProxyFactory.java)
[22:56:47] [Timer-3/WARN]: 	at com.zaxxer.hikari.pool.ProxyConnection.createStatement(ProxyConnection.java:273)
[22:56:47] [Timer-3/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyConnection.createStatement(HikariProxyConnection.java)
[22:56:47] [Timer-3/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.updateBatch(MySQL.java:542)
[22:56:47] [Timer-3/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL$3.run(MySQL.java:142)
[22:56:47] [Timer-3/WARN]: 	at java.util.TimerThread.mainLoop(Timer.java:555)
[22:56:47] [Timer-3/WARN]: 	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by BenCodez** [comment]
I don't think it's from that commit. Might be from the other issue.

**Comment by mibby** [comment]
You might have been correct. Dev 599 seems good now.
