### ISSUE TITLE
Build 599 error

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#504]
Getting this error when trying build 599
```[22:13:05] [Craft Scheduler Thread - 11/WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such column: PlayerName)
[22:13:05] [Craft Scheduler Thread - 11/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:941)
[22:13:05] [Craft Scheduler Thread - 11/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:953)
[22:13:05] [Craft Scheduler Thread - 11/WARN]: 	at org.sqlite.core.DB.throwex(DB.java:918)
[22:13:05] [Craft Scheduler Thread - 11/WARN]: 	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[22:13:05] [Craft Scheduler Thread - 11/WARN]: 	at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
[22:13:05] [Craft Scheduler Thread - 11/WARN]: 	at org.sqlite.core.DB.prepare(DB.java:257)
[22:13:05] [Craft Scheduler Thread - 11/WARN]: 	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:47)
[22:13:05] [Craft Scheduler Thread - 11/WARN]: 	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
[22:13:05] [Craft Scheduler Thread - 11/WARN]: 	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
[22:13:05] [Craft Scheduler Thread - 11/WARN]: 	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
[22:13:05] [Craft Scheduler Thread - 11/WARN]: 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
[22:13:05] [Craft Scheduler Thread - 11/WARN]: 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
[22:13:05] [Craft Scheduler Thread - 11/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.sql.Table.getRowsNames(Table.java:264)
[22:13:05] [Craft Scheduler Thread - 11/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.sql.Table.getNames(Table.java:211)
[22:13:05] [Craft Scheduler Thread - 11/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserManager.getAllPlayerNames(UserManager.java:51)
[22:13:05] [Craft Scheduler Thread - 11/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Misc.PlayerUtils$1.run(PlayerUtils.java:365)
[22:13:05] [Craft Scheduler Thread - 11/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
[22:13:05] [Craft Scheduler Thread - 11/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[22:13:05] [Craft Scheduler Thread - 11/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:13:05] [Craft Scheduler Thread - 11/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[22:13:05] [Craft Scheduler Thread - 11/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[22:13:05] [Craft Scheduler Thread - 11/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by BenCodez** [comment]
Full console log of the error?

**Comment by x1p** [comment]
https://pastebin.com/djktis19

**Comment by BenCodez** [comment]
Restart the server fix it?

**Comment by x1p** [comment]
Nope. Haven't tried mySQL yet. This is a default test server. I just put the plugin on it so it would create it's default config files.

**Comment by BenCodez** [comment]
mysql would work, it just can't create a column for whatever reason.

**Comment by x1p** [comment]
Still see this:
```
[23:03:42] [Server thread/ERROR]: [VotingPlugin] Plugin VotingPlugin v5.17.5 has failed to register events for class com.Ben12345rocks.VotingPlugin.Listeners.VotiferEvent because com/vexsoftware/votifier/model/VotifierEvent does not exist.
```
But on this server, I haven't got votesites set up so might as well be that.
MySQL works indeed

**Comment by BenCodez** [comment]
Fixed the problem, just waiting for dev build to be built.

**Comment by BenCodez** [comment]
Should be good now:
http://ben12345rocks.com/job/VotingPlugin/

**Comment by x1p** [comment]
Indeed. Works without errors.
I'll close this now. Tnx
