### ISSUE TITLE
Plugin VotingPlugin v5.18.2 generated an exception while executing task 48

### ISSUE THREAD

**Issue by resi23** [BenCodez/VotingPlugin#517]
When I stop the server I get the following error message

`[14:23:29] [Craft Scheduler Thread - 13/WARN]: [VotingPlugin] Plugin VotingPlugin v5.18.2 generated an exception while executing task 48
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:515) ~[patched_1.13.2.jar:git-Paper-535]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:220) ~[patched_1.13.2.jar:git-Paper-535]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:216) ~[patched_1.13.2.jar:git-Paper-535]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:167) ~[patched_1.13.2.jar:git-Paper-535]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:136) ~[patched_1.13.2.jar:git-Paper-535]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Skull.SkullThread$ReadThread.load(SkullThread.java:68) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Skull.SkullHandler.loadSkull(SkullHandler.java:73) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Skull.SkullThread$ReadThread.startup(SkullThread.java:107) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Skull.SkullHandler$1.run(SkullHandler.java:58) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-535]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-535]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-535]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]`

Complete Logfile: https://pastebin.com/dArAyTuT

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

That help?

**Comment by resi23** [comment]
Yes, no Errors anymore :) Thank you very much
