### ISSUE TITLE
Error on loading

### ISSUE THREAD

**Issue by Rosu-Catalin** [BenCodez/VotingPlugin#520]
[16:46:54] [Server thread/ERROR]: Error occurred while enabling VotingPlugin v5.18.2 (Is it up to date?)
java.lang.NoSuchFieldError: UI_BUTTON_CLICK
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreConfigOptions.<init>(AdvancedCoreConfigOptions.java:123) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.<init>(AdvancedCoreHook.java:124) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.<clinit>(AdvancedCoreHook.java:73) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Main.debug(Main.java:227) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Main.setupFiles(Main.java:952) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Main.onEnable(Main.java:716) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by BenCodez** [comment]
Later versions don't support 1.12 and below.
