### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LogGits** [BenCodez/VotingPlugin#534]
```
[09:15:36] [Timer-5/WARN]: Exception in thread "Timer-5" java.lang.IllegalAccessError: tried to access method com.zaxxer.hikari.pool.HikariProxyStatement.<init>(Lcom/zaxxer/hikari/pool/ProxyConnection;Ljava/sql/Statement;)V from class com.zaxxer.hikari.pool.ProxyFactory
[09:15:36] [Timer-5/WARN]: 	at com.zaxxer.hikari.pool.ProxyFactory.getProxyStatement(ProxyFactory.java)
[09:15:36] [Timer-5/WARN]: 	at com.zaxxer.hikari.pool.ProxyConnection.createStatement(ProxyConnection.java:273)
[09:15:36] [Timer-5/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyConnection.createStatement(HikariProxyConnection.java)
[09:15:36] [Timer-5/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.updateBatch(MySQL.java:542)
[09:15:36] [Timer-5/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL$3.run(MySQL.java:142)
[09:15:36] [Timer-5/WARN]: 	at java.util.TimerThread.mainLoop(Timer.java:555)
[09:15:36] [Timer-5/WARN]: 	at java.util.TimerThread.run(Timer.java:505)
```
vp 5.18.2 spigot build (and latest jenkins build)
paper 1.13.2 build 610

**Comment by BenCodez** [comment]
Is there another plugin with hikari mysql installed?

Edit: try the newer jenkins build

**Comment by LogGits** [comment]
Still get this error on build 53
```
[17:00:28] [Timer-5/WARN]: Exception in thread "Timer-5" java.lang.IllegalAccessError: tried to access method com.zaxxer.hikari.pool.HikariProxyStatement.<init>(Lcom/zaxxer/hikari/pool/ProxyConnection;Ljava/sql/Statement;)V from class com.zaxxer.hikari.pool.ProxyFactory
[17:00:28] [Timer-5/WARN]: 	at com.zaxxer.hikari.pool.ProxyFactory.getProxyStatement(ProxyFactory.java)
[17:00:28] [Timer-5/WARN]: 	at com.zaxxer.hikari.pool.ProxyConnection.createStatement(ProxyConnection.java:273)
[17:00:28] [Timer-5/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyConnection.createStatement(HikariProxyConnection.java)
[17:00:28] [Timer-5/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.updateBatch(MySQL.java:542)
[17:00:28] [Timer-5/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL$3.run(MySQL.java:142)
[17:00:28] [Timer-5/WARN]: 	at java.util.TimerThread.mainLoop(Timer.java:555)
[17:00:28] [Timer-5/WARN]: 	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by BenCodez** [comment]
How about now?
http://ben12345rocks.com/job/VotingPlugin/

**Comment by LogGits** [comment]
on build 63 i still get the error
```
Exception in thread "Timer-5" java.lang.IllegalAccessError: tried to access method com.zaxxer.hikari.pool.HikariProxyStatement.<init>(Lcom/zaxxer/hikari/pool/ProxyConnection;Ljava/sql/Statement;)V from class com.zaxxer.hikari.pool.ProxyFactory
at com.zaxxer.hikari.pool.ProxyFactory.getProxyStatement(ProxyFactory.java)
at com.zaxxer.hikari.pool.ProxyConnection.createStatement(ProxyConnection.java:273)
at com.zaxxer.hikari.pool.HikariProxyConnection.createStatement(HikariProxyConnection.java)
at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.updateBatch(MySQL.java:542)
at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL$3.run(MySQL.java:142)
at java.util.TimerThread.mainLoop(Timer.java:555)
at java.util.TimerThread.run(Timer.java:505)
```

**Comment by BenCodez** [comment]
Now?
http://ben12345rocks.com/job/VotingPlugin/

**Comment by LogGits** [comment]
On build 69 the error is gone <3
