### ISSUE TITLE
Failed to load data for block entity minecraft:sign java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by andris155** [BenCodez/VotingPlugin#567]
Paper 1.14.3
```
[19:54:54] [Server thread/ERROR]: Failed to load data for block entity minecraft:sign
java.lang.NullPointerException: null
	at net.minecraft.server.v1_14_R1.ChatComponentUtils.filterForDisplay(SourceFile:38) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.TileEntitySign.load(TileEntitySign.java:103) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.TileEntity.lambda$create$1(TileEntity.java:135) ~[patched_1.14.3.jar:git-Paper-122]
	at java.util.Optional.map(Optional.java:265) ~[?:?]
	at net.minecraft.server.v1_14_R1.TileEntity.create(TileEntity.java:132) ~[patched_1.14.3.jar:git-Paper-122]
	at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlockEntityState.createSnapshot(CraftBlockEntityState.java:82) ~[patched_1.14.3.jar:git-Paper-122]
	at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:37) ~[patched_1.14.3.jar:git-Paper-122]
	at org.bukkit.craftbukkit.v1_14_R1.block.CraftSign.<init>(CraftSign.java:19) ~[patched_1.14.3.jar:git-Paper-122]
	at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.getState0(CraftBlock.java:344) ~[patched_1.14.3.jar:git-Paper-122]
	at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.getState(CraftBlock.java:322) ~[patched_1.14.3.jar:git-Paper-122]
	at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.getState(CraftBlock.java:316) ~[patched_1.14.3.jar:git-Paper-122]
	at com.Ben12345rocks.VotingPlugin.Listeners.PlayerInteract.onPlayerInteract(PlayerInteract.java:45) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor365.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.3.jar:git-Paper-122]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.3.jar:git-Paper-122]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.3.jar:git-Paper-122]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.3.jar:git-Paper-122]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:445) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:441) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1392) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:978) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-122]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by BenCodez** [comment]
Can't recreate. Any details?
