### ISSUE TITLE
NoClassDefFoundError: com/vexsoftware/votifier/Votifier

### ISSUE THREAD

**Issue by mibby** [BenCodez/VotingPlugin#568]
VotingPlugin dev 206
nuVotifier dev 42

@Ben12345rocks https://github.com/Ben12345rocks/VotingPlugin/commit/6d760e2c5b34043aa24067a16c2f497208af011d Breaks when using nuVotifier?

```
[23:01:23] [Craft Scheduler Thread - 13/WARN]: [VotingPlugin] Plugin VotingPlugin v5.19 generated an exception while executing task 111
java.lang.NoClassDefFoundError: com/vexsoftware/votifier/Votifier
	at com.Ben12345rocks.VotingPlugin.Main.checkVotifierLoaded(Main.java:146) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Main.access$100(Main.java:86) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Main$38.run(Main.java:873) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.3.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.3.jar:git-Paper-123]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.3.jar:git-Paper-123]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: com.vexsoftware.votifier.Votifier
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.14.3.jar:git-Paper-123]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.3.jar:git-Paper-123]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	... 9 more
```

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Should be good now.
