### ISSUE TITLE
ZİP PROBLEM

### ISSUE THREAD

**Issue by successed** [BenCodez/VotingPlugin#595]
[19:47:36] [Server thread/ERROR]: Could not load 'plugins/VotingPlugin.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:167) ~[patched_1.14.4.jar:git-Paper-163]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:142) ~[patched_1.14.4.jar:git-Paper-163]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:355) ~[patched_1.14.4.jar:git-Paper-163]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.14.4.jar:git-Paper-163]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:869) ~[patched_1.14.4.jar:git-Paper-163]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_222]
	at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_222]
	at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_222]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_222]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_222]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:155) ~[patched_1.14.4.jar:git-Paper-163]
	... 5 more

**Comment by BenCodez** [comment]
Redownload jar.

**Comment by successed** [comment]
t,y
