### ISSUE TITLE
/vote error

### ISSUE THREAD

**Issue by seema84** [BenCodez/VotingPlugin#60]
[INFO]: Player issued server command: /vote

org.bukkit.command.CommandException: Unhandled exception executing command 'vote' in plugin VotingPlugin v3.3.5
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-4af49dc-c5e9a16]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[craftbukkit.jar:git-Spigot-4af49dc-c5e9a16]
at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:645) ~[craftbukkit.jar:git-Spigot-4af49dc-c5e9a16]
at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1349) [craftbukkit.jar:git-Spigot-4af49dc-c5e9a16]
at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1184) [craftbukkit.jar:git-Spigot-4af49dc-c5e9a16]
at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit.jar:git-Spigot-4af49dc-c5e9a16]
at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit.jar:git-Spigot-4af49dc-c5e9a16]
at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-4af49dc-c5e9a16]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [craftbukkit.jar:git-Spigot-4af49dc-c5e9a16]
at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [craftbukkit.jar:git-Spigot-4af49dc-c5e9a16]
at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [craftbukkit.jar:git-Spigot-4af49dc-c5e9a16]
at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [craftbukkit.jar:git-Spigot-4af49dc-c5e9a16]
at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [craftbukkit.jar:git-Spigot-4af49dc-c5e9a16]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException

Please fix this and add a option to set the Command Priority. (I have a other Plugin with a /vote command)

**Comment by BenCodez** [comment]
/vote works fine for me and everyone else, Send me your Format.yml and make sure you have a VoteURL in each votesite

You can use a command alias to override my /vote command

**Comment by seema84** [comment]
Format.yml -> http://pastebin.com/U06Zw5wa

**Comment by BenCodez** [comment]
I need more info, you don't have the full error, or atleast there isn't enough for me to trace the error. Try  /av reload and try again. Send me the full error if there is one.

**Comment by seema84** [comment]
its the full error log http://pastebin.com/VY1c4TmU

i get the error after i set 3 votesite with  /av VoteSite (SiteName) SetMoney (Money)

**Comment by BenCodez** [comment]
Is there VoteURL: 'Text' in each vote site file?

**Comment by seema84** [comment]
no i have only set ingame  /av VoteSite (SiteName) SetMoney (Money)
as described herein:
https://github.com/Ben12345rocks/VotingPlugin/wiki/Basic-Rewards
(in the docs is a s to many  /av VoteSite(S) (SiteName) SetMoney (Money) )

**Comment by seema84** [comment]
ah ok when i copy the content from the Example.yml file it works
but the doc its not good to setup the votesite

**Comment by BenCodez** [comment]
The error is from having no VoteURL value, the stacktrace clearly shows that.

**Comment by seema84** [comment]
ok maybe its better to set defaults if a player create ingame a votesite
please edit the docs /av VoteSite(**S**)  does not work

**Comment by BenCodez** [comment]
I'm pretty sure it works, do you reload the plugin after you do the command?

**Comment by BenCodez** [comment]
It is also just easier to edit the files manually, but I am pretty sure it works.

**Comment by seema84** [comment]
yes my problem works now (as I wrote before 18 min)
the defaults with ingame commands is only a idea

**Comment by BenCodez** [comment]
When a votesite gets ceated (with commands or automaticly) it generates with default values, enough for no errors.

**Comment by seema84** [comment]
and /av VoteSites do not work
from https://github.com/Ben12345rocks/VotingPlugin/wiki/Basic-Rewards

right is /av VoteSite (without s)

**Comment by BenCodez** [comment]
/av VoteSites does nothing, it needs arguments behind it

**Comment by seema84** [comment]
if a votesite created it generate no defaults

**Comment by BenCodez** [comment]
It is generated with defaults, use /av VoteSite (siteName) create

**Comment by seema84** [comment]
in /av help there is not the /av votesite(s) command

ah ok but with /av VoteSite (siteName) setMoney Money it dont set defaults

**Comment by BenCodez** [comment]
When you use any of the set commands its already assumed there is a votesite file generated, I will take a look at /av help, probably missed a command or two.

**Comment by seema84** [comment]
also i can create too sites with /av votesites name1 name2 ?

**Comment by BenCodez** [comment]
No, only one at a time, you could also just vote on the site it should be auto created as well if votifier is setup.

**Comment by seema84** [comment]
please test it yourself the command from the docs /av votesites is wrong right is /av votesite
/av votsites has no function please edit the docs

**Comment by BenCodez** [comment]
Oh oops, I did those commands off by memory :P I guess I will go fix that, there is a full list though seen [here](https://github.com/Ben12345rocks/VotingPlugin/wiki/Commands-&-Permissions), did notice I missed a few commands in that list though, whoops.

**Comment by BenCodez** [comment]
Fixed.

**Comment by seema84** [comment]
and can you please "all" /vote help output add in Format.yml a half translating its not so good

**Comment by BenCodez** [comment]
I originally had that, but removed it because I kept adding commands, maybe I will readd it for the next update.

**Comment by seema84** [comment]
translations brings only a little if i can translate all text
if a rus owner translate your plugin and there user cant english how they should understand this output?
i think you know what i mean

**Comment by BenCodez** [comment]
Yeah, I'll do that for the next version then. Aiming this/next weekend or so to release it.
