### ISSUE TITLE
Some error on server shutdown

### ISSUE THREAD

**Issue by Qinak** [BenCodez/VotingPlugin#611]
```
[01:43:37 WARN]: [VotingPlugin] Plugin VotingPlugin v5.19.4 generated an exception while executing task 24
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:518) ~[patched_1.14.4.jar:git-Paper-176]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:221) ~[patched_1.14.4.jar:git-Paper-176]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:217) ~[patched_1.14.4.jar:git-Paper-176]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:168) ~[patched_1.14.4.jar:git-Paper-176]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:137) ~[patched_1.14.4.jar:git-Paper-176]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Skull.SkullHandler.loadSkull(SkullHandler.java:154) ~[?:?]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Skull.SkullThread$ReadThread.startup(SkullThread.java:107) ~[?:?]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Skull.SkullHandler$1.run(SkullHandler.java:142) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-176]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-176]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-176]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

This better?

**Comment by Qinak** [comment]
Better :)
