### ISSUE TITLE
Bungee version

### ISSUE THREAD

**Issue by BenCodez** [BenCodez/VotingPlugin#627]
Allow VotingPlugin to be on Bungee server.
Global broadcast, etc

**Comment by x1p** [comment]
I was impatient and tried to make a test setup.
Once the vote should have been broadcasted on a second server I got this error.
```
[14:29:13 WARN]: [VotingPlugin] Plugin VotingPlugin v5.20.2 generated an exception whilst handling plugin message
java.lang.NullPointerException: null
at com.Ben12345rocks.VotingPlugin.BungeeHandler$2.onRecieve(BungeeHandler.java:38) ~[?:?]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.PluginMessage.PluginMessage.onPluginMessageReceived(PluginMessage.java:58) ~[?:?]
at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:436) ~[patched_1.13.2.jar:git-Paper-650]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2625) ~[patched_1.13.2.jar:git-Paper-650]
at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:45) ~[patched_1.13.2.jar:git-Paper-650]
at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.13.2.jar:git-Paper-650]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-650]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-650]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-650]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-650]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-650]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-650]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
Used 5.20.2-b410 on a Waterfall proxy, first server 1.14.4, second server 1.13.2.

Edit: I apparently forgot to define the votesite on the second server.

Edit2:
Works pretty nice. But for some reason some names don't get broadcasted.
Debug gives this reason: `Can't send plugin message, player == null`
Player is known and online on the second server
So the player needs to be online on the first (hub) server although I've set
```
  # Broadcast only when player is online
  BroadcastWhenOnline: false
```

**Comment by BenCodez** [comment]
Yeah, it's still a wip. Still a few things I need to do on that.

**Comment by BenCodez** [comment]
This will add to the debug, and fix the first error from popping up.
http://ben12345rocks.com/job/VotingPlugin/

**Comment by BenCodez** [comment]
@x1p 
http://ben12345rocks.com/job/VotingPlugin/

How much better is this for you? I haven't tested some of the changes yet.

**Comment by x1p** [comment]
I can't run build 415 on a normal (spigot like) server.
```
[10:30:53] [Craft Scheduler Thread - 26/WARN]: [VotingPlugin] Plugin VotingPlugin v5.20.2 generated an exception while executing task 51
java.lang.NullPointerException: null
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCorePlugin$11.onStartUp(AdvancedCorePlugin.java:601) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCorePlugin$13.run(AdvancedCorePlugin.java:821) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-210]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-210]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-210]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by x1p** [comment]
I picked up the testing:
When I vote for a known playername, this happens:
```
Can't send plugin message, player == null, Broadcast data: MCTools.org, TestPlayer123
```

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

That should fixed that.

**Comment by x1p** [comment]
Unfortunately not
The player needs to be online on the first server or else this appears again: `player == null`

**Comment by BenCodez** [comment]
Yeah, plugin messages require an online player. But that's not the main part of the plugin, atleast bungee version wise. Votes work on bungee server?

**Comment by x1p** [comment]
The player is online on the second server, so I'm not sure what the bungee plugin adds in this

**Comment by BenCodez** [comment]
Having nuvotifier on bungee to handle giving votes on each server.

**Comment by x1p** [comment]
So Votingplugin can pick up votes directly from nuvotifier on the bungee?

**Comment by BenCodez** [comment]
That's the idea.

**Comment by x1p** [comment]
Oh ok. I thought it would still need votifier on the spigot server, so I forwarded the vote to the first server.
In that case I will change the routing
Edit: vote arrives, but then nothing happens. I have to find out how VotingPlugin should pick it up

**Comment by BenCodez** [comment]
Is mysql setup on bungee?
Is bungee enabled on sub servers?

**Comment by x1p** [comment]
Both: yes
The first paper server does not print out something so I suspect that votingplugin on bungee does not listen to the votifier on the bungee. The vote point are not added either.
The votingplugin is loaded a moment before nuvotifier is loaded. There is no message that says that it's hooked into the nuvotifier correctly.

**Comment by BenCodez** [comment]
There is no message set. You'll have to be on the server to get the reward processed. Make sure you set the server name in each server (same as what it is on bungee)
