### ISSUE TITLE
Little exception

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#638]
Saw this error appear out of nowhere.
No one was voting or doing anything with the plugin.

```
[22:13:38 WARN]: [VotingPlugin] Plugin VotingPlugin v5.20.1 generated an exception while executing task 8334
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_212]
at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_212]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Misc.ArrayUtils.convert(ArrayUtils.java:172) ~[?:?]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserManager.getAllUUIDs(UserManager.java:91) ~[?:?]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.User.hasLoggedOnBefore(User.java:565) ~[?:?]
at com.Ben12345rocks.VotingPlugin.CoolDown.CoolDownCheck$1.run(CoolDownCheck.java:63) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-196]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-196]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-196]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
VotingPlugin 5.20.1
Paper 1.14.4 build 196

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

This fix it?

**Comment by x1p** [comment]
I think it's solved. Haven't seen it since

**Comment by x1p** [comment]
I'm afraid latest stable version has it too.
```
[12:57:54 WARN]: [VotingPlugin] Plugin VotingPlugin v5.20.2 generated an exception while executing task 16016
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_212]
at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_212]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Misc.ArrayUtils.convert(ArrayUtils.java:173) ~[?:?]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserManager.getAllUUIDs(UserManager.java:91) ~[?:?]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.User.hasLoggedOnBefore(User.java:565) ~[?:?]
at com.Ben12345rocks.VotingPlugin.CoolDown.CoolDownCheck$1.run(CoolDownCheck.java:63) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-207]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-207]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-207]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Seems to be a different issue then I thought it was, see if that works.

**Comment by x1p** [comment]
Using VotingPlugin 5.20.2-build389
```
[20:49:43 WARN]: [VotingPlugin] Plugin VotingPlugin v5.20.2 generated an exception while executing task 1581156
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_212]
at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_212]
at java.util.AbstractCollection.addAll(AbstractCollection.java:343) ~[?:1.8.0_212]
at java.util.HashSet.<init>(HashSet.java:120) ~[?:1.8.0_212]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Misc.ArrayUtils.convert(ArrayUtils.java:172) ~[?:?]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserManager.getAllUUIDs(UserManager.java:91) ~[?:?]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.User.hasLoggedOnBefore(User.java:565) ~[?:?]
at com.Ben12345rocks.VotingPlugin.CoolDown.CoolDownCheck$1.run(CoolDownCheck.java:63) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-209]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-209]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-209]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Maybe now?

**Comment by x1p** [comment]
```
[00:01:14 INFO]: [VotingPlugin] Time change event: DAY, Fake: false
[00:01:15 INFO]: [VotingPlugin] Created zip file at /home/container/plugins/VotingPlugin/Backups/Backup-2019_OCTOBER_6.zip
[00:01:15 INFO]: [VotingPlugin] Time change event: WEEK, Fake: false
[00:01:15 WARN]: [VotingPlugin] Plugin VotingPlugin v5.20.2 generated an exception while executing task 161546
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_212]
at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_212]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserManager.getAllUUIDs(UserManager.java:93) ~[?:?]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.User.hasLoggedOnBefore(User.java:565) ~[?:?]
at com.Ben12345rocks.VotingPlugin.CoolDown.CoolDownCheck$1.run(CoolDownCheck.java:63) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-209]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-209]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-209]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Maybe now?

Thanks for help trying to solve this by the way.

**Comment by x1p** [comment]
I still haven't seen it happen again
