### ISSUE TITLE
Could not pass event InventoryClickEvent

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#646]
Got this error spamming over and over for half an hour
VotingPlugin 5.20.2 stable
Paper 1.13.2 build 650
```
[11:29:40] [Server thread/ERROR]: Could not pass event InventoryClickEvent to VotingPlugin v5.20.2
java.lang.NullPointerException: null
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Inventory.BInventory.onInventoryClick(BInventory.java:413) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor844.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-650]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-650]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-650]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-650]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2288) ~[patched_1.13.2.jar:git-Paper-650]
	at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.13.2.jar:git-Paper-650]
	at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-650]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-650]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-650]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-650]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-650]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-650]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-650]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by x1p** [comment]
I tried to load the latest dev build with plugman but this occurred:
```
[12:08:13 INFO]: [VotingPlugin] Enabling VotingPlugin v5.20.2
[12:08:13 ERROR]: Error occurred while enabling VotingPlugin v5.20.2 (Is it up to date?)
java.lang.VerifyError: Bad type on operand stack
Exception Details:
Location:
com/Ben12345rocks/VotingPlugin/Objects/VoteSite.giveRewards(Lcom/Ben12345rocks/VotingPlugin/Objects/User;Z)V @87: invokevirtual
Reason:
Type 'com/Ben12345rocks/VotingPlugin/Objects/User' (current frame, stack[1]) is not assignable to 'com/Ben12345rocks/VotingPlugin/AdvancedCore/UserManager/User'
Current Frame:
bci: @87
flags: { }
locals: { 'com/Ben12345rocks/VotingPlugin/Objects/VoteSite', 'com/Ben12345rocks/VotingPlugin/Objects/User', integer }
stack: { 'com/Ben12345rocks/VotingPlugin/AdvancedCore/Rewards/RewardBuilder', 'com/Ben12345rocks/VotingPlugin/Objects/User' }
Bytecode:
0x0000000: bb00 f559 b200 ebb6 00f8 b200 eb2a b400
0x0000010: 31b6 00fb b700 fe1c b601 0213 0104 2ab6
0x0000020: 006e b601 0813 010a 2ab6 0069 b601 0813
0x0000030: 010c bb00 a559 b700 a613 010e b600 aa2a
0x0000040: b601 12b6 0115 b600 afb6 0108 1301 172a
0x0000050: b601 1ab6 0108 2bb6 011e bb00 f559 b200
0x0000060: ebb6 00f8 b200 ebb6 0121 b700 fe1c b601
0x0000070: 0213 0104 2ab6 006e b601 0813 010a 2ab6
0x0000080: 0069 b601 0813 010c bb00 a559 b700 a613
0x0000090: 010e b600 aa2a b601 12b6 0115 b600 afb6
0x00000a0: 0108 1301 172a b601 1ab6 0108 2bb6 011e
0x00000b0: b1
at com.Ben12345rocks.VotingPlugin.Config.ConfigVoteSites.getVoteSitesLoad(ConfigVoteSites.java:193) ~[?:?]
at com.Ben12345rocks.VotingPlugin.Main.loadVoteSites(Main.java:422) ~[?:?]
at com.Ben12345rocks.VotingPlugin.Main.onPreLoad(Main.java:968) ~[?:?]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCorePlugin.onEnable(AdvancedCorePlugin.java:711) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-650]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-650]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-650]
at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) ~[?:?]
at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) ~[?:?]
at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-650]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-650]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-650]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:696) ~[patched_1.13.2.jar:git-Paper-650]
at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:483) ~[patched_1.13.2.jar:git-Paper-650]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:440) ~[patched_1.13.2.jar:git-Paper-650]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-650]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-650]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[12:08:13 INFO]: [VotingPlugin] Disabling VotingPlugin v5.20.2
[12:08:13 WARN]: Exception in thread "Timer-11" java.lang.NullPointerException
[12:08:13 WARN]: at com.Ben12345rocks.VotingPlugin.Signs.Signs.storeSigns(Signs.java:81)
[12:08:13 WARN]: at com.Ben12345rocks.VotingPlugin.Main$43.run(Main.java:985)
[12:08:13 WARN]: at java.util.TimerThread.mainLoop(Timer.java:555)
[12:08:13 WARN]: at java.util.TimerThread.run(Timer.java:505)
[12:08:13 INFO]: [PlugMan] VotingPlugin has been loaded and enabled.
```
I had to restart the server eventually to get it working again.

**Comment by BenCodez** [comment]
You can't really hotswap the jar with plugin man, that would cause that error you got from doing that. Are you still using the dev build? It should be working fine.

**Comment by Castiella** [comment]
I'm using the recent dev build and this is happening to me again too.

**Comment by BenCodez** [comment]
@Castiella Wanna provide the log for that?

**Comment by Momshroom** [comment]
I'm getting this as well.  Paper 192 (1.14.4). VotingPlugin 5.20.2

**Comment by BenCodez** [comment]
Try this
http://ben12345rocks.com/job/VotingPlugin/

**Comment by x1p** [comment]
It didn't happen again on any of my servers. I don't know what caused it so I'm not sure when it's "solved"

**Comment by BenCodez** [comment]
If two people using /vote top at the same time it will do that, but you got to perfectly time it :)

**Comment by x1p** [comment]
I never use that command, nor my players.

**Comment by BenCodez** [comment]
Well, that's interesting then.
