### ISSUE TITLE
Cant get it Run

### ISSUE THREAD

**Issue by Minersheart** [BenCodez/VotingPlugin#648]
I installed succesfully and im using latest Paper single server.
System is ubuntu 18.04 with mysql.
I need Support because any test vote will forwarded instand but no User Vote will corretly registered.
I dont know waht is my issue or waht is wrong.
Can you support me please.

email webmaster@minersheart.de
server mc.minersheart.de
teamspeak ts.minersheart.de

**Comment by BenCodez** [comment]
Check console log on the server getting the vote, it will say if it gets it.

**Comment by Minersheart** [comment]
Here some infos for you

https://pastebin.com/5Xy31Xui

No Vote accepted-....

**Comment by BenCodez** [comment]
Votifier is not getting the vote.

**Comment by Minersheart** [comment]
Yes i have tested port open and ufw disabeld  and i get no vote MCTools.org Test vote runs completly.

I have changhed to SQLIte and have no changhes.

Have you any ideas what kind of issue this is...!??

**Comment by Minersheart** [comment]
Votifier Config.yml

# The IP to listen to. Use 0.0.0.0 if you wish to listen to all interfaces on your server. (All IP addresses)
# This defaults to the IP you have configured your server to listen on, or 0.0.0.0 if you have not configured this.
host: 0.0.0.0

# Port to listen for new votes on
port: 8192

# Setting this option to true will disable handling of Protocol v1 packets. While the old protocol is not secure, this
# option is currently not recommended as most voting sites only support the old protocol at present. However, if you are
# using NuVotifier's proxy forwarding mechanism, enabling this option will increase your server's security.
disable-v1-protocol: false

# All tokens, labeled by the serviceName of each server list.
tokens:
  # Default token for all server lists, if another isn't supplied.
  default: 5h8ik2vpo7cnojn4ukvk621amg

# Configuration section for all vote forwarding to NuVotifier
forwarding:
  # Sets whether to set up a remote method for fowarding. Supported methods:
  # - none - Does not set up a forwarding method.
  # - pluginMessaging - Sets up plugin messaging
  method: pluginMessaging
  pluginMessaging:
    channel: nuvotifier:votes
-------------------------------------------------------------------------------------------------------
Public Key

MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvdz5Lv6/h/r77QpSt1ZAnWg5TAKr+zaEgH/xQYiC52MtW1EyAnIsZ4QidhWTJtvxS2WimLtLI2eruyXV2VlJpH23n/ijXOq2oXMTqG/uuMYWIW0W0oXurV8lQAFktB8IuFnxdtLAtUrz4J8miI0w5nKiaSXAVecTDy3wvu9u5KbARYUQ2QLZqsYym43GZXDaGc7Si0NNAg5hyjORB8xkvwRjkIfchV6yuuV1DSOtzkY8VtvcL4h2naCbOtPPadJTYs/F1Ypzty/UlEC6o4aW1QX6cosYYEoShnsvO6/7kui8PS1JYblEq0jHWruWBCAacYBgvQ+GwszXYKQvjg7gmQIDAQAB
------------------------------------------------------------------------------------------------------
One Site i have voted at 11:35 UTF+2 Timezone Germany
https://minecraft-serverliste.com/vote/4711

The Log Tells

[11:34:57] [Votifier NIO worker/ERROR]: [Votifier] Unable to process vote from /37.120.172.98:49292
com.vexsoftware.votifier.netty.handler.codec.CorruptedFrameException: Could not decrypt data (is your key correct?)
	at com.vexsoftware.votifier.net.protocol.VotifierProtocol1Decoder.decode(VotifierProtocol1Decoder.java:34) ~[?:?]
	at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[?:?]
	at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[?:?]
	at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[?:?]
	at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
	at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:249) ~[?:?]
	at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[?:?]
	at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[?:?]
	at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[?:?]
	at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
	at com.vexsoftware.votifier.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[?:?]
	at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
	at com.vexsoftware.votifier.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[?:?]
	at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at com.vexsoftware.votifier.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[?:?]
	at com.vexsoftware.votifier.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[?:?]
	at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) ~[?:?]
	at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:591) ~[?:?]
	at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:508) ~[?:?]
	at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) ~[?:?]
	at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: javax.crypto.BadPaddingException: Decryption error
	at sun.security.rsa.RSAPadding.unpadV15(RSAPadding.java:378) ~[?:?]
	at sun.security.rsa.RSAPadding.unpad(RSAPadding.java:290) ~[?:?]
	at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:366) ~[?:?]
	at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:392) ~[?:?]
	at javax.crypto.Cipher.doFinal(Cipher.java:2202) ~[?:?]
	at com.vexsoftware.votifier.net.protocol.v1crypto.RSA.decrypt(RSA.java:58) ~[?:?]
	at com.vexsoftware.votifier.net.protocol.VotifierProtocol1Decoder.decode(VotifierProtocol1Decoder.java:32) ~[?:?]
	... 28 more

--------------------------------------------------------------------------------------------------------

**Comment by BenCodez** [comment]
Regen your keys. Delete the key folder.

**Comment by Minersheart** [comment]
ok thx itry

**Comment by Minersheart** [comment]
Log
[23:16:35 INFO]: [Votifier] Loaded token for website: default
[23:16:35 INFO]: [Votifier] Receiving votes over PluginMessaging channel 'nuvotifier:votes'.
[23:16:35 INFO]: [Votifier] Reload was successful.
[23:16:35 INFO]: [Votifier] Votifier enabled on socket /0:0:0:0:0:0:0:0:8192.

After Vote
[23:18:08 ERROR]: [Votifier] Unable to process vote from /37.120.172.98:56030
com.vexsoftware.votifier.netty.handler.codec.CorruptedFrameException: Could not decrypt data (is your key correct?)
        at com.vexsoftware.votifier.net.protocol.VotifierProtocol1Decoder.decode(VotifierProtocol1Decoder.java:34) ~[?:?]
        at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[?:?]
        at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[?:?]
        at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[?:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
        at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:249) ~[?:?]
        at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[?:?]
        at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[?:?]
        at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[?:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
        at com.vexsoftware.votifier.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[?:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
        at com.vexsoftware.votifier.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[?:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
        at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
        at com.vexsoftware.votifier.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[?:?]
        at com.vexsoftware.votifier.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[?:?]
        at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) ~[?:?]
        at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:591) ~[?:?]
        at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:508) ~[?:?]
        at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) ~[?:?]
        at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: javax.crypto.BadPaddingException: Decryption error
        at sun.security.rsa.RSAPadding.unpadV15(RSAPadding.java:378) ~[?:?]
        at sun.security.rsa.RSAPadding.unpad(RSAPadding.java:290) ~[?:?]
        at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:366) ~[?:?]
        at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:392) ~[?:?]
        at javax.crypto.Cipher.doFinal(Cipher.java:2202) ~[?:?]
        at com.vexsoftware.votifier.net.protocol.v1crypto.RSA.decrypt(RSA.java:58) ~[?:?]
        at com.vexsoftware.votifier.net.protocol.VotifierProtocol1Decoder.decode(VotifierProtocol1Decoder.java:32) ~[?:?]
        ... 28 more

**Comment by Minersheart** [comment]
I sucessfully delete the rsa Folder and new rsa folder was created

**Comment by BenCodez** [comment]
Did you change the key when testing?

**Comment by Minersheart** [comment]
the public ist random or a complete same one..??
have to changhe them in the VoteSite Config

**Comment by BenCodez** [comment]
Use the public key you just generated, they need to match on the web site for votifier to work.

**Comment by Minersheart** [comment]
Ok now i get a vote ....i test it on each site and give you a report ....thx a lot fom now
