### ISSUE TITLE
NPE: Build 415

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#649]
I can't run build 415 on a normal (spigot like) server.
```
[10:30:53] [Craft Scheduler Thread - 26/WARN]: [VotingPlugin] Plugin VotingPlugin v5.20.2 generated an exception while executing task 51
java.lang.NullPointerException: null
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCorePlugin$11.onStartUp(AdvancedCorePlugin.java:601) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCorePlugin$13.run(AdvancedCorePlugin.java:821) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-210]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-210]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-210]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by BenCodez** [comment]
This work?
http://ben12345rocks.com/job/VotingPlugin/

**Comment by x1p** [comment]
```
[07:59:31 WARN]: [VotingPlugin] Plugin VotingPlugin v5.20.2 generated an exception while executing task 51
java.lang.NullPointerException: null
at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCorePlugin$11.onStartUp(AdvancedCorePlugin.java:601) ~[?:?]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCorePlugin$13.run(AdvancedCorePlugin.java:822) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-210]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-210]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-210]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by x1p** [comment]
Addition errors when player joins:
```
[08:11:35] [Craft Scheduler Thread - 36/ERROR]: Could not pass event AdvancedCoreLoginEvent to VotingPlugin v5.20.2
java.lang.NullPointerException: null
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.update(MySQL.java:519) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserData.setString(UserData.java:267) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.User.setLastOnline(User.java:945) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Listeners.PlayerJoinEvent.onJoin(PlayerJoinEvent.java:54) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor381.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-210]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.14.4.jar:git-Paper-210]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-210]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-210]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Listeners.PlayerJoinEvent$1.run(PlayerJoinEvent.java:85) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-210]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-210]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-210]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
And when a vote is received:
```
[08:18:58] [Craft Scheduler Thread - 44/ERROR]: Could not pass event AdvancedCoreLoginEvent to VotingPlugin v5.20.2
java.lang.NullPointerException: null
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.update(MySQL.java:519) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserData.setString(UserData.java:267) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.User.setLastOnline(User.java:945) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Listeners.PlayerJoinEvent.onJoin(PlayerJoinEvent.java:54) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor381.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-210]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.14.4.jar:git-Paper-210]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-210]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-210]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Listeners.PlayerJoinEvent$1.run(PlayerJoinEvent.java:85) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-210]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-210]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-210]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[08:18:58] [Craft Scheduler Thread - 44/INFO]: [VotingPlugin] Debug: Processing rewards is disabled
[08:19:33] [Craft Scheduler Thread - 48/WARN]: [VotingPlugin] Plugin VotingPlugin v5.20.2 generated an exception while executing task 26427
java.lang.NullPointerException: null
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.update(MySQL.java:519) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserData.setString(UserData.java:267) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Misc.PlayerUtils.getPlayerName(PlayerUtils.java:87) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.User.<init>(User.java:109) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Objects.User.<init>(User.java:74) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.UserManager.UserManager.getVotingPluginUser(UserManager.java:58) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.CoolDown.CoolDownCheck$1.run(CoolDownCheck.java:62) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-210]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-210]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-210]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[08:19:34] [Timer-0/INFO]: [VotingPlugin] Debug: Clearing cache
[08:19:34] [Timer-0/INFO]: [VotingPlugin] Debug: Clearing cache basic
[08:19:34] [Timer-0/INFO]: [VotingPlugin] Debug: Starting background task
[08:19:34] [Timer-0/INFO]: [VotingPlugin] Looks like something went wrong.
[08:19:34] [Timer-0/WARN]: java.lang.NullPointerException
[08:19:34] [Timer-0/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.update(MySQL.java:519)
[08:19:34] [Timer-0/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserData.setString(UserData.java:267)
[08:19:34] [Timer-0/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Misc.PlayerUtils.getPlayerName(PlayerUtils.java:87)
[08:19:34] [Timer-0/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.User.<init>(User.java:109)
[08:19:34] [Timer-0/WARN]: 	at com.Ben12345rocks.VotingPlugin.Objects.User.<init>(User.java:74)
[08:19:34] [Timer-0/WARN]: 	at com.Ben12345rocks.VotingPlugin.UserManager.UserManager.getVotingPluginUser(UserManager.java:58)
[08:19:34] [Timer-0/WARN]: 	at com.Ben12345rocks.VotingPlugin.Main.update(Main.java:1121)
[08:19:34] [Timer-0/WARN]: 	at com.Ben12345rocks.VotingPlugin.Main$3$1.run(Main.java:392)
[08:19:34] [Timer-0/WARN]: 	at java.util.TimerThread.mainLoop(Timer.java:555)
[08:19:34] [Timer-0/WARN]: 	at java.util.TimerThread.run(Timer.java:505)
```
FYI: This test server is using mysql storage

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Good now?

**Comment by x1p** [comment]
Startup
```
[23:22:27 WARN]: [VotingPlugin] Detected an issue with voting sites, check the server startup log for more details
[23:22:27 INFO]: [VotingPlugin] Debug: User Startup starting
[23:22:27 INFO]: [VotingPlugin] Debug: Starting background uuid task
[23:22:27 WARN]: [VotingPlugin] Plugin VotingPlugin v5.20.2 generated an exception while executing task 51
java.lang.NullPointerException: null
at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCorePlugin$11.onStartUp(AdvancedCorePlugin.java:601) ~[?:?]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCorePlugin$13.run(AdvancedCorePlugin.java:822) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-210]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-210]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-210]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
When player joins
```
[23:24:51 ERROR]: Could not pass event AdvancedCoreLoginEvent to VotingPlugin v5.20.2
java.lang.NullPointerException: null
at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.update(MySQL.java:519) ~[?:?]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserData.setString(UserData.java:267) ~[?:?]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.User.setLastOnline(User.java:945) ~[?:?]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.Listeners.PlayerJoinEvent.onJoin(PlayerJoinEvent.java:54) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor381.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-210]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.14.4.jar:git-Paper-210]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-210]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-210]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.Listeners.PlayerJoinEvent$1.run(PlayerJoinEvent.java:85) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-210]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-210]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-210]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by BenCodez** [comment]
Build 421 works for me. Try with that?

**Comment by x1p** [comment]
build 421
```
[23:37:31 WARN]: [VotingPlugin] Plugin VotingPlugin v5.20.2 generated an exception while executing task 51
java.lang.NullPointerException: null
at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCorePlugin$11.onStartUp(AdvancedCorePlugin.java:601) ~[?:?]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCorePlugin$13.run(AdvancedCorePlugin.java:822) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-210]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-210]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-210]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
I don't know what I'm doing wrong then ¯\_(ツ)_/¯

**Comment by BenCodez** [comment]
What's in your mysql table?
http://ben12345rocks.com/job/VotingPlugin/

Build 424
Should silence the error now, not sure what's happening.

**Comment by x1p** [comment]
In the table is only a few test votes for 3 players.

**Comment by BenCodez** [comment]
What columns do you have?

**Comment by BenCodez** [comment]
I think I figured it out.
Build 426, if you have debug and no errors pop up then it should be good.

**Comment by x1p** [comment]
```
1	uuid	varchar(37)	utf8mb4_general_ci
2	TopVoterIgnore	varchar(5)	utf8mb4_general_ci
3	CheckWorld	varchar(5)	utf8mb4_general_ci
4	Reminded	varchar(5)	utf8mb4_general_ci
5	DisableBroadcast	varchar(5)	utf8mb4_general_ci
6	LastOnline	varchar(20)	utf8mb4_general_ci
7	PlayerName	varchar(30)	utf8mb4_general_ci
8	DailyTotal	int(11)	
9	WeeklyTotal	int(11)	
10	DayVoteStreak	int(11)	
11	BestDayVoteStreak	int(11)	
12	WeekVoteStreak	int(11)	
13	BestWeekVoteStreak	int(11)	
14	VotePartyVotes	int(11)	
15	MonthVoteStreak	int(11)	
16	Points	int(11)	
17	HighestDailyTotal	int(11)	
18	MileStoneTotal	int(11)	
19	AllTimeTotal	int(11)	
20	HighestMonthlyTotal	int(11)	
21	MilestoneCount	int(11)	
22	MonthTotal	int(11)	
23	HighestWeeklyTotal	int(11)	
24	LastMonthTotal	int(11)	
25	LastVotes	text	utf8mb4_general_ci
26	LastVoteCoolDownCheck	text	utf8mb4_general_ci
27	OfflineVotes	text	utf8mb4_general_ci
28	DayVoteStreakLastUpdate	text	utf8mb4_general_ci
```

**Comment by BenCodez** [comment]
Hopefully the new build solves it.

**Comment by x1p** [comment]
It indeed fixes the first message
But as soon the player joins...
```
[00:20:56 ERROR]: Could not pass event AdvancedCoreLoginEvent to VotingPlugin v5.20.2
java.lang.NullPointerException: null
at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.update(MySQL.java:519) ~[?:?]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserData.setString(UserData.java:267) ~[?:?]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.User.setCheckWorld(User.java:921) ~[?:?]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.User.checkOfflineRewards(User.java:216) ~[?:?]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.Listeners.PlayerJoinEvent.onJoin(PlayerJoinEvent.java:53) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor381.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-210]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.14.4.jar:git-Paper-210]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-210]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-210]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.Listeners.PlayerJoinEvent$1.run(PlayerJoinEvent.java:85) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-210]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-210]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-210]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[00:20:56 INFO]: [VotingPlugin] Debug: Adding column: Proxy_Test1
[00:20:56 ERROR]: Could not pass event AdvancedCoreLoginEvent to VotingPlugin v5.20.2
java.lang.NullPointerException: null
at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.update(MySQL.java:519) ~[?:?]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserData.setString(UserData.java:267) ~[?:?]
at com.Ben12345rocks.VotingPlugin.Objects.User.bungeeVote(User.java:613) ~[?:?]
at com.Ben12345rocks.VotingPlugin.Objects.User.bungeeVote(User.java:603) ~[?:?]
at com.Ben12345rocks.VotingPlugin.Listeners.PlayerJoinEvent.onPlayerLogin(PlayerJoinEvent.java:56) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor386.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-210]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.14.4.jar:git-Paper-210]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-210]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-210]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.Listeners.PlayerJoinEvent$1.run(PlayerJoinEvent.java:85) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-210]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-210]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-210]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by BenCodez** [comment]
Well, now that makes more sense... explains the first error.
http://ben12345rocks.com/job/VotingPlugin/

Should solve it. Build 428, when it finishes building.

**Comment by x1p** [comment]
Nice, It's getting very late here, I hope I can confirm before my eyes slowly close
Yes works.
Apparently I had some offline votes so it printed some debug stuff.
Vote arrive without errors
I will test bungee functionality further in the morning

**Comment by x1p** [comment]
I think this issue can be solved as I told it is solved
