### ISSUE TITLE
Could not pass event AdvancedCoreLoginEvent

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#659]
**Versions**
Plugin version and spigot version.
5.20.3 build 457 on Paper 1.14.4

**Describe the bug**
```
[21:30:30 ERROR]: Could not pass event AdvancedCoreLoginEvent to VotingPlugin v5.20.3
java.lang.NullPointerException: null
at com.Ben12345rocks.VotingPlugin.Objects.User.bungeeVote(User.java:609) ~[?:?]
at com.Ben12345rocks.VotingPlugin.Objects.User.bungeeVote(User.java:603) ~[?:?]
at com.Ben12345rocks.VotingPlugin.Listeners.PlayerJoinEvent.onPlayerLogin(PlayerJoinEvent.java:56) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor386.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[purpur.jar:git-Purpur-318]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur.jar:git-Purpur-318]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur.jar:git-Purpur-318]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[purpur.jar:git-Purpur-318]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.Listeners.PlayerJoinEvent$1.run(PlayerJoinEvent.java:85) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[purpur.jar:git-Purpur-318]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[purpur.jar:git-Purpur-318]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur.jar:git-Purpur-318]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**To Reproduce**
1. Votingplugin op Paper
2. Set both bungee options to true
3. Join server

**Expected behavior**
No error

**Screenshots**

**Additional context**
I'm experimenting if the VotingPlugin on Bungee so I set VotingPlugin on the (paper) server to look for the bungee version of VotingPlugin

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

That fix it?

**Comment by x1p** [comment]
It was my own fault. I had the database type set on flat instead of mysql.
