### ISSUE TITLE
BungeeBroadcast

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#660]
**Versions**
Plugin version 5.20.3 build 460
Paper 1.14.4
**Describe the bug**
I'm experimenting with Bungee setup
Can't get broadcast to other servers to work
```
# Get the plugin to broadcast to all servers
BungeeBroadcast: true
```
VotingPlugin gives this debug message
`Can't send plugin message, player == null, Broadcast data: MCTools.org, MyPlayerName123`

**To Reproduce**
1. Bungee server: VotingPlugin + nuvotifier set to forward to hub server
2. Hub (paper) server: VotingPlugin + nuvotifier with Both Bungeecord options true
3. Test2 (paper) server: VotingPlugin with Both Bungeecord options true
4. I'm on Test2 server
5. Vote comes in, being processed by Hub server
6. No broadcast is send

**Expected behavior**
I would expect the broadcast being forwarded to the bungee from where it would be forwarded to the servers behind the hub, no matter if any player is online in the hub.

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.

**Additional context**

**Comment by BenCodez** [comment]
Yeah, downside of plugin messaging, might add a socket system to solve that issue. Server processing the reward has to have a player on it.

**Comment by BenCodez** [comment]
Do you want to test a different way of bungeecord handling?
http://ben12345rocks.com/job/VotingPlugin/

You'll need to add this to your configs:
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/Config.yml#L954

https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/bungeeconfig.yml#L12

I haven't tested any of this yet.

**Comment by x1p** [comment]
Thanks for the update.
Bungee start up error:
```
[10:45:00] [main/ERROR]: java.net.BindException: Cannot assign requested address (Bind failed)
[10:45:00] [main/ERROR]: 	at java.net.PlainSocketImpl.socketBind(Native Method)
[10:45:00] [main/ERROR]: 	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
[10:45:00] [main/ERROR]: 	at java.net.ServerSocket.bind(ServerSocket.java:375)
[10:45:00] [main/ERROR]: 	at java.net.ServerSocket.bind(ServerSocket.java:329)
[10:45:00] [main/ERROR]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sockets.SocketServer.<init>(SocketServer.java:34)
[10:45:00] [main/ERROR]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sockets.SocketHandler$1.<init>(SocketHandler.java:14)
[10:45:00] [main/ERROR]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sockets.SocketHandler.<init>(SocketHandler.java:14)
[10:45:00] [main/ERROR]: 	at com.Ben12345rocks.VotingPlugin.bungee.Bungee.onEnable(Bungee.java:67)
[10:45:00] [main/ERROR]: 	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:283)
[10:45:00] [main/ERROR]: 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281)
[10:45:00] [main/ERROR]: 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
[10:45:00] [main/ERROR]: 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```
Startup error paper server:
```
[10:45:55] [Server thread/WARN]: java.net.SocketException: Unresolved address
[10:45:55] [Server thread/WARN]: 	at java.net.ServerSocket.bind(ServerSocket.java:368)
[10:45:55] [Server thread/WARN]: 	at java.net.ServerSocket.bind(ServerSocket.java:329)
[10:45:55] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sockets.SocketServer.<init>(SocketServer.java:34)
[10:45:55] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sockets.SocketHandler$1.<init>(SocketHandler.java:14)
[10:45:55] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sockets.SocketHandler.<init>(SocketHandler.java:14)
[10:45:55] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.BungeeHandler.load(BungeeHandler.java:35)
[10:45:55] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.Main.onPostLoad(Main.java:751)
[10:45:55] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCorePlugin.onEnable(AdvancedCorePlugin.java:742)
[10:45:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[10:45:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[10:45:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[10:45:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:468)
[10:45:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:382)
[10:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:475)
[10:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:299)
[10:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:878)
[10:45:55] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```
When vote arrives:
```
[10:49:22] [Craft Scheduler Thread - 26/WARN]: org.bukkit.plugin.messaging.ChannelNotRegisteredException: Attempted to send a plugin message through the unregistered channel `votingplugin:votingplugin'.
[10:49:22] [Craft Scheduler Thread - 26/WARN]: 	at org.bukkit.plugin.messaging.StandardMessenger.validatePluginMessage(StandardMessenger.java:544)
[10:49:22] [Craft Scheduler Thread - 26/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.sendPluginMessage(CraftPlayer.java:1466)
[10:49:22] [Craft Scheduler Thread - 26/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.PluginMessage.PluginMessage.sendPluginMessage(PluginMessage.java:79)
[10:49:22] [Craft Scheduler Thread - 26/WARN]: 	at com.Ben12345rocks.VotingPlugin.Objects.VoteSite.broadcastVote(VoteSite.java:121)
[10:49:22] [Craft Scheduler Thread - 26/WARN]: 	at com.Ben12345rocks.VotingPlugin.Objects.VoteSite.broadcastVote(VoteSite.java:107)
[10:49:22] [Craft Scheduler Thread - 26/WARN]: 	at com.Ben12345rocks.VotingPlugin.Listeners.PlayerVoteListener.onplayerVote(PlayerVoteListener.java:104)
[10:49:22] [Craft Scheduler Thread - 26/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor389.execute(Unknown Source)
[10:49:22] [Craft Scheduler Thread - 26/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[10:49:22] [Craft Scheduler Thread - 26/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[10:49:22] [Craft Scheduler Thread - 26/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[10:49:22] [Craft Scheduler Thread - 26/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)
[10:49:22] [Craft Scheduler Thread - 26/WARN]: 	at com.Ben12345rocks.VotingPlugin.Listeners.VotiferEvent$2.run(VotiferEvent.java:109)
[10:49:22] [Craft Scheduler Thread - 26/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[10:49:22] [Craft Scheduler Thread - 26/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[10:49:22] [Craft Scheduler Thread - 26/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:49:22] [Craft Scheduler Thread - 26/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[10:49:22] [Craft Scheduler Thread - 26/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[10:49:22] [Craft Scheduler Thread - 26/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```
I have the feeling the ports should not be the game ports but an extra unused port

**Comment by BenCodez** [comment]
Yeah, you need unused ports.

And this should fix that last error.
http://ben12345rocks.com/job/VotingPlugin/

**Comment by x1p** [comment]
I'm still getting this one on the spigot/paper server:
```
[22:44:01 WARN]: org.bukkit.plugin.messaging.ChannelNotRegisteredException: Attempted to send a plugin message through the unregistered channel `votingplugin:votingplugin'.
[22:44:01 WARN]: at org.bukkit.plugin.messaging.StandardMessenger.validatePluginMessage(StandardMessenger.java:544)
[22:44:01 WARN]: at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.sendPluginMessage(CraftPlayer.java:1466)
[22:44:01 WARN]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.PluginMessage.PluginMessage.sendPluginMessage(PluginMessage.java:79)
[22:44:01 WARN]: at com.Ben12345rocks.VotingPlugin.Objects.VoteSite.broadcastVote(VoteSite.java:121)
[22:44:01 WARN]: at com.Ben12345rocks.VotingPlugin.Objects.VoteSite.broadcastVote(VoteSite.java:107)
[22:44:01 WARN]: at com.Ben12345rocks.VotingPlugin.Listeners.PlayerVoteListener.onplayerVote(PlayerVoteListener.java:104)
[22:44:01 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor389.execute(Unknown Source)
[22:44:01 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[22:44:01 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[22:44:01 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[22:44:01 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)
[22:44:01 WARN]: at com.Ben12345rocks.VotingPlugin.Listeners.VotiferEvent$2.run(VotiferEvent.java:109)
[22:44:01 WARN]: at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[22:44:01 WARN]: at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[22:44:01 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:44:01 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[22:44:01 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[22:44:01 WARN]: at java.lang.Thread.run(Thread.java:748)
```

**Comment by BenCodez** [comment]
Latest dev build with usebungeecord set to false?

**Comment by x1p** [comment]
Ok, I'm lost for now.
Bungee Votifier accepts vote, forwards it to the first spigot
Server votifier accepts vote, votingplugin should pick it up and should notify bungee to broadcast it. But this appears:
```
[22:55:02 WARN]: org.bukkit.plugin.messaging.ChannelNotRegisteredException: Attempted to send a plugin message through the unregistered channel `votingplugin:votingplugin'.
[22:55:02 WARN]: at org.bukkit.plugin.messaging.StandardMessenger.validatePluginMessage(StandardMessenger.java:544)
[22:55:02 WARN]: at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.sendPluginMessage(CraftPlayer.java:1466)
[22:55:02 WARN]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.PluginMessage.PluginMessage.sendPluginMessage(PluginMessage.java:79)
[22:55:02 WARN]: at com.Ben12345rocks.VotingPlugin.Objects.VoteSite.broadcastVote(VoteSite.java:121)
[22:55:02 WARN]: at com.Ben12345rocks.VotingPlugin.Objects.VoteSite.broadcastVote(VoteSite.java:107)
[22:55:02 WARN]: at com.Ben12345rocks.VotingPlugin.Listeners.PlayerVoteListener.onplayerVote(PlayerVoteListener.java:104)
[22:55:02 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor389.execute(Unknown Source)
[22:55:02 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[22:55:02 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[22:55:02 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[22:55:02 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)
[22:55:02 WARN]: at com.Ben12345rocks.VotingPlugin.Listeners.VotiferEvent$2.run(VotiferEvent.java:109)
[22:55:02 WARN]: at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[22:55:02 WARN]: at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[22:55:02 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:55:02 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[22:55:02 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[22:55:02 WARN]: at java.lang.Thread.run(Thread.java:748)
```

UseBungeecoord: true

**Comment by BenCodez** [comment]
The main ideas is that you don't need to forward the vote. VotingPlugin is suppose to handle it (which it does, it's just not instant, the broadcast is still WIP). Currently working on it more, but that looks like something went wrong with the build, resetting my vps soon, so that will fix that I think

Here is a build directly from dropbox.
https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by BenCodez** [comment]
Incase you read it already, I managed to test it locally and got it to work for me. Just need this build :)

https://www.dropbox.com/s/zyt6bfllm73n6wb/VotingPlugin.jar?dl=0

**Comment by BenCodez** [comment]
Have you tried the latest version?

**Comment by x1p** [comment]
I'm sorry, I haven't tested further. I am quite busy. I'll pick it up asap

**Comment by BenCodez** [comment]
No rush, just wondering.

**Comment by x1p** [comment]
Quick test on Bungee (WF actually):
```
[22:58:52 INFO] [com.Ben12345rocks.VotingPlugin.AdvancedCore.hikari.HikariDataSource]: HikariPool-1 - Starting...
[22:58:53 INFO] [com.Ben12345rocks.VotingPlugin.AdvancedCore.hikari.HikariDataSource]: HikariPool-1 - Start completed.
[22:58:53 INFO]: VotingPlugin: Encryption/Decrypted failed: This is a classified message!
[22:58:53 ERROR]: java.net.BindException: Cannot assign requested address (Bind failed)
[22:58:53 ERROR]: at java.net.PlainSocketImpl.socketBind(Native Method)
[22:58:53 ERROR]: at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
[22:58:53 ERROR]: at java.net.ServerSocket.bind(ServerSocket.java:375)
[22:58:53 ERROR]: at java.net.ServerSocket.bind(ServerSocket.java:329)
[22:58:53 ERROR]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sockets.SocketServer.<init>(SocketServer.java:34)
[22:58:53 ERROR]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sockets.SocketHandler$1.<init>(SocketHandler.java:20)
[22:58:53 ERROR]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sockets.SocketHandler.<init>(SocketHandler.java:20)
[22:58:53 ERROR]: at com.Ben12345rocks.VotingPlugin.bungee.Bungee.onEnable(Bungee.java:69)
[22:58:53 ERROR]: at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:283)
[22:58:53 ERROR]: at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281)
[22:58:53 ERROR]: at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
[22:58:53 ERROR]: at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) 
```

**Comment by BenCodez** [comment]
You need a port that's available.

**Comment by x1p** [comment]
It turns out, it needs to listen to the address 0.0.0.0 instead of the docker IP address.
Now it's binding apparently, because there are no startup errors.
Vote arrives, and this appears.
```
[23:52:19 ERROR]: java.lang.IllegalArgumentException: Illegal base64 character 25
[23:52:19 ERROR]: at java.util.Base64$Decoder.decode0(Base64.java:714)
[23:52:19 ERROR]: at java.util.Base64$Decoder.decode(Base64.java:526)
[23:52:19 ERROR]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Encryption.EncryptionHandler.decrypt(EncryptionHandler.java:107)
[23:52:19 ERROR]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sockets.SocketServer.run(SocketServer.java:60)
[23:52:19 ERROR]: java.lang.NullPointerException
[23:52:19 ERROR]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sockets.SocketServer.run(SocketServer.java:61)
```
So I tried the nuvotifier forwarding to none, and now the vote does not give an error, but nothing seems to happen with the vote. So I'm still a bit puzzled how the connection is made between nuvotifier and the votingplugin on bungee.

**Comment by BenCodez** [comment]
Are you using latest spigot build or dev build?
Dev build requires secretkey.key file to be same across every server, it's for encryption.

You can use /votingpluginbungee vote (name) (site) to test as well.
