### ISSUE TITLE
[VotingPlugin] Error in console - Low Priority

### ISSUE THREAD

**Issue by QuindecimTT** [BenCodez/VotingPlugin#700]
![1132131](https://user-images.githubusercontent.com/61077692/74584636-a59c4680-4fa2-11ea-8e3e-56314645502c.PNG)
**Plugin Version**: 5.20.6 
**Spigot version**: 1.15.2

I can't find to what config this issue belongs to, which is why I am here. The error code in the console was vague. This is all I have to go on. If there is other information required, I believe the attached .log will suffice. It is my latest log after installing .jar, starting and then stopping. No further starts have been attempted, yet. This is the VotingPlugins first deployment in the server.

Below is the error code that popped up. While not TOO important, I'd like to fix this to rid my logs and console of issues. I can see it has something to do with the time change event, but alas I can't find where as all the available configs reference timing in one way or another. I looked up Timer-2 and found nothing, and I also looked up Fake and found few relevant pieces of information. Hopefully someone can shed some light into what this is. I _just_ downloaded this .jar, so I don't believe it was me who did this. Perhaps this is a bug? Anyways, here's the code:

`[07:15:53] [Timer-2/INFO]: [VotingPlugin] Time change event: MONTH, Fake: false
[07:15:53] [Timer-2/WARN]: Exception in thread "Timer-2" 
[07:15:53] [Timer-2/WARN]: java.lang.IllegalStateException: PreDateChangedEvent cannot be
triggered asynchronously from primary server thread.
[07:15:53] [Timer-2/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:506)
[07:15:53] [Timer-2/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.TimeChecker.TimeChecker.forceChanged(TimeChecker.java:55)
[07:15:53] [Timer-2/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.TimeChecker.TimeChecker.update(TimeChecker.java:195)
[07:15:53] [Timer-2/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.TimeChecker.TimeChecker$1.run(TimeChecker.java:148)
[07:15:53] [Timer-2/WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[07:15:53] [Timer-2/WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:506)`

Also, I am aware the attached log has other errors. They've been fixed. I'm currently updating all plugins. Everything, aside from this posted issue, has been resolved. Also, there are NO vote sites set up, yet. As a note, I have superBvote also installed (but will soon be removed), as well as nuVotifier. Vault and ProtocolLib are also up-to-date. Actually, all plugins are up-to-date aside from legacy plugins which have no available update (while remaining without erros). 

Added screenshot as the format wasn't saved ^^

[QuindecimLATESTLOG.log](https://github.com/Ben12345rocks/VotingPlugin/files/4207913/QuindecimLATESTLOG.log)
[1132131](https://user-images.githubusercontent.com/61077692/74584636-a59c4680-4fa2-11ea-8e3e-56314645502c.PNG)

**Comment by BenCodez** [comment]
I think this should help:
http://ben12345rocks.com/job/VotingPlugin/

**Comment by QuindecimTT** [comment]
Can confirm - The new update did indeed fix it.
