### ISSUE TITLE
A few errors and questions.

### ISSUE THREAD

**Issue by ZandercraftGames** [BenCodez/VotingPlugin#723]
**Versions**
- git-Paper-129 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
- VotingPlugin

**Describe the bug**
An error is occuring when stopping the server.

**To Reproduce**
1. Start server with plugin
2. Configure the use of bungee
3. Stop server

**Expected behavior**
No errors on disabling plugin

**Console Errors**
```
14:13:29 INFO]: [VotingPlugin] Disabling VotingPlugin v5.20.7
[14:13:29 INFO]: [VotingPlugin] Shutting down mysql, query size: 0
[14:13:29 ERROR]: Error occurred while disabling VotingPlugin v5.20.7 (Is it up to date?)
java.lang.NullPointerException: null
at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sockets.ClientHandler.stopConnection(ClientHandler.java:51) ~[?:?]
at com.Ben12345rocks.VotingPlugin.BungeeHandler.close(BungeeHandler.java:36) ~[?:?]
at com.Ben12345rocks.VotingPlugin.Main.onUnLoad(Main.java:1013) ~[?:?]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCorePlugin.onDisable(AdvancedCorePlugin.java:733) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.2.jar:git-Paper-129]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:372) ~[patched_1.15.2.jar:git-Paper-129]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:468) ~[patched_1.15.2.jar:git-Paper-129]
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:454) ~[patched_1.15.2.jar:git-Paper-129]
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:447) ~[patched_1.15.2.jar:git-Paper-129]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.disablePlugins(CraftServer.java:404) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:742) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:752) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:974) ~[patched_1.15.2.jar:git-Paper-129]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[14:13:29 WARN]: java.net.SocketException: Socket closed
[14:13:29 WARN]: at java.net.PlainSocketImpl.socketAccept(Native Method)
[14:13:29 WARN]: at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
[14:13:29 WARN]: at java.net.ServerSocket.implAccept(ServerSocket.java:545)
[14:13:29 WARN]: at java.net.ServerSocket.accept(ServerSocket.java:513)
[14:13:29 WARN]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sockets.SocketServer.run(SocketServer.java:56)
```

Also another error on startup:
```
[14:13:55 INFO]: [VotingPlugin] Giving VotingPlugin.Player permission by default, can be disabled in the config
[14:13:55 ERROR]: [VotingPlugin] Plugin VotingPlugin v5.20.7 has failed to register events for class com.Ben12345rocks.VotingPlugin.Listeners.VotiferEvent because com/vexsoftware/votifier/model/VotifierEvent does not exist.
[14:13:55 INFO]: [VotingPlugin] Enabled VotingPlugin 5.20.7
```

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Should fix all of that.

**Comment by ZandercraftGames** [comment]
@Ben12345rocks In the latest version you linked, the following error occurs:
```
[22:29:39 INFO]: [VotingPlugin] Enabling VotingPlugin v5.20.7
[22:29:39 WARN]: [VotingPlugin] Detected no voting sites, this may mean something isn't properly setup
[22:29:39 WARN]: [VotingPlugin] Loaded class com.comphenix.protocol.events.PacketListener from ProtocolLib v4.5.0 which is not a depend, softdepend or loadbefore of this plugin.
[22:29:39 INFO]: [com.Ben12345rocks.VotingPlugin.AdvancedCore.hikari.HikariDataSource] HikariPool-1 - Starting...
[22:29:39 INFO]: [com.Ben12345rocks.VotingPlugin.AdvancedCore.hikari.HikariDataSource] HikariPool-1 - Start completed.
[22:29:39 INFO]: VotingPlugin: Encryption/Decrypted failed: This is a classified message!
[22:29:39 INFO]: [VotingPlugin] Giving VotingPlugin.Player permission by default, can be disabled in the config
[22:29:39 ERROR]: [VotingPlugin] Plugin VotingPlugin v5.20.7 has failed to register events for class com.Ben12345rocks.VotingPlugin.Listeners.VotiferEvent because com/vexsoftware/votifier/model/VotifierEvent does not exist.
[22:29:39 INFO]: [VotingPlugin] Enabled VotingPlugin 5.20.7
```

**Comment by ZandercraftGames** [comment]
And this when stopping server:
```
[22:33:00 INFO]: [VotingPlugin] Disabling VotingPlugin v5.20.7
[22:33:00 INFO]: [VotingPlugin] Shutting down mysql, query size: 0
[22:33:00 WARN]: java.net.SocketException: Socket closed
[22:33:00 WARN]: at java.net.PlainSocketImpl.socketAccept(Native Method)
[22:33:00 WARN]: at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
[22:33:00 WARN]: at java.net.ServerSocket.implAccept(ServerSocket.java:545)
[22:33:00 WARN]: at java.net.ServerSocket.accept(ServerSocket.java:513)
[22:33:00 WARN]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sockets.SocketServer.run(SocketServer.java:56)
```

**Comment by ZandercraftGames** [comment]
And on bungeecord:
```
[22:38:16 INFO] [com.Ben12345rocks.VotingPlugin.AdvancedCore.hikari.HikariDataSource]: HikariPool-1 - Starting...
[22:38:16 INFO] [com.Ben12345rocks.VotingPlugin.AdvancedCore.hikari.HikariDataSource]: HikariPool-1 - Start completed.
[22:38:16 INFO]: VotingPlugin: Encryption/Decrypted failed: This is a classified message!
[22:38:16 ERROR]: java.net.BindException: Cannot assign requested address (Bind failed)
[22:38:16 ERROR]: at java.net.PlainSocketImpl.socketBind(Native Method)
[22:38:16 ERROR]: at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
[22:38:16 ERROR]: at java.net.ServerSocket.bind(ServerSocket.java:375)
[22:38:16 ERROR]: at java.net.ServerSocket.bind(ServerSocket.java:329)
[22:38:16 ERROR]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sockets.SocketServer.<init>(SocketServer.java:34)
[22:38:16 ERROR]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sockets.SocketHandler$1.<init>(SocketHandler.java:20)
[22:38:16 ERROR]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sockets.SocketHandler.<init>(SocketHandler.java:20)
[22:38:16 ERROR]: at com.Ben12345rocks.VotingPlugin.bungee.Bungee.onEnable(Bungee.java:69)
[22:38:16 ERROR]: at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:285)
[22:38:16 ERROR]: at net.md_5.bungee.BungeeCord.start(BungeeCord.java:288)
[22:38:16 ERROR]: at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
[22:38:16 ERROR]: at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[22:38:16 INFO]: Enabled plugin VotingPlugin version 5.20.7 by Ben12345rocks
```

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

That should take care of the first two.

The last error is on your end:
java.net.BindException: Cannot assign requested address (Bind failed)

**Comment by ZandercraftGames** [comment]
Now the following errors occur.
At startup:
```
[00:10:08 INFO]: [VotingPlugin] Enabling VotingPlugin v5.20.7
[00:10:08 WARN]: [VotingPlugin] Detected no voting sites, this may mean something isn't properly setup
[00:10:08 INFO]: [com.Ben12345rocks.VotingPlugin.AdvancedCore.hikari.HikariDataSource] HikariPool-1 - Starting...
[00:10:08 INFO]: [com.Ben12345rocks.VotingPlugin.AdvancedCore.hikari.HikariDataSource] HikariPool-1 - Start completed.
[00:10:08 INFO]: [VotingPlugin] Giving VotingPlugin.Player permission by default, can be disabled in the config
[00:10:08 ERROR]: [VotingPlugin] Plugin VotingPlugin v5.20.7 has failed to register events for class com.Ben12345rocks.VotingPlugin.Listeners.VotiferEvent because com/vexsoftware/votifier/model/VotifierEvent does not exist.
[00:10:08 INFO]: [VotingPlugin] Enabled VotingPlugin 5.20.7
```

And at stop:
```
[00:10:53 INFO]: [VotingPlugin] Disabling VotingPlugin v5.20.7
[00:10:53 INFO]: [VotingPlugin] Shutting down mysql, query size: 0
[00:10:53 WARN]: java.net.SocketException: Socket closed
[00:10:53 WARN]: at java.net.PlainSocketImpl.socketAccept(Native Method)
[00:10:53 WARN]: at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
[00:10:53 WARN]: at java.net.ServerSocket.implAccept(ServerSocket.java:545)
[00:10:53 WARN]: at java.net.ServerSocket.accept(ServerSocket.java:513)
[00:10:53 WARN]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sockets.SocketServer.run(SocketServer.java:56)
[00:10:53 INFO]: [ProtocolLib] Disabling ProtocolLib v4.5.0
```

**Comment by BenCodez** [comment]
You can ignore the last error, it won't break anything, but this should get rid of it:
http://ben12345rocks.com/job/VotingPlugin/

**Comment by ZandercraftGames** [comment]
Thanks man! 😄

**Comment by ZandercraftGames** [comment]
The bind to address issue didnt occur before the update to the version you supplied. I cannot find anything on my end that would be causing this. Nothing changed except for the jar file.

**Comment by BenCodez** [comment]
I didn't change anything that would effect that.

**Comment by ZandercraftGames** [comment]
Would you have in the past month? I dont think there would be anything else running on the server on that part. It also seems it enables twice... Might that contribute to the issue?

**Comment by BenCodez** [comment]
I changed nothing since the latest spigot build regarding that. What do you mean by enabled twice?

**Comment by ZandercraftGames** [comment]
Nevermind. It loads then enables.

**Comment by ZandercraftGames** [comment]
```
BungeeServer:
  Host: '172.18.0.1'
  Port: 1297
```
This is it's configuration. That port is forwarded and allowed through the firewall. It worked before, so I dont see what would be causing issues here.

**Comment by ZandercraftGames** [comment]
![image](https://user-images.githubusercontent.com/28664144/76692483-cc937a00-662d-11ea-89c6-1c7124b3b3f6.png)
Running `ufw allow 1297` results in this:
```
Skipping adding existing rule
Skipping adding existing rule (v6)
```

**Comment by BenCodez** [comment]
Maybe try a new port? It can't bind to the ip/port for whatever reason

**Comment by ZandercraftGames** [comment]
```
tcp        0      0 172.18.0.1:1297         0.0.0.0:*               LISTEN      5277/docker-proxy
udp        0      0 172.18.0.1:1297         0.0.0.0:*                           5290/docker-proxy
```
It seems the docker proxy service (a.k.a. the server) is listening on that port, but the plugin reports it cannot.

**Comment by BenCodez** [comment]
Force kill the server and restart? I honestly have no idea right now, since if it was broken it would be on all servers, it uses the exact same API.

**Comment by ZandercraftGames** [comment]
Hmm. Because it seems to only fail on the bungee server. Not on the individual spigot servers of the network.

**Comment by ZandercraftGames** [comment]
When I stop the server it unbinds that port.
```
zander@[REDACTED]:~$ sudo netstat -pnltu | grep -i "1297"
zander@[REDACTED]:~$
```

**Comment by BenCodez** [comment]
I guess try another port if you got no idea.

**Comment by ZandercraftGames** [comment]
```
[01:09:03 INFO] [com.Ben12345rocks.VotingPlugin.AdvancedCore.hikari.HikariDataSource]: HikariPool-1 - Starting...
[01:09:03 INFO] [com.Ben12345rocks.VotingPlugin.AdvancedCore.hikari.HikariDataSource]: HikariPool-1 - Start completed.
[01:09:03 ERROR]: java.net.BindException: Cannot assign requested address (Bind failed)
[01:09:03 ERROR]: at java.net.PlainSocketImpl.socketBind(Native Method)
[01:09:03 ERROR]: at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
[01:09:03 ERROR]: at java.net.ServerSocket.bind(ServerSocket.java:375)
[01:09:03 ERROR]: at java.net.ServerSocket.bind(ServerSocket.java:329)
[01:09:03 ERROR]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sockets.SocketServer.<init>(SocketServer.java:35)
[01:09:03 ERROR]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sockets.SocketHandler$1.<init>(SocketHandler.java:20)
[01:09:03 ERROR]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sockets.SocketHandler.<init>(SocketHandler.java:20)
[01:09:03 ERROR]: at com.Ben12345rocks.VotingPlugin.bungee.Bungee.onEnable(Bungee.java:69)
[01:09:03 ERROR]: at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:285)
[01:09:03 ERROR]: at net.md_5.bungee.BungeeCord.start(BungeeCord.java:288)
[01:09:03 ERROR]: at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
[01:09:03 ERROR]: at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```
Same issue when binding to port 1298.
For some reason its still binding to 1297 when the config is set to 1298

**Comment by ZandercraftGames** [comment]
My config in case you were wondering:
```
# STILL A WORK IN PROGRESS, USE AT YOUR OWN RISK
# 
# Set bungeecoord to true on servers on the network
# Set server name in each server related to what it is on bungee
#
# Have a reward on each server
SendVotesToAllServers: false
# Have a reward on 1 server on the network
SendToOnlineServer: true
# Tell servers to broadcast
Broadcast: true
# List of servers the plugin won't send the vote to
BlockedServers: []
FallBackServer: lobby

# Bungee communication, Add this to each spigot server
BungeeServer:
  Host: '172.18.0.1'
  Port: 1298
  
# Bungee communication, add each spigot server here
SpigotServers:
  lobby:
    Host: '172.18.0.1'
    Port: 1302
  tempsurvival:
    Host: '172.18.0.1'
    Port: 1301
  smp:
    Host: '172.18.0.1'
    Port: 1303
  sg-01:
    Host: '172.18.0.1'
    Port: 1304
  uhc:
    Host: '172.18.0.1'
    Port: 1305
```

**Comment by BenCodez** [comment]
Yeah I got nothing.

**Comment by ZandercraftGames** [comment]
Okay. Thanks anyways

**Comment by ZandercraftGames** [comment]
Have you set it up to use an external system to contact it? Because it works now that I set it to be publicly facing. That does however not seem like a very good idea. What is transmitted over that port? Anything sensitive?

**Comment by BenCodez** [comment]
Nothing sensitive and it's encrypted. Just for the server to check from the mysql table that a vote came through.

**Comment by ZandercraftGames** [comment]
In what way? The rsa secret key in the folder? Also, would it provide any form of an entrypoint into the sql database? Another thing, do I need to make all of the spigot servers have the same key in the secretkey file?

**Comment by BenCodez** [comment]
the secretkey.key file in VotingPlugin.

It does not provide any possible way to provide any sort of entry into any data. It just sends a message saying this player voted and to check said player on mysql data.

The encryption was just an extra layer I added, so no one could use this by any means.

Check the code yourself if you want.
https://github.com/Ben12345rocks/AdvancedCore/tree/master/AdvancedCore/src/com/Ben12345rocks/AdvancedCore/Util/Encryption

You can all the data that is sent here:
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/src/com/Ben12345rocks/VotingPlugin/bungee/Bungee.java#L67

And yes, all servers need the same key file.

**Comment by ZandercraftGames** [comment]
Okay thank you.
