### ISSUE TITLE
Out of the blue stopped working, nothing changed in years.

### ISSUE THREAD

**Issue by TomLewis** [BenCodez/VotingPlugin#739]
**Versions**
5.13.6
Paper 1.12.2

**Describe the bug**
Voting has been working perfectly fine for over a year since I installed VotingPlugin, out of the blue, its just randomly stopped working.
Theres been no changes to my MySQL, no changes to the configs, no changes to the Votifier, no changes to the open ports, nothing, it just randomly started spitting out this when people vote.

MySQL is on the same localhost.

```

[15:59:36] [Craft Scheduler Thread - 1811/WARN]: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
[15:59:36] [Craft Scheduler Thread - 1811/WARN]: 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:666)
[15:59:36] [Craft Scheduler Thread - 1811/WARN]: 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:182)
[15:59:36] [Craft Scheduler Thread - 1811/WARN]: 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
[15:59:36] [Craft Scheduler Thread - 1811/WARN]: 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
[15:59:36] [Craft Scheduler Thread - 1811/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.api.ConnectionManager.getConnection(ConnectionManager.java:80)
[15:59:36] [Craft Scheduler Thread - 1811/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.api.queries.Query.<init>(Query.java:20)
[15:59:36] [Craft Scheduler Thread - 1811/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.getColumnsQueury(MySQL.java:249)
[15:59:36] [Craft Scheduler Thread - 1811/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.loadData(MySQL.java:431)
[15:59:36] [Craft Scheduler Thread - 1811/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.getColumns(MySQL.java:241)
[15:59:36] [Craft Scheduler Thread - 1811/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.checkColumn(MySQL.java:179)
[15:59:36] [Craft Scheduler Thread - 1811/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.update(MySQL.java:464)
[15:59:36] [Craft Scheduler Thread - 1811/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.UserData.setString(UserData.java:246)
[15:59:36] [Craft Scheduler Thread - 1811/WARN]: 	at com.Ben12345rocks.VotingPlugin.Objects.User.setReminded(User.java:718)
[15:59:36] [Craft Scheduler Thread - 1811/WARN]: 	at com.Ben12345rocks.VotingPlugin.VoteReminding.VoteReminding.runRemindLogin(VoteReminding.java:121)
[15:59:36] [Craft Scheduler Thread - 1811/WARN]: 	at com.Ben12345rocks.VotingPlugin.Objects.User.loginMessage(User.java:524)
[15:59:36] [Craft Scheduler Thread - 1811/WARN]: 	at com.Ben12345rocks.VotingPlugin.Events.PlayerJoinEvent$1.run(PlayerJoinEvent.java:58)
[15:59:36] [Craft Scheduler Thread - 1811/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[15:59:36] [Craft Scheduler Thread - 1811/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[15:59:36] [Craft Scheduler Thread - 1811/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:59:36] [Craft Scheduler Thread - 1811/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[15:59:36] [Craft Scheduler Thread - 1811/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[15:59:36] [Craft Scheduler Thread - 1811/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[15:59:36] [Craft Scheduler Thread - 1811/WARN]: [VotingPlugin] Plugin VotingPlugin v5.13.6 generated an exception while executing task 1694743
java.lang.NullPointerException: null
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.api.queries.Query.<init>(Query.java:21) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.getColumnsQueury(MySQL.java:249) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.loadData(MySQL.java:431) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.getColumns(MySQL.java:241) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.checkColumn(MySQL.java:179) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.update(MySQL.java:464) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.UserData.setString(UserData.java:246) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Objects.User.setReminded(User.java:718) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.VoteReminding.VoteReminding.runRemindLogin(VoteReminding.java:121) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Objects.User.loginMessage(User.java:524) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Events.PlayerJoinEvent$1.run(PlayerJoinEvent.java:58) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1617]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1617]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[15:59:36] [Craft Scheduler Thread - 1777/WARN]: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
[15:59:36] [Craft Scheduler Thread - 1777/WARN]: 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:666)
[15:59:36] [Craft Scheduler Thread - 1777/WARN]: 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:182)
[15:59:36] [Craft Scheduler Thread - 1777/WARN]: 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
[15:59:36] [Craft Scheduler Thread - 1777/WARN]: 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
[15:59:36] [Craft Scheduler Thread - 1777/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.api.ConnectionManager.getConnection(ConnectionManager.java:80)
[15:59:36] [Craft Scheduler Thread - 1777/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.api.queries.Query.<init>(Query.java:20)
[15:59:36] [Craft Scheduler Thread - 1777/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.getExactQuery(MySQL.java:280)
[15:59:36] [Craft Scheduler Thread - 1777/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.loadPlayer(MySQL.java:442)
[15:59:36] [Craft Scheduler Thread - 1777/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.loadPlayerIfNeeded(MySQL.java:451)
[15:59:36] [Craft Scheduler Thread - 1777/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.mysql.MySQL.getExact(MySQL.java:270)
[15:59:36] [Craft Scheduler Thread - 1777/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.UserData.getMySqlRow(UserData.java:108)
[15:59:36] [Craft Scheduler Thread - 1777/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.UserData.getString(UserData.java:133)
[15:59:36] [Craft Scheduler Thread - 1777/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.UserData.getBoolean(UserData.java:22)
[15:59:36] [Craft Scheduler Thread - 1777/WARN]: 	at com.Ben12345rocks.VotingPlugin.Objects.User.getDisableBroadcast(User.java:180)
[15:59:36] [Craft Scheduler Thread - 1777/WARN]: 	at com.Ben12345rocks.VotingPlugin.Objects.VoteSite.broadcastVote(VoteSite.java:100)
[15:59:36] [Craft Scheduler Thread - 1777/WARN]: 	at com.Ben12345rocks.VotingPlugin.Events.VotiferEvent.playerVote(VotiferEvent.java:82)
[15:59:36] [Craft Scheduler Thread - 1777/WARN]: 	at com.Ben12345rocks.VotingPlugin.Events.VotiferEvent$2.run(VotiferEvent.java:198)
[15:59:36] [Craft Scheduler Thread - 1777/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[15:59:36] [Craft Scheduler Thread - 1777/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[15:59:36] [Craft Scheduler Thread - 1777/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:59:36] [Craft Scheduler Thread - 1777/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[15:59:36] [Craft Scheduler Thread - 1777/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[15:59:36] [Craft Scheduler Thread - 1777/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[15:59:36] [Craft Scheduler Thread - 1777/WARN]: [VotingPlugin] Plugin VotingPlugin v5.13.6 generated an exception while executing task 1652027
java.lang.NullPointerException: null
```

**Comment by BenCodez** [comment]
Isn't anything I can do since your not running the latest vesion.

**Comment by TomLewis** [comment]
> 
> 
> Isn't anything I can do since your not running the latest vesion.

I cant, the latest version does not run on 1.12.2

**Comment by BenCodez** [comment]
Exactly....

**Comment by TomLewis** [comment]
> 
> Exactly....

You should support 1.12.2, 1.13+ has terrible performance for hosting a server, thousands of people still use 1.12.2.

On another note, why would this break after working for years? It randomly stopped working, and sometimes it will just work again, can you explain what the issue is its happening, it looks like its struggling to connect to the MySQL but no other plugin is having issues with connecting to MySQL.

Even things like this already exist
https://github.com/CryptoMorin/XSeries


https://github.com/CryptoMorin/XSeries/blob/master/src/main/java/com/cryptomorin/xseries/XMaterial.java

**Comment by BenCodez** [comment]
Why should I waste time supporting older versions? Not happening.

On why mysql broke, I got no idea.
