### ISSUE TITLE
Bind Address Failing

### ISSUE THREAD

**Issue by StormyIceLeopard** [BenCodez/VotingPlugin#825]
**Versions**
[13:00:20 INFO]: This server is running Paper version git-Paper-327 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[13:00:44 INFO]: VotingPlugin version 5.21.3
[13:00:44 INFO]: Highly Customizable Voting Listener!
[13:00:44 INFO]: Website: https://www.spigotmc.org/resources/votingplugin.15358/
[13:00:44 INFO]: Author: Ben12345rocks

**Relevant information**
Spigot
# --------------------------
# Bungee Setup 
# Only if using votingplugin bungee to send votes
# REQUIRES RESTART FOR CHANGES TO TAKE EFFECT
# --------------------------

# Plugin using bungee, requires plugin on bungee server
UseBungeecoord: true

# Get the plugin to broadcast to all servers
BungeeBroadcast: true

# What server this is in bungee (must match)
# Also can be applied to rewards
Server: Lobby

# Bungee communication, add bungee host/port here
BungeeServer:
  Host: '192.168.1.105'
  Port: 1297
  
# Bungee communication, add this to bungee server
SpigotServer:
  Host: '172.18.0.1'
  Port: 5566

Bungee
# Bungee communication, Add this to each spigot server
BungeeServer:
  Host: '192.168.1.105'
  Port: 1297
  
# Bungee communication, add each spigot server here
SpigotServers:
  Lobby:
    Host: '172.18.0.1'
    Port: 5566
  SMP:
    Host: '172.18.0.1'
    Port: 5567
  NeoTNT:
    Host: '172.18.0.1'
    Port: 5570
  BomBrigaders:
    Host: '172.18.0.1'
    Port: 5571

**Context**
Getting the following error on both Bungee and Spigot

[12:46:12 WARN]: java.net.BindException: Cannot assign requested address (Bind failed)
[12:46:12 WARN]: at java.net.PlainSocketImpl.socketBind(Native Method)
[12:46:12 WARN]: at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
[12:46:12 WARN]: at java.net.ServerSocket.bind(ServerSocket.java:390)
[12:46:12 WARN]: at java.net.ServerSocket.bind(ServerSocket.java:344)
[12:46:12 WARN]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sockets.SocketServer.<init>(SocketServer.java:35)
[12:46:12 WARN]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sockets.SocketHandler$1.<init>(SocketHandler.java:20)
[12:46:12 WARN]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sockets.SocketHandler.<init>(SocketHandler.java:20)
[12:46:12 WARN]: at com.Ben12345rocks.VotingPlugin.BungeeHandler.load(BungeeHandler.java:118)
[12:46:12 WARN]: at com.Ben12345rocks.VotingPlugin.Main.onPostLoad(Main.java:779)
[12:46:12 WARN]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCorePlugin.onEnable(AdvancedCorePlugin.java:742)
[12:46:12 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[12:46:12 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[12:46:12 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[12:46:12 WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472)
[12:46:12 WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386)
[12:46:12 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488)
[12:46:12 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
[12:46:12 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:900)
[12:46:12 WARN]: at java.lang.Thread.run(Thread.java:748)

Can you please help me?

**Comment by BenCodez** [comment]
java.net.BindException: Cannot assign requested address (Bind failed)

Something is preventing it from binding.

**Comment by StormyIceLeopard** [comment]
I am using pterodactyl
Waterfall: 192.168.1.105:1297
Lobby: 172.18.0.1:5566

I am unable to debug why it is not binding

**Comment by BenCodez** [comment]
No idea, I know it works on pterodactyl, as others I've help got it to work. Just needs to be setup correctly.

**Comment by StormyIceLeopard** [comment]
IP of Physical PC: 192.168.1.105 (local IP)
IP that waterfall uses: 0.0.0.0:25565 (from config.yml)
IP that Lobby uses: 0.0.0.0:25566 (from server.properties)
IP that Paper uses for serverselector: 172.18.0.1:PORT (Uses for plugins between all paper servers communicate)

If you got any ideas where I should start, I am all ears.

**Comment by BenCodez** [comment]
Use the local ip of the pc? or set it all to localhost? You need to use an ip that the server can bind to.

**Comment by StormyIceLeopard** [comment]
I am unable to get the IP off 0.0.0.0 (I even tried modifying the eggs to no luck)
And what I do not understand is why Lobby can talk to SMP and NeoTNT but Lobby cannot talk to Waterfall.

**Comment by BenCodez** [comment]
There isn't much I can do other than recommend using other ips

**Comment by StormyIceLeopard** [comment]
Okay, I will keep messing around. I will either post again or close this issue.

**Comment by StormyIceLeopard** [comment]
For kicks and grins, I set the IP to 0.0.0.0 in the config and the port binded. lol
Now I have a new issue
[13:28:19 WARN]: [VotingPlugin] No vote has been recieved from PlanetMinecraft.com, may be an invalid service site. Vote on the site and look in console for a service site, if you get nothing then there is an issue with votifier
[13:28:19 WARN]: [VotingPlugin] No vote has been recieved from MinecraftServers.org, may be an invalid service site. Vote on the site and look in console for a service site, if you get nothing then there is an issue with votifier
[13:28:19 WARN]: [VotingPlugin] No vote has been recieved from Minecraft-Server.net, may be an invalid service site. Vote on the site and look in console for a service site, if you get nothing then there is an issue with votifier
[13:28:19 WARN]: [VotingPlugin] No vote has been recieved from TOPG.org, may be an invalid service site. Vote on the site and look in console for a service site, if you get nothing then there is an issue with votifier
[13:28:19 WARN]: [VotingPlugin] No vote has been recieved from MinecraftList.org, may be an invalid service site. Vote on the site and look in console for a service site, if you get nothing then there is an issue with votifier
[13:28:19 WARN]: [VotingPlugin] No vote has been recieved from MineMen.com, may be an invalid service site. Vote on the site and look in console for a service site, if you get nothing then there is an issue with votifier
[13:28:19 WARN]: [VotingPlugin] No vote has been recieved from Minecraft-MP.com, may be an invalid service site. Vote on the site and look in console for a service site, if you get nothing then there is an issue with votifier
[13:28:19 WARN]: [VotingPlugin] No vote has been recieved from Minecraft-Server-list.com, may be an invalid service site. Vote on the site and look in console for a service site, if you get nothing then there is an issue with votifier

I understand the rest might be wrong but I know that PlanetMinecraft is correct, I voted myself to confirm, and it still does that. Any suggestions?

**Comment by BenCodez** [comment]
Just do a vote. Will go away once the server gets a vote.

Does the server get the vote?
/votingpluginbungee vote (name) (site) work?

**Comment by StormyIceLeopard** [comment]
I did two of them. Both times got "Sending Vote" followed by nothing. Did this in Waterfall console.

**Comment by BenCodez** [comment]
Same secret.key file across servers? Everything else setup from here? https://github.com/Ben12345rocks/VotingPlugin/wiki/Bungeecoord-Setups

**Comment by StormyIceLeopard** [comment]
oh, probably not. Assuming I need to copy the proxy one to the spigot ones.
Yes, followed the first method.

**Comment by BenCodez** [comment]
Doesn't matter which file, just the same across all servers

**Comment by StormyIceLeopard** [comment]
>.... [13:47:15 INFO] [VotingPlugin]: Vote received StormyIceLeopard from service site Minemen.com (From Waterfall)
Nothing happened in Lobby. /vote today results in nothing.
Same secret.key

Is there a command to check if the plugin on bungee/waterfall is communicating with the plugin on Spigot/Paper? Like /votingplugin status

**Comment by BenCodez** [comment]
/votingpluginbungee vote (name) (site) - if that doesn't work then something is wrong.

**Comment by StormyIceLeopard** [comment]
Sadly that does not work. What is supposed to happen?

**Comment by BenCodez** [comment]
Are you connected to the server when you do that?

**Comment by StormyIceLeopard** [comment]
No, I will try while in Lobby. Still nothing

**Comment by BenCodez** [comment]
Did you restart the servers after everything?

**Comment by StormyIceLeopard** [comment]
I have. I think you are right. It is because the server IP is 0.0.0.0
But if I change it from 0.0.0.0 then the server is unjoinable.
I am just going to have to settle once again to have voting just on Lobby.

I appreciate all your help, thank you.
