### ISSUE TITLE
InterruptedException: sleep interrupted on shutdown

### ISSUE THREAD

**Issue by mibby** [BenCodez/VotingPlugin#842]
**Versions**
Paper dev 347
VotingPlugin dev 202

**Relevant information**
```
[10:00:01] [Server thread/INFO]: [VotingPlugin] Disabling VotingPlugin v5.21.3
[10:00:01] [Server thread/INFO]: [VotingPlugin] Shutting down mysql, query size: 0
[10:00:01] [Thread-40/WARN]: java.lang.InterruptedException: sleep interrupted
[10:00:01] [Thread-40/WARN]: 	at java.base/java.lang.Thread.sleep(Native Method)
[10:00:01] [Thread-40/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Thread.Thread$ReadThread.run(Thread.java:33)
[10:00:01] [Thread-63/WARN]: java.lang.InterruptedException: sleep interrupted
[10:00:01] [Thread-63/WARN]: 	at java.base/java.lang.Thread.sleep(Native Method)
[10:00:01] [Thread-63/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Thread.FileThread$ReadThread.run(FileThread.java:92)
```

**Context**
Noticed this exception on shutdown. Caused by this commit?
https://github.com/Ben12345rocks/AdvancedCore/commit/bb9c15834b8b51874d70e97de65e12a5dcf66d8c#diff-7cec5c32714aea117c1c5a1065b34a47R742
https://github.com/Ben12345rocks/AdvancedCore/commit/cfe891db6d9e014eb436d9cf25706b9f561114b0

**Comment by BenCodez** [comment]
Yeah, will fix later today

**Comment by BenCodez** [comment]
Latest dev build should fix it.
