### ISSUE TITLE
Plugin not loading.

### ISSUE THREAD

**Issue by Areez01** [BenCodez/VotingPlugin#868]
**Versions**
Plugin Version: 5.22
Paper: 1.16.1 Lastest build

**Describe the bug**
[14:47:05] [Server thread/INFO]: [VotingPlugin] Enabling VotingPlugin v5.22
[14:47:05] [Server thread/WARN]: [VotingPlugin] Loaded class fr.xephi.authme.events.AuthMeAsyncPreLoginEvent from AuthMe v5.6.0-SNAPSHOT-b2394 which is not a depend, softdepend or loadbefore of this plugin.
[14:47:05] [Server thread/INFO]: [VotingPlugin] Giving VotingPlugin.Player permission by default, can be disabled in the config
[14:47:05] [Server thread/WARN]: [VotingPlugin] Loaded class be.maximvdw.placeholderapi.PlaceholderReplacer from MVdWPlaceholderAPI v3.1.0 which is not a depend, softdepend or loadbefore of this plugin.
[14:47:05] [Server thread/ERROR]: Error occurred while enabling VotingPlugin v5.22 (Is it up to date?)
java.lang.NoSuchMethodError: be.maximvdw.placeholderapi.PlaceholderAPI.registerPlaceholder(Lorg/bukkit/plugin/Plugin;Ljava/lang/String;Lbe/maximvdw/placeholderapi/PlaceholderReplacer;)Z
	at com.Ben12345rocks.VotingPlugin.Util.PlaceHolders.MVdWPlaceholders.loadMVdWPlaceholders(MVdWPlaceholders.java:57) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Main.onPostLoad(Main.java:847) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCorePlugin.onEnable(AdvancedCorePlugin.java:748) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-83]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-83]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-83]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-83]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-83]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-83]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-83]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-83]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-83]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[14:47:05] [Server thread/INFO]: [VotingPlugin] Disabling VotingPlugin v5.22

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Better?
