### ISSUE TITLE
Sometime it works sometimes not

### ISSUE THREAD

**Issue by Cryper** [BenCodez/VotingPlugin#869]
Version 5.22

_What happen:_
I just restart the Server and than the server wont Start cause of VP

_Console Log:_ 
[20:50:35] [Server thread/ERROR]: Error occurred while enabling VotingPlugin v5.22 (Is it up to date?)
java.util.MissingResourceException: Can't find bundle for base name com/sun/rowset/RowSetResourceBundle, locale de_DE
	at java.util.ResourceBundle.throwMissingResourceException(Unknown Source) ~[?:1.8.0_251]
	at java.util.ResourceBundle.getBundleImpl(Unknown Source) ~[?:1.8.0_251]
	at java.util.ResourceBundle.getBundle(Unknown Source) ~[?:1.8.0_251]
	at com.sun.rowset.JdbcRowSetResourceBundle.<init>(Unknown Source) ~[?:1.8.0_251]
	at com.sun.rowset.JdbcRowSetResourceBundle.getJdbcRowSetResourceBundle(Unknown Source) ~[?:1.8.0_251]
	at com.sun.rowset.CachedRowSetImpl.<init>(Unknown Source) ~[?:1.8.0_251]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.api.queries.Query.executeQuery(Query.java:114) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.getRowsQuery(MySQL.java:410) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.getUuidsQuery(MySQL.java:435) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.clearCacheBasic(MySQL.java:225) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserManager.purgeOldPlayers(UserManager.java:206) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCorePlugin.loadHook(AdvancedCorePlugin.java:388) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCorePlugin.onEnable(AdvancedCorePlugin.java:747) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-372]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-372]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-372]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-372]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Paper-372]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[20:50:35] [Server thread/INFO]: [VotingPlugin] Disabling VotingPlugin v5.22
[20:50:35] [Server thread/INFO]: [VotingPlugin] Shutting down mysql, query size: 1

**Comment by BenCodez** [comment]
Try a different java version.

**Comment by Cryper** [comment]
Sorry that i didnt reponse so fast.
Other Java version wont work either

**Comment by BenCodez** [comment]
What java version you try? Someone else said java 11 fixed it.

**Comment by Cryper** [comment]
I tried it with 14 now. dont work.
Will try it with 11 right now

**Comment by BenCodez** [comment]
Well, you can search the error, it says missing module from what I can tell

**Comment by BenCodez** [comment]
Also see if this build helps:
http://ben12345rocks.com/job/VotingPlugin/

**Comment by Cryper** [comment]
I installed Java 11 now its works.

**Comment by BenCodez** [comment]
Hmm. Good to know. I don't have a good way to recreate the problem, so I can't really test.
