### ISSUE TITLE
Please support 1.12.2

### ISSUE THREAD

**Issue by TomLewis** [BenCodez/VotingPlugin#881]
Please support 1.12.2, Some of us are forced to use this version due to Mojangs refusal to fix performance for 40+ online players on later versions of Minecraft, some of the largest servers in the world still use 1.12.2, like 2b2t, please watch this video for a better understanding.

https://www.youtube.com/watch?v=MBpN679o5Yk

Library's designed to help do this;
https://github.com/CryptoMorin/XSeries
https://github.com/CryptoMorin/XSeries/blob/master/src/main/java/com/cryptomorin/xseries/XMaterial.java

Metric data 
https://bstats.org/global/bukkit

12% of all servers still using 1.12.2
13% using below to 1.8.

So 1/4 of all Minecraft servers that exist use below 1.13.

Today I had to disable /vote top as it was crashing my server, im sure this is fixed in newer versions, but I cant upgrade to 1.13+ until Mojang sorts the performance issue with lots of players online.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

I made it so it can run on 1.12, no idea if it works, I think it should, but not every feature.

**Comment by TomLewis** [comment]
> 
> 
> http://ben12345rocks.com/job/VotingPlugin/
> 
> I made it so it can run on 1.12, no idea if it works, I think it should, but not every feature.

Thanks Ben, I will test it on my test server & if theres no errors I will trial it on my production tomorrow morning where it will get some real use!
Thanks!

**Comment by TomLewis** [comment]
After updating all the configs with my changes, it seems to work on 1.12.2, the only error I see so far is at boot:
```
[19:14:21] [Server thread/ERROR]: [VotingPlugin] Plugin VotingPlugin v5.22 has failed to register events for class com.Ben12345rocks.VotingPlugin.Listeners.PlayerCommandSendListener because org/bukkit/event/player/PlayerCommandSendEvent does not exist.
```
And then `/vote top` gives me PLAYER_HEAD error, as Its named differently in 1.13+
```
[19:15:54] [Server thread/INFO]: GodsDead issued server command: /vote top
[19:15:54] [Craft Scheduler Thread - 33/WARN]: [VotingPlugin] Plugin VotingPlugin v5.22 generated an exception while executing task 631
java.lang.NoSuchFieldError: PLAYER_HEAD
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Misc.PlayerUtils.getPlayerSkull(PlayerUtils.java:116) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.User.getPlayerHead(User.java:347) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Commands.GUI.PlayerGUIs.openVoteTop(PlayerGUIs.java:567) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Commands.CommandLoader$79.execute(CommandLoader.java:1839) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.CommandAPI.CommandHandler$1.run(CommandHandler.java:399) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1617]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1617]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[19:16:01] [Timer-10/WARN]: Exception in thread "Timer-10" java.lang.NoSuchFieldError: PLAYER_HEAD
[19:16:01] [Timer-10/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Skull.SkullHandler.getSkull(SkullHandler.java:112)
[19:16:01] [Timer-10/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Skull.SkullThread$ReadThread$2.run(SkullThread.java:81)
[19:16:01] [Timer-10/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Skull.SkullThread$ReadThread.run(SkullThread.java:127)
[19:16:01] [Timer-10/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Skull.SkullThread.run(SkullThread.java:197)
[19:16:01] [Timer-10/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Skull.SkullThread$ReadThread.load(SkullThread.java:77)
[19:16:01] [Timer-10/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Skull.SkullHandler$2.run(SkullHandler.java:174)
[19:16:01] [Timer-10/WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[19:16:01] [Timer-10/WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:506)
```

There was an issue with CLOCK/WATCH names, but I replaced all these in the config.yml and it fixed it, but I cant set the PLAYER_HEAD item.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Disable preloadskulls and loadskulls in the config as well, that's a feature that I guess will be too hard to implement in 1.12 (if it is even possible for it to work)

**Comment by TomLewis** [comment]
Brilliant, I had to rename the stained glass panel this second time.
This now opens the `/vote top` GUI, but its empty, I did copy my SQL lite database from my live to test server, so when I do `/vote Top 1` it does display the top votes in chat, just not showing their heads in the `/vote top` GUI.

Is this because I changed LoadSkulls to false?

**Comment by BenCodez** [comment]
Might be because I'm not adding the data value to make SKULL to player skull, not sure any good way around that, might just set it as another item or something

**Comment by TomLewis** [comment]
![2020-07-19_19 45 05](https://user-images.githubusercontent.com/144046/87882550-7e85ed00-c9f8-11ea-9389-f73563049d3b.png)
Testing the Heads showing in-game while, It updated the first 2 after about 30 seconds, but the other 3 didnt get their skins, errors to go with this part;
```
[19:42:43] [Server thread/INFO]: [GriefPrevention] GodsDead placed a sign @ PirateCraft_1: x-202, z543;[VotingPlugin];1;Monthly
[19:42:43] [Server thread/WARN]: [VotingPlugin] Task #1366 for VotingPlugin v5.22 generated an exception
java.lang.NoSuchMethodError: 'org.bukkit.block.data.BlockData org.bukkit.block.BlockState.getBlockData()'
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler.updateSkulls(SignHandler.java:263) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler.checkSkulls(SignHandler.java:108) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler$2.run(SignHandler.java:251) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1617]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[19:42:57] [Server thread/INFO]: Shiver me timbers! Unknown Command Landlubber, try "/info" and "/help"
[19:43:09] [Server thread/INFO]: GodsDead issued server command: /skull godsdead
[19:43:29] [Server thread/INFO]: [GriefPrevention] GodsDead placed a sign @ PirateCraft_1: x-202, z543;[VotingPlugin];1;Monthly
[19:43:29] [Server thread/WARN]: [VotingPlugin] Task #1425 for VotingPlugin v5.22 generated an exception
java.lang.NoSuchMethodError: 'org.bukkit.block.data.BlockData org.bukkit.block.BlockState.getBlockData()'
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler.updateSkulls(SignHandler.java:263) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler.checkSkulls(SignHandler.java:108) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler$2.run(SignHandler.java:251) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1617]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[19:43:39] [Server thread/INFO]: GodsDead issued server command: /gm 0
[19:43:57] [Server thread/INFO]: Shiver me timbers! Unknown Command Landlubber, try "/info" and "/help"
[19:44:03] [Server thread/INFO]: [GriefPrevention] GodsDead placed a sign @ PirateCraft_1: x-201, z543;[VotingPlugin];2;Monthly
[19:44:03] [Server thread/WARN]: [VotingPlugin] Task #1483 for VotingPlugin v5.22 generated an exception
java.lang.NoSuchMethodError: 'org.bukkit.block.data.BlockData org.bukkit.block.BlockState.getBlockData()'
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler.updateSkulls(SignHandler.java:263) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler.checkSkulls(SignHandler.java:108) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler$2.run(SignHandler.java:251) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1617]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[19:44:15] [Server thread/INFO]: GodsDead issued server command: /i sign
[19:44:23] [Server thread/INFO]: [GriefPrevention] GodsDead placed a sign @ PirateCraft_1: x-200, z543;[VotingPlugin];3;Monthly
[19:44:23] [Server thread/WARN]: [VotingPlugin] Task #1514 for VotingPlugin v5.22 generated an exception
java.lang.NoSuchMethodError: 'org.bukkit.block.data.BlockData org.bukkit.block.BlockState.getBlockData()'
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler.updateSkulls(SignHandler.java:263) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler.checkSkulls(SignHandler.java:108) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler$2.run(SignHandler.java:251) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1617]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[19:44:35] [Server thread/INFO]: [GriefPrevention] GodsDead placed a sign @ PirateCraft_1: x-199, z543;[VotingPlugin];4;Monthly
[19:44:36] [Server thread/WARN]: [VotingPlugin] Task #1533 for VotingPlugin v5.22 generated an exception
java.lang.NoSuchMethodError: 'org.bukkit.block.data.BlockData org.bukkit.block.BlockState.getBlockData()'
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler.updateSkulls(SignHandler.java:263) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler.checkSkulls(SignHandler.java:108) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler$2.run(SignHandler.java:251) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1617]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[19:44:36] [Server thread/WARN]: [VotingPlugin] Task #1535 for VotingPlugin v5.22 generated an exception
java.lang.NoSuchMethodError: 'org.bukkit.block.data.BlockData org.bukkit.block.BlockState.getBlockData()'
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler.updateSkulls(SignHandler.java:263) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler.checkSkulls(SignHandler.java:108) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler$2.run(SignHandler.java:251) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1617]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[19:44:46] [Server thread/INFO]: [GriefPrevention] GodsDead placed a sign @ PirateCraft_1: x-198, z543;[VotingPlugin];5;Monthly
[19:44:46] [Server thread/WARN]: [VotingPlugin] Task #1552 for VotingPlugin v5.22 generated an exception
java.lang.NoSuchMethodError: 'org.bukkit.block.data.BlockData org.bukkit.block.BlockState.getBlockData()'
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler.updateSkulls(SignHandler.java:263) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler.checkSkulls(SignHandler.java:108) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler$2.run(SignHandler.java:251) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1617]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[19:44:46] [Server thread/WARN]: [VotingPlugin] Task #1554 for VotingPlugin v5.22 generated an exception
java.lang.NoSuchMethodError: 'org.bukkit.block.data.BlockData org.bukkit.block.BlockState.getBlockData()'
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler.updateSkulls(SignHandler.java:263) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler.checkSkulls(SignHandler.java:108) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler$2.run(SignHandler.java:251) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1617]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[19:44:46] [Server thread/WARN]: [VotingPlugin] Task #1556 for VotingPlugin v5.22 generated an exception
java.lang.NoSuchMethodError: 'org.bukkit.block.data.BlockData org.bukkit.block.BlockState.getBlockData()'
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler.updateSkulls(SignHandler.java:263) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler.checkSkulls(SignHandler.java:108) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Signs.SignHandler$2.run(SignHandler.java:251) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1617]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

Edit: after I relogged the skins showed up, but the errors still percist.

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

I disabled the skulls for vote top on 1.12 (Isn't a way to fix it really that I'll spend time on)

**Comment by TomLewis** [comment]
Thanks Ben, latest build `/vote top` throws the PLAYER_HEAD warning again.


```
[22:13:11] [Craft Scheduler Thread - 23/WARN]: [VotingPlugin] Plugin VotingPlugin v5.22 generated an exception while executing task 2020
java.lang.NoSuchFieldError: PLAYER_HEAD
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Misc.PlayerUtils.getPlayerSkull(PlayerUtils.java:109) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.User.getPlayerHead(User.java:347) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Commands.GUI.PlayerGUIs.openVoteTop(PlayerGUIs.java:567) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Commands.CommandLoader$79.execute(CommandLoader.java:1839) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.CommandAPI.CommandHandler$1.run(CommandHandler.java:399) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1617]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1617]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[22:13:25] [Server thread/INFO]: GodsDead issued server command: /vote top
[22:13:25] [Craft Scheduler Thread - 4/WARN]: [VotingPlugin] Plugin VotingPlugin v5.22 generated an exception while executing task 2030
java.lang.NoSuchFieldError: PLAYER_HEAD
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Misc.PlayerUtils.getPlayerSkull(PlayerUtils.java:109) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.User.getPlayerHead(User.java:347) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Commands.GUI.PlayerGUIs.openVoteTop(PlayerGUIs.java:567) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Commands.CommandLoader$79.execute(CommandLoader.java:1839) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.CommandAPI.CommandHandler$1.run(CommandHandler.java:399) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1617]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1617]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Should fix that.

**Comment by TomLewis** [comment]
So I upgraded to my production today, went to test as a normal user and none of the links can be clicked in chat now...
Mine have been formatted differently for a long time for clearer difference.

![2020-07-23_11 30 25](https://user-images.githubusercontent.com/144046/88277069-00fffc80-ccd8-11ea-9d58-666b6f75e840.png)

```
  Commands:
    # Format for /vote
    # %num% = the number of the site, for a numbered list
    # %url% = site URL
    Vote: 
      Text:
      - '&7&l&m--&8&l&m--&f&lVote PirateCraft!&8&l&m--&7&l&m--'
      
      # If you want to want to use the feature below where the plugin will
      # automaticly list the sites then set the message in the text above
      AutoInputSites: true
      # For each VoteSite
      # make sure to set VoteURL in your VoteSites
      # Requires above to be true
      # Text will be sent before this
      Sites: '%SiteName% &7&m-&r %url%'
      
      # If true, links will always be forced as urls
      ForceLinks: true
      
      # Format for /vote next
```
I even have ForceLinks: true

Example Vote site, I bet its because the color code before the VoteURL, this used to work before I updated.
```
  vote11:
    Enabled: true
    Name: "&6Site &f#11"
    Priority: 1
    ServiceSite: Trackyserver.com
    VoteURL: "&ehttps://piratemc.com/vote11/"
    VoteDelay: 24
    ForceOffline: false
    Item:
      Material: 'GOLD_BLOCK'
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
```

URGH, lame, it is. That means I have to remove all the separating color scheme I have used for URLS to easily separate them.
Please can you fix this, so I can keep my colors on URLS, this has been working previously.

**Comment by TomLewis** [comment]
Much harder to differentiate not being able to set colors on URLS, but at least I found the bug.

![2020-07-23_11 48 34](https://user-images.githubusercontent.com/144046/88278560-7cfb4400-ccda-11ea-803b-715a5edf19d1.png)

**Comment by TomLewis** [comment]
Sorry, another one.

`/vote today` is the same issue with heads.

```
[12:15:24] [Server thread/INFO]: GodsDead issued server command: /vote today
[12:15:24] [Craft Scheduler Thread - 418/WARN]: [VotingPlugin] Plugin VotingPlugin v5.22 generated an exception while executing task 555564
java.lang.NoSuchFieldError: PLAYER_HEAD
	at com.Ben12345rocks.VotingPlugin.Commands.GUI.PlayerGUIs.openVoteToday(PlayerGUIs.java:519) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Commands.CommandLoader$87.execute(CommandLoader.java:2062) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.CommandAPI.CommandHandler$1.run(CommandHandler.java:399) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1617]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1617]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Should do it.

You can't have the color code in the vote url like that (it will include the color code as the url.

You can customize the full vote text under Text: (disable auto input sites)
