### ISSUE TITLE
Error in console - mysql

### ISSUE THREAD

**Issue by bobhenl** [BenCodez/VotingPlugin#903]
**Versions**
#326

**Describe the bug**
Error in console

**To Reproduce**
Not sure, just saw this in console.

**Expected behavior**
Without errors.

**Error**
```
.... [20:51:06 WARN]: java.sql.SQLException: Illegal operation on empty result set.
>.... [20:51:06 WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
>.... [20:51:06 WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
>.... [20:51:06 WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
>.... [20:51:06 WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
>.... [20:51:06 WARN]: at com.mysql.jdbc.ResultSetImpl.checkRowPos(ResultSetImpl.java:780)
>.... [20:51:06 WARN]: at com.mysql.jdbc.ResultSetImpl.getStringInternal(ResultSetImpl.java:5204)
>.... [20:51:06 WARN]: at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5127)
>.... [20:51:06 WARN]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.hikari.pool.HikariProxyResultSet.getString(HikariProxyResultSet.java)
>.... [20:51:06 WARN]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.getExactQuery(MySQL.java:369)
>.... [20:51:06 WARN]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.loadPlayer(MySQL.java:548)
>.... [20:51:06 WARN]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.loadPlayerIfNeeded(MySQL.java:555)
>.... [20:51:06 WARN]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.getExact(MySQL.java:336)
>.... [20:51:06 WARN]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserData.getMySqlRow(UserData.java:116)
>.... [20:51:06 WARN]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserData.getString(UserData.java:141)
>.... [20:51:06 WARN]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.User.isCheckWorld(User.java:599)
>.... [20:51:06 WARN]: at com.Ben12345rocks.VotingPlugin.AdvancedCore.Listeners.WorldChangeEvent$1.run(WorldChangeEvent.java:52)
>.... [20:51:06 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
>.... [20:51:06 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
>.... [20:51:06 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
>.... [20:51:06 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
>.... [20:51:06 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
>.... [20:51:06 WARN]: at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

This better? Build 328

**Comment by bobhenl** [comment]
https://pastebin.com/NBSe1554 @BenCodez ?

**Comment by BenCodez** [comment]
Do a restart?

**Comment by bobhenl** [comment]
yeah I did just if there isn't anything wrong

**Comment by BenCodez** [comment]
What?
