### ISSUE TITLE
BatchUpdateException: Data truncation: Data too long for column 'OfflineRewards' 

### ISSUE THREAD

**Issue by mibby** [BenCodez/VotingPlugin#926]
**Versions**
VotingPlugin dev 363

**Describe the bug**
```
[22:29:56] [Server thread/INFO]: [VotingPlugin] Received a vote from service site 'TopG.org' by player 'SmellyTramp'!
[22:29:57] [Timer-14/WARN]: java.sql.BatchUpdateException: Data truncation: Data too long for column 'OfflineRewards' at row 1
[22:29:57] [Timer-14/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[22:29:57] [Timer-14/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[22:29:57] [Timer-14/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[22:29:57] [Timer-14/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[22:29:57] [Timer-14/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[22:29:57] [Timer-14/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
[22:29:57] [Timer-14/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:386)
[22:29:57] [Timer-14/WARN]: 	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1154)
[22:29:57] [Timer-14/WARN]: 	at com.mysql.jdbc.StatementImpl.executeBatchUsingMultiQueries(StatementImpl.java:1202)
[22:29:57] [Timer-14/WARN]: 	at com.mysql.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:997)
[22:29:57] [Timer-14/WARN]: 	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:954)
[22:29:57] [Timer-14/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
[22:29:57] [Timer-14/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.hikari.pool.HikariProxyStatement.executeBatch(HikariProxyStatement.java)
[22:29:57] [Timer-14/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.updateBatch(MySQL.java:629)
[22:29:57] [Timer-14/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL$3.run(MySQL.java:149)
[22:29:57] [Timer-14/WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[22:29:57] [Timer-14/WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:506)
[22:29:57] [Timer-14/WARN]: Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'OfflineRewards' at row 1
[22:29:57] [Timer-14/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3931)
[22:29:57] [Timer-14/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
[22:29:57] [Timer-14/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:864)
[22:29:57] [Timer-14/WARN]: 	at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:2367)
[22:29:57] [Timer-14/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2725)
[22:29:57] [Timer-14/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
[22:29:57] [Timer-14/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2439)
[22:29:57] [Timer-14/WARN]: 	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:829)
[22:29:57] [Timer-14/WARN]: 	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:923)
[22:29:57] [Timer-14/WARN]: 	at com.mysql.jdbc.StatementImpl.executeBatchUsingMultiQueries(StatementImpl.java:1181)
[22:29:57] [Timer-14/WARN]: 	... 8 more
```
**To Reproduce**
1. Vote on a service.
2. Receive error.

**Expected behavior**
No error.

**Comment by mibby** [comment]
Also noticed this error. The SQL database is running on localhost, so I assume it timed out its own connection and failed to retry?

```
[22:31:41] [Timer-0/WARN]: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 50000ms.
[22:31:41] [Timer-0/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:697)
[22:31:41] [Timer-0/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
[22:31:41] [Timer-0/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
[22:31:41] [Timer-0/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[22:31:41] [Timer-0/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.api.ConnectionManager.getConnection(ConnectionManager.java:80)
[22:31:41] [Timer-0/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.getColumnsQueury(MySQL.java:301)
[22:31:41] [Timer-0/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.clearCacheBasic(MySQL.java:224)
[22:31:41] [Timer-0/WARN]: 	at com.Ben12345rocks.VotingPlugin.Main.update(Main.java:1150)
[22:31:41] [Timer-0/WARN]: 	at com.Ben12345rocks.VotingPlugin.Main$3$1.run(Main.java:410)
[22:31:41] [Timer-0/WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[22:31:41] [Timer-0/WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:506)
[22:31:41] [Timer-0/INFO]: [com.Ben12345rocks.VotingPlugin.AdvancedCore.hikari.HikariDataSource] HikariPool-2 - Starting...
[22:31:41] [Timer-0/WARN]: [VotingPlugin] Loaded class plan.com.mysql.cj.jdbc.Driver from Plan v5.1 build 657 which is not a depend, softdepend or loadbefore of this plugin.
[22:31:41] [Timer-0/INFO]: [com.Ben12345rocks.VotingPlugin.AdvancedCore.hikari.HikariDataSource] HikariPool-2 - Start completed.
[22:31:41] [Timer-0/WARN]: java.lang.NullPointerException
[22:31:41] [Timer-0/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.getColumnsQueury(MySQL.java:302)
[22:31:41] [Timer-0/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.clearCacheBasic(MySQL.java:224)
[22:31:41] [Timer-0/WARN]: 	at com.Ben12345rocks.VotingPlugin.Main.update(Main.java:1150)
[22:31:41] [Timer-0/WARN]: 	at com.Ben12345rocks.VotingPlugin.Main$3$1.run(Main.java:410)
[22:31:41] [Timer-0/WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[22:31:41] [Timer-0/WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:506)
```

**Comment by BenCodez** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Should fix the first error, expanded the size for that column

Not really sure about the second one though
