### ISSUE TITLE
Users.db-journal (No such file)

### ISSUE THREAD

**Issue by mrfloris** [BenCodez/VotingPlugin#956]
```
[00:00:57 INFO]: [VotingPlugin] Time change event: DAY, Fake: false
[00:00:57 INFO]: [VotingPlugin] Time change event: WEEK, Fake: false
[00:00:58 INFO]: [VotingPlugin] Saving TopVoters Daily
[00:00:59 WARN]: java.io.FileNotFoundException: plugins/VotingPlugin/Users.db-journal (No such file or directory)
[00:00:59 WARN]:        at java.base/java.io.FileInputStream.open0(Native Method)
[00:00:59 WARN]:        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
[00:00:59 WARN]:        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
[00:00:59 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Backups.ZipCreator.addToZip(ZipCreator.java:90)
[00:00:59 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Backups.ZipCreator.writeZipFile(ZipCreator.java:158)
[00:00:59 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Backups.ZipCreator.create(ZipCreator.java:130)
[00:00:59 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.Backups.BackupHandle.onDateChange(BackupHandle.java:46)
[00:00:59 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1260.execute(Unknown Source)
[00:00:59 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[00:00:59 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[00:00:59 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:00:59 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[00:00:59 WARN]:        at com.Ben12345rocks.VotingPlugin.AdvancedCore.TimeChecker.TimeChecker$1.run(TimeChecker.java:80)
[00:00:59 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[00:00:59 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[00:00:59 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[00:00:59 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[00:00:59 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[00:00:59 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[00:00:59 INFO]: [VotingPlugin] Created zip file at /Users/floris/MinecraftServer/live-1mb-2.8.3-mc-1.16.3/plugins/VotingPlugin/Backups/Backup-2020_SEPTEMBER_20.zip
[00:00:59 INFO]: [VotingPlugin] Saving TopVoters Weekly
```

Just reporting back that i noticed it spit out something when it couldn't find the file before creating one. 
```
> ver Votifier
[09:01:16 INFO]: Votifier version 2.7.1
[09:01:16 INFO]: A plugin that gets notified when votes are made for the server on toplists.
[09:01:16 INFO]: Authors: Ichbinjoe, blakeman8192, Kramer and tuxed
> ver VotingPlugin
[09:01:19 INFO]: VotingPlugin version 5.23.3
[09:01:19 INFO]: Highly Customizable Voting Listener!
[09:01:19 INFO]: Website: https://www.spigotmc.org/resources/votingplugin.15358/
[09:01:19 INFO]: Author: Ben12345rocks
> ver
[09:01:21 INFO]: This server is running Paper version git-Paper-198 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[09:01:21 INFO]: Checking version, please wait...
[09:01:21 INFO]: Previous version: git-Paper-138 (MC: 1.16.1)
[09:01:21 INFO]: You are 4 version(s) behind
>
```

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin/

Should help.

**Comment by mrfloris** [comment]
Thank you, upgrading later tonight and let's see if this helps 👍

**Comment by mrfloris** [comment]
Sorry for not following up. I have upgraded since and haven't had any issues yet with this. So I guess it's fair to assume it's resolved.
