### ISSUE TITLE
Saw this error by coincidence

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#963]
**Versions**
VotingPlugin 5.23.3 
Paper (fork) 1.16.3

**Describe the bug**
```
[15:22:37] [Server thread/INFO]: Someplayer123 issued server command: /vote
[15:22:41] [Server thread/ERROR]: Could not pass event InventoryClickEvent to VotingPlugin v5.23.3
java.lang.NullPointerException: null
at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Inventory.BInventory.onInventoryClick(BInventory.java:463) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor880.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Purpur-766]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.3.jar:git-Purpur-766]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Purpur-766]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Purpur-766]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2496) ~[patched_1.16.3.jar:git-Purpur-766]
at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.3.jar:git-Purpur-766]
at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.3.jar:git-Purpur-766]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.3.jar:git-Purpur-766]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Purpur-766]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Purpur-766]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Purpur-766]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Purpur-766]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1203) ~[patched_1.16.3.jar:git-Purpur-766]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1196) ~[patched_1.16.3.jar:git-Purpur-766]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Purpur-766]
at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1172) ~[patched_1.16.3.jar:git-Purpur-766]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1016) ~[patched_1.16.3.jar:git-Purpur-766]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.3.jar:git-Purpur-766]
at java.lang.Thread.run(Thread.java:834) [?:?]
```

**To Reproduce**
Not sure how

**Expected behavior**
No errors :)

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin/

Should solve that.

**Comment by x1p** [comment]
Ok, thnx. I've put it on the server.
I won't be able to tell the difference since it seem to happen quite rarely. So I suggest to close this issue in confidence that it's solved.
