### ISSUE TITLE
Velocity Support

### ISSUE THREAD

**Issue by kubo6472** [BenCodez/VotingPlugin#971]
**Is your feature request related to a problem? Please describe.**
Can't use on velocity proxy

**Describe the solution you'd like**
Please integrate the support for velocity proxy

**Describe alternatives you've considered**
Finding another plugin, which is due to tight integration between namelessMC and votingplugin quite impossible.

**Comment by BenCodez** [comment]
Got links to that? Never heard of velocity, no idea what it is.

**Comment by kubo6472** [comment]
velocitypowered.com it's like a waterfall/bungee cord alternative. Got its own API and stuff.

**Comment by BenCodez** [comment]
Would be a bit difficult, but I'll see what I can do.

**Comment by kubo6472** [comment]
Thank you very much. If there's anything I may help with, I'll try my best.

**Comment by galacticwarrior9** [comment]
Going to bump this since it automatically closed, if you don't mind. [Velocity](https://velocitypowered.com/) is an excellent, performant alternative to BungeeCord and its forks. It is being adopted by an increasing number of networks, including mine. The issue is that it has its own [API ](https://velocitypowered.com/wiki/developers/api-basics/), so I understand if there is neither the willpower or time to support it from your end.

**Comment by BenCodez** [comment]
It's on my list to do within next 2 weeks or so I hope. Remind me if that doesn't happen.

**Comment by kubo6472** [comment]
> It's on my list to do within next 2 weeks or so I hope. Remind me if that doesn't happen.

Aight got it. We actually started using this on a single server in a velocity proxy network and are quite happy I must say.

**Comment by BenCodez** [comment]
I've spent a few hours taking a stab at adding velocity support. The biggest hurdle is not being able to use yml files on velocity (without adding my API to it), since toml files don't seem to be able to do what I need, atleast not easily. 

For now I'll take a break on it, get back to it at some point. 

But unless anyone knows a good way to add yml file support to velocity (a copy of bungeecord API is preferred) it might take A LOT of work, which I probably won't do anytime soon. Maybe they could add it in velocity directly?

**Comment by kubo6472** [comment]
> (a copy of bungeecord API is preferred)

https://github.com/Phoenix616/Snap

**Comment by kubo6472** [comment]
> But unless anyone knows a good way to add yml file support to velocity

https://github.com/VelocityPowered/Velocity/issues/451#issuecomment-808857875

**Comment by astei** [comment]
> But unless anyone knows a good way to add yml file support to velocity (a copy of bungeecord API is preferred) it might take A LOT of work, which I probably won't do anytime soon. Maybe they could add it in velocity directly?

The Velocity API comes with [Configurate](https://github.com/SpongePowered/Configurate) and bundles YAML support. [This might be helpful too](https://github.com/SpongePowered/Configurate/wiki/From-Bukkit-Configuration).

**Comment by BenCodez** [comment]
Thanks, that should help a lot. Will look into this a lot more later when I get the chance.

**Comment by BenCodez** [comment]
> > (a copy of bungeecord API is preferred)
> 
> https://github.com/Phoenix616/Snap

I ran a test using snap and was able to get it to work without any changes. It also seemed to function properly. So I guess technically VotingPlugin can run on bungee with that. Thanks @kubo6472 for that

Not sure if it's worth the effort to custom code a plugin when this solution seems to work pretty well.

**Comment by astei** [comment]
We strongly prefer native plugins over the compatibility layer (which is not even something we support).

**Comment by BenCodez** [comment]
@astei If I really get the chance to do then I will. But it would take awhile to do that, also really depends on the demand for it.

**Comment by kubo6472** [comment]
Totally understand. I think some demand will come. Since I knew nameless since 2017, which I found when browsing spigotmc. And then, when browsing namelessmc addons, I stumbled upon this cool plugin. It wouldn't be the first, that will be run through snap. If I will ran into some problems down the line, I'll definitely let you know. Thanks for your time and trying to make it work. I'll not close this yet, and bump it a few times to stay open, but I will deploy the bungee version then.

**Comment by Skizzles** [comment]
Was looking into velocity and this is something I would love.

Definitely feel more people would enjoy this.

**Comment by BenCodez** [comment]
@Skizzles I'm hoping to make a push in the next few weeks to add direct support for it. Just keep nagging me if I don't add it :)

**Comment by kubo6472** [comment]
> 
> 
> @Skizzles I'm hoping to make a push in the next few weeks to add direct support for it. Just keep nagging me if I don't add it :)

How's it going?

**Comment by BenCodez** [comment]
> > @Skizzles I'm hoping to make a push in the next few weeks to add direct support for it. Just keep nagging me if I don't add it :)
> 
> How's it going?

Made a little attempt yesterday, but for now it won't be going anywhere for right now, but I made some progress atleast, won't be anytime soon

**Comment by BenCodez** [comment]
Anyone happen to know exactly what the cause of this is?
http://bencodez.com/job/VotingPlugin/
https://github.com/BenCodez/VotingPlugin/commit/3b7f8afe76069cc5527fdfbe4e0aef9f670385cf

Can't figure it out right now.

```
[15:42:50] [main/ERROR]: Can't create module for plugin votingplugin
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:339) ~[?:?]
	at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:281) ~[?:?]
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:316) ~[?:?]
	at java.util.jar.JarVerifier.update(JarVerifier.java:230) ~[?:?]
	at java.util.jar.JarFile.initializeVerifier(JarFile.java:757) ~[?:?]
	at java.util.jar.JarFile.ensureInitialization(JarFile.java:1028) ~[?:?]
	at java.util.jar.JavaUtilJarAccessImpl.ensureInitialization(JavaUtilJarAccessImpl.java:72) ~[?:?]
	at jdk.internal.loader.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:873) ~[?:?]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:479) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:420) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:414) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:691) ~[?:?]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:413) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:66) ~[velocity-1.1.5.jar:1.1.5]
	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:60) ~[velocity-1.1.5.jar:1.1.5]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:88) ~[velocity-1.1.5.jar:1.1.5]
	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:122) ~[velocity-1.1.5.jar:1.1.5]
	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:283) ~[velocity-1.1.5.jar:1.1.5]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:225) ~[velocity-1.1.5.jar:1.1.5]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:75) ~[velocity-1.1.5.jar:1.1.5]```

**Comment by astei** [comment]
[This suggests that there is an issue with your shading of dependencies](https://stackoverflow.com/a/34856095).

**Comment by BenCodez** [comment]
http://bencodez.com/job/VotingPlugin%20-%20With%20MySQL%20Driver/

I have votingplugin working on velocity now. That link above includes a jar with mysql driver included (since velocity doesn't include that), but due to the the jar size being so much bigger I'll probably leave this as a separate build or a separate jar for mysql driver.

Only thing that I know doesn't work right now is copying the default config, don't have time to implement that. But the rest should work like on bungeecoord (config, commands, etc). You'll also need to set mysql information before it works.

**Comment by kubo6472** [comment]
Sending example of the separate MySQL plugin for another plugin I use: https://simonsator.de/repo/de/simonsator/MySQL-And-Configurate-For-Velocity/1.0.0/

**Comment by kubo6472** [comment]
Okay, I spent the last hour trying to supply a valid velocity config file to the plugin, being unsuccessful. I even went as far to try jdc on the thing and look where the config location or filename may lie. Still nothing. So am I turning for a little help now. 

How is please the wanted config file called and where it should be put? Thanks.

**Comment by BenCodez** [comment]
@kubo6472 Can you send what you got? There should be a blank file when you start up

**Comment by kubo6472** [comment]
A rather long error spam from the build #5 and no folder or file generated whatsoever: https://hastebin.com/dexefuvutu.sql

**Comment by BenCodez** [comment]
try build #6 when it builds

**Comment by kubo6472** [comment]
Fixed it mostly somehow:
```
[21:26:47 ERROR]: 5 [Velocity Event Executor - #0] INFO com.bencodez.votingplugin.advancedcore.hikari.HikariDataSource - HikariPool-1 - Starting...
[21:26:47 ERROR]: 202 [Velocity Event Executor - #0] INFO com.bencodez.votingplugin.advancedcore.hikari.HikariDataSource - HikariPool-1 - Start completed.
[21:26:48 ERROR]: Some errors occurred whilst posting event ProxyInitializeEvent.
[21:26:48 ERROR]: #1: 

java.lang.IllegalStateException: bStats Metrics class has not been relocated correctly!
        at org.bstats.MetricsBase.checkRelocation(MetricsBase.java:220) ~[?:?]
        at org.bstats.MetricsBase.<init>(MetricsBase.java:104) ~[?:?]
        at org.bstats.velocity.Metrics.<init>(Metrics.java:84) ~[?:?]
        at org.bstats.velocity.Metrics.<init>(Metrics.java:18) ~[?:?]
        at org.bstats.velocity.Metrics$Factory.make(Metrics.java:49) ~[?:?]
        at com.bencodez.votingplugin.bungee.velocity.VotingPluginVelocity.onProxyInitialization(VotingPluginVelocity.java:305) ~[?:?]
        at net.kyori.event.asm.generated.3b281f83d1.VotingPluginVelocity-onProxyInitialization-ProxyInitializeEvent-4.invoke(Unknown Source) ~[?:?]
        at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[velocity.jar:1.1.6-SNAPSHOT (git-06ecab26-b430)]
        at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[velocity.jar:1.1.6-SNAPSHOT (git-06ecab26-b430)]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:154) ~[velocity.jar:1.1.6-SNAPSHOT (git-06ecab26-b430)]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$1(VelocityEventManager.java:136) ~[velocity.jar:1.1.6-SNAPSHOT (git-06ecab26-b430)]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

using build #3

trying build #7 now

**Comment by kubo6472** [comment]
Aight, some insights. Build 7 still does not generate the files. But. The moment I create the file votingplugin/bungeeconfig.yml it generates the rest on the next server startup.

**Comment by BenCodez** [comment]
@kubo6472 You'll need to copy the file from https://github.com/BenCodez/VotingPlugin/blob/master/VotingPlugin/Resources/bungeeconfig.yml

**Comment by kubo6472** [comment]
> @kubo6472 You'll need to copy the file from https://github.com/BenCodez/VotingPlugin/blob/master/VotingPlugin/Resources/bungeeconfig.yml

Yep, that is the file I got there now. Filled with the MSQL database connection information.

**Comment by BenCodez** [comment]
@kubo6472 Didn't really work on that part of it yet, but from there it should be good as far as I know

**Comment by kubo6472** [comment]
> @kubo6472 Didn't really work on that part of it yet, but from there it should be good as far as I know

It is now. Thanks.

**Comment by BenCodez** [comment]
Velocity should now be fully supported: http://bencodez.com/job/VotingPlugin/

MySQL driver if needed: http://bencodez.com/job/MySQLDriver/

I'll probably make an update once 1.17 comes out.
