### ISSUE TITLE
exception while executing task 7007086

### ISSUE THREAD

**Issue by mrfloris** [BenCodez/VotingPlugin#985]
**Versions**
Plugin version and spigot version.
```
> ver
[16:06:12 INFO]: This server is running Paper version git-Paper-220 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[16:06:12 INFO]: Checking version, please wait...
[16:06:12 INFO]: Previous version: git-Paper-216 (MC: 1.16.3)
[16:06:12 INFO]: You are running the latest version
> ver VotingPlugin
[16:06:14 INFO]: VotingPlugin version 5.24.1
[16:06:14 INFO]: Highly Customizable Voting Listener!
[16:06:14 INFO]: Website: https://www.spigotmc.org/resources/votingplugin.15358/
[16:06:14 INFO]: Author: BenCodez
> ver Votifier
[16:06:21 INFO]: Votifier version 3.0.0-SNAPSHOT
[16:06:21 INFO]: A plugin that gets notified when votes are made for the server on toplists.
[16:06:21 INFO]: Authors: Ichbinjoe, blakeman8192, Kramer and tuxed
>
```
**Describe the bug**
Saw someone type /vote and it spit out an exception error

```
[15:53:58 INFO]: LaureatePoem120 issued server command: /vote
[15:53:58 WARN]: [VotingPlugin] Plugin VotingPlugin v5.24.1 generated an exception while executing task 7007086
xyz.upperlevel.spigot.book.NmsBookHelper$UnsupportedVersionException: Error while executing reflections, submit to developers the following log (version: v1_16_R2)
        at xyz.upperlevel.spigot.book.NmsBookHelper.setPages(NmsBookHelper.java:145) ~[?:?]
        at xyz.upperlevel.spigot.book.BookUtil$BookBuilder.pages(BookUtil.java:146) ~[?:?]
        at com.Ben12345rocks.VotingPlugin.Commands.GUI.PlayerGUIs.openVoteURL(PlayerGUIs.java:846) ~[?:?]
        at com.Ben12345rocks.VotingPlugin.Commands.CommandLoader$100.execute(CommandLoader.java:2356) ~[?:?]
        at com.Ben12345rocks.VotingPlugin.AdvancedCore.CommandAPI.CommandHandler$1.run(CommandHandler.java:399) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-220]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.3.jar:git-Paper-220]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Paper-220]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at xyz.upperlevel.spigot.book.NmsBookHelper.setPages(NmsBookHelper.java:142) ~[?:?]
        ... 10 more
Caused by: com.google.gson.JsonParseException: Don't know how to turn {"value":[{"text":"https://omgboards.com/link-forums/503/"}]} into a Component
        at net.minecraft.server.v1_16_R2.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:205) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:101) ~[patched_1.16.3.jar:git-Paper-220]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[patched_1.16.3.jar:git-Paper-220]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.16.3.jar:git-Paper-220]
        at com.google.gson.Gson.fromJson(Gson.java:952) ~[patched_1.16.3.jar:git-Paper-220]
        at com.google.gson.Gson.fromJson(Gson.java:925) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:364) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.ChatHoverable.a(SourceFile:97) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.ChatModifier$ChatModifierSerializer.b(ChatModifier.java:288) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.ChatModifier$ChatModifierSerializer.deserialize(ChatModifier.java:259) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.ChatModifier$ChatModifierSerializer.deserialize(ChatModifier.java:239) ~[patched_1.16.3.jar:git-Paper-220]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[patched_1.16.3.jar:git-Paper-220]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.16.3.jar:git-Paper-220]
        at com.google.gson.Gson.fromJson(Gson.java:952) ~[patched_1.16.3.jar:git-Paper-220]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:237) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:233) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:233) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:101) ~[patched_1.16.3.jar:git-Paper-220]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.ChatDeserializer.a(SourceFile:493) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.ChatDeserializer.a(SourceFile:517) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:359) ~[patched_1.16.3.jar:git-Paper-220]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at xyz.upperlevel.spigot.book.NmsBookHelper.setPages(NmsBookHelper.java:142) ~[?:?]
        ... 10 more
```

**Comment by BenCodez** [comment]
Add www. in the url? If not send your config and Votesites.yml

**Comment by mrfloris** [comment]
I don't see why www. is a requirement. The domains are valid.

**Comment by BenCodez** [comment]
It's a minecraft limitation with the book

**Comment by mrfloris** [comment]
Ugh, ok

**Comment by mrfloris** [comment]
Update: I've added www. and made sure they work and redirect properly etc. It's all good now. Thanks for the tip.
